ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'FILL_BLANK';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'ERROR_CORRECTION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'REORDER';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TRANSLATION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'SENTENCE_CREATION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'AI_DIALOGUE';

ALTER TABLE "ReadingArticle"
ADD COLUMN "summary" TEXT NOT NULL DEFAULT '',
ADD COLUMN "oralRetellingPrompt" TEXT NOT NULL DEFAULT '',
ADD COLUMN "writingExtensionPrompt" TEXT NOT NULL DEFAULT '';

ALTER TABLE "ListeningProgress" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
