import Link from "next/link";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";
import { addReadingQuestion, deleteReadingQuestion, updateContentStatus, updateReadingMetadata } from "@/modules/admin/actions";
import { readingPublishReadiness } from "@/modules/admin/content-schemas";

const levels = ["PRE_A1", "A1", "A2", "B1", "B2", "C1", "C2"];
const questionTypes = ["MULTIPLE_CHOICE", "TRUE_FALSE", "SHORT_ANSWER", "VOCABULARY"];

export default async function ReadingEditorPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSystemAdmin();
  const english = (await cookies()).get("ui_locale")?.value === "en";
  const { id } = await params;
  const article = await db.readingArticle.findUnique({ where: { id }, include: { questions: { orderBy: { order: "asc" } } } });
  if (!article) notFound();
  const missing = readingPublishReadiness({ questions: article.questions.length, targetVocabulary: article.targetVocabulary.length, summary: article.summary, oralRetellingPrompt: article.oralRetellingPrompt, writingExtensionPrompt: article.writingExtensionPrompt });
  const t = english ? {
    back: "Back to content", editor: "Graded reading editor", source: "Source", ai: "AI generated", manual: "Manually authored", words: "words", status: "Status", update: "Update status", readiness: "Publication readiness", ready: "Ready to publish", missing: "Still required", info: "Article and learning design", title: "Title", body: "English article", translation: "Chinese translation (optional)", audience: "Audience", topic: "Topic", vocabulary: "Target vocabulary, comma separated", grammar: "Target grammar, comma separated", summary: "Article summary", retell: "Oral retelling prompt", writing: "Writing extension prompt", save: "Save article", questions: "Comprehension and application questions", add: "Add question", prompt: "Prompt", options: "Options, one per line (not needed for short answer)", answer: "Answer key (must exactly match an option where applicable)", explanation: "Explanation (optional)", remove: "Remove"
  } : {
    back: "返回内容管理", editor: "分级阅读课程编辑器", source: "内容来源", ai: "AI 生成", manual: "人工编写", words: "词", status: "状态", update: "更新状态", readiness: "发布完整度", ready: "已经达到发布标准", missing: "仍需补齐", info: "文章与学习设计", title: "文章标题", body: "英文文章正文", translation: "中文翻译（可选）", audience: "适用人群", topic: "主题", vocabulary: "目标词汇（用逗号分隔）", grammar: "目标语法（用逗号分隔）", summary: "文章总结", retell: "口头复述任务", writing: "写作延伸任务", save: "保存文章", questions: "理解与应用题", add: "新增题目", prompt: "题目", options: "选项（每行一项；简答题不需要）", answer: "标准答案（有选项时必须与某个选项完全一致）", explanation: "答案解析（可选）", remove: "删除"
  };
  return <div className="mx-auto max-w-6xl">
    <Link className="text-sm font-bold text-brand" href="/admin/content">← {t.back}</Link>
    <div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-brand">{article.level} · {article.topic}</p><h1 className="mt-1 text-4xl font-black">{t.editor}</h1><p className="mt-2 text-muted">{t.source}: {article.aiGenerated ? t.ai : t.manual} · {article.wordCount} {t.words}</p></div><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value="reading"/><input type="hidden" name="id" value={article.id}/><label><span className="label">{t.status}</span><select className="input" name="status" defaultValue={article.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><button className="button-primary">{t.update}</button></form></div>
    <section className={missing.length ? "mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-100" : "mt-6 rounded-2xl border border-emerald-300 bg-emerald-50 p-5 text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"}><h2 className="font-black">{t.readiness}</h2><p className="mt-2">{missing.length ? `${t.missing}: ${missing.join(english ? ", " : "、")}` : `✓ ${t.ready}`}</p></section>
    <section className="card mt-6"><h2 className="text-2xl font-black">{t.info}</h2><form action={updateReadingMetadata} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="articleId" value={article.id}/><Field name="title" label={t.title} value={article.title}/><label><span className="label">CEFR</span><select className="input" name="level" defaultValue={article.level}>{levels.map(level=><option key={level}>{level}</option>)}</select></label><Field name="audience" label={t.audience} value={article.audience}/><Field name="topic" label={t.topic} value={article.topic}/><Area name="body" label={t.body} value={article.body} tall/><Area name="translation" label={t.translation} value={article.translation ?? ""} tall/><Area name="targetVocabulary" label={t.vocabulary} value={article.targetVocabulary.join(", ")}/><Area name="targetGrammar" label={t.grammar} value={article.targetGrammar.join(", ")}/><Area name="summary" label={t.summary} value={article.summary}/><Area name="oralRetellingPrompt" label={t.retell} value={article.oralRetellingPrompt}/><Area name="writingExtensionPrompt" label={t.writing} value={article.writingExtensionPrompt}/><button className="button-primary md:col-span-2">{t.save}</button></form></section>
    <section className="card mt-6"><h2 className="text-2xl font-black">{t.questions} ({article.questions.length})</h2><div className="mt-4 grid gap-3">{article.questions.map(item=><div key={item.id} className="flex items-start justify-between gap-3 rounded-xl bg-slate-100 p-4 dark:bg-slate-800"><div><strong>{item.order}. [{item.type}] {item.prompt}</strong><p className="mt-1 text-sm text-muted">{t.answer}: {item.answerKey}</p>{item.explanation&&<p className="mt-1 text-sm text-muted">{item.explanation}</p>}</div><form action={deleteReadingQuestion}><input type="hidden" name="articleId" value={article.id}/><input type="hidden" name="id" value={item.id}/><button className="text-xs font-bold text-red-700">{t.remove}</button></form></div>)}</div><form action={addReadingQuestion} className="mt-6 grid gap-3 border-t pt-6 md:grid-cols-2"><input type="hidden" name="articleId" value={article.id}/><label><span className="label">Type</span><select className="input" name="type">{questionTypes.map(type=><option key={type}>{type}</option>)}</select></label><Field name="prompt" label={t.prompt}/><Area name="options" label={t.options}/><Field name="answerKey" label={t.answer}/><Field name="explanation" label={t.explanation} optional/><button className="button-primary md:col-span-2">{t.add}</button></form></section>
  </div>;
}

function Field({ name, label, value = "", optional = false }: { name: string; label: string; value?: string; optional?: boolean }) { return <label><span className="label">{label}</span><input className="input" name={name} defaultValue={value} required={!optional}/></label>; }
function Area({ name, label, value = "", tall = false }: { name: string; label: string; value?: string; tall?: boolean }) { return <label><span className="label">{label}</span><textarea className={`input ${tall ? "min-h-80" : "min-h-28"}`} name={name} defaultValue={value}/></label>; }
