import Link from "next/link";
import { cookies } from "next/headers";
import { db } from "@/lib/db";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";
import { createGrammarTopic, createListeningExercise, createReadingArticle, createScenarioLesson, createVocabulary, updateContentDetails, updateContentStatus } from "@/modules/admin/actions";

const levels = ["PRE_A1", "A1", "A2", "B1", "B2", "C1"];
export default async function AdminContentPage() {
  await requireSystemAdmin();
  const english = (await cookies()).get("ui_locale")?.value === "en";
  const t=english?{title:"Courses and content",intro:"Human- or AI-authored content is saved as a draft first. Publish it only after review.",generate:"Generate graded reading with AI",labels:{vocabulary:"Vocabulary",reading:"Reading",grammar:"Grammar",scenario:"Scenario",listening:"Listening"},newVocabulary:"New vocabulary",newReading:"New reading",newListening:"New listening",newGrammar:"New grammar",newScenario:"New scenario lesson",word:"Word",phonetic:"Phonetic",part:"Part of speech",definitionEn:"English definition",definitionZh:"Chinese definition",topic:"Topic",itemTitle:"Title",body:"English text",translation:"Chinese translation",audience:"Age / audience",targetVocabulary:"Target vocabulary, comma-separated",targetGrammar:"Target grammar, comma-separated",transcript:"English transcript",audio:"Optional audio URL",slug:"Slug, e.g. present-perfect",ruleEn:"English rule",ruleZh:"Chinese explanation",useCases:"Use cases, one per line",errors:"Common errors, one per line",category:"Category",introField:"Scenario introduction",edit:"Edit content",titleWord:"Title / word",topicCategory:"Topic / category",primary:"English text / rule / definition",secondary:"Chinese translation / explanation",saveRevision:"Save revision",updateStatus:"Update status",empty:"No content yet. Add content or run the idempotent seed.",saveDraft:"Save draft"}:{title:"课程与内容",intro:"人工或 AI 创建后先保存为草稿，审核无误再发布。",generate:"AI 生成分级阅读",labels:{vocabulary:"词汇",reading:"阅读",grammar:"语法",scenario:"场景",listening:"听力"},newVocabulary:"新增词汇",newReading:"新增阅读",newListening:"新增听力",newGrammar:"新增语法",newScenario:"新增场景课程",word:"单词",phonetic:"音标",part:"词性",definitionEn:"英文解释",definitionZh:"中文解释",topic:"主题",itemTitle:"标题",body:"英文正文",translation:"中文翻译",audience:"年龄/受众",targetVocabulary:"目标词汇，逗号分隔",targetGrammar:"目标语法，逗号分隔",transcript:"英文听力稿",audio:"可选音频 URL",slug:"slug，例如 present-perfect",ruleEn:"英文规则",ruleZh:"中文解释",useCases:"适用场景，每行一项",errors:"常见错误，每行一项",category:"分类",introField:"场景介绍",edit:"编辑内容",titleWord:"标题/单词",topicCategory:"主题/分类",primary:"英文正文/规则/解释",secondary:"中文翻译/解释",saveRevision:"保存修订",updateStatus:"更新状态",empty:"暂无内容，请新增内容或运行幂等 seed。",saveDraft:"保存草稿"};
  const [vocabulary, reading, grammar, scenario, listening] = await Promise.all([
    db.vocabulary.findMany({ take: 100, orderBy: { updatedAt: "desc" }, include: { meanings: { where: { locale: "zh-CN", senseOrder: 1 }, take: 1 } } }),
    db.readingArticle.findMany({ take: 100, orderBy: { updatedAt: "desc" } }),
    db.grammarTopic.findMany({ take: 100, orderBy: { updatedAt: "desc" } }),
    db.scenarioLesson.findMany({ take: 100, orderBy: { updatedAt: "desc" } }),
    db.listeningExercise.findMany({ take: 100, orderBy: { updatedAt: "desc" } })
  ]);
  const rows = [
    ...vocabulary.map((item) => ({ type: "vocabulary", id: item.id, title: item.word, primary: item.definitionEn, secondary: item.meanings[0]?.definition ?? "", topic: item.topic, level: item.level, status: item.status })),
    ...reading.map((item) => ({ type: "reading", id: item.id, title: item.title, primary: item.body, secondary: item.translation ?? "", topic: item.topic, level: item.level, status: item.status })),
    ...grammar.map((item) => ({ type: "grammar", id: item.id, title: item.title, primary: item.ruleEn, secondary: item.ruleZh, topic: "", level: item.level, status: item.status })),
    ...scenario.map((item) => ({ type: "scenario", id: item.id, title: item.title, primary: item.intro, secondary: "", topic: item.category, level: item.level, status: item.status })),
    ...listening.map((item) => ({ type: "listening", id: item.id, title: item.title, primary: item.transcript, secondary: item.translation ?? "", topic: item.topic, level: item.level, status: item.status }))
  ];
  return <div className="mx-auto max-w-6xl">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-4xl font-black">{t.title}</h1><p className="mt-2 text-muted">{t.intro}</p></div><Link className="button-primary" href="/admin/content/generate-reading">{t.generate}</Link></div>
    <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-5">
      <CreateCard title={t.newVocabulary} submit={t.saveDraft} action={createVocabulary}><Text name="word" label={t.word}/><Text name="phonetic" label={t.phonetic} optional/><Text name="partOfSpeech" label={t.part}/><Text name="definitionEn" label={t.definitionEn}/><Text name="definitionZh" label={t.definitionZh}/><Text name="topic" label={t.topic}/><Level/></CreateCard>
      <CreateCard title={t.newReading} submit={t.saveDraft} action={createReadingArticle}><Text name="title" label={t.itemTitle}/><Area name="body" label={t.body}/><Area name="translation" label={t.translation} optional/><Text name="audience" label={t.audience}/><Text name="topic" label={t.topic}/><Text name="targetVocabulary" label={t.targetVocabulary} optional/><Text name="targetGrammar" label={t.targetGrammar} optional/><Level/></CreateCard>
      <CreateCard title={t.newListening} submit={t.saveDraft} action={createListeningExercise}><Text name="title" label={t.itemTitle}/><Area name="transcript" label={t.transcript}/><Area name="translation" label={t.translation} optional/><Text name="topic" label={t.topic}/><Text name="audioUrl" label={t.audio} optional/><Level/></CreateCard>
      <CreateCard title={t.newGrammar} submit={t.saveDraft} action={createGrammarTopic}><Text name="slug" label={t.slug}/><Text name="title" label={t.itemTitle}/><Area name="ruleEn" label={t.ruleEn}/><Area name="ruleZh" label={t.ruleZh}/><Area name="useCases" label={t.useCases} optional/><Area name="commonErrors" label={t.errors} optional/><Level/></CreateCard>
      <CreateCard title={t.newScenario} submit={t.saveDraft} action={createScenarioLesson}><Text name="category" label={t.category}/><Text name="title" label={t.itemTitle}/><Area name="intro" label={t.introField}/><Level/></CreateCard>
    </section>
    <div className="card mt-6 space-y-3">{rows.map((row) => <details key={`${row.type}-${row.id}`} className="rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><summary className="flex cursor-pointer flex-wrap items-center justify-between gap-3"><div><span className="mr-3 rounded-full bg-brand/10 px-2 py-1 text-xs font-bold text-brand">{t.labels[row.type as keyof typeof t.labels]}</span><strong>{row.title}</strong><span className="ml-2 text-xs text-muted">{row.level} · {row.status}</span></div><span className="text-sm text-brand">{t.edit}</span></summary><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_auto]"><form action={updateContentDetails} className="grid gap-3 md:grid-cols-2"><input type="hidden" name="type" value={row.type}/><input type="hidden" name="id" value={row.id}/><Text name="title" label={t.titleWord} value={row.title}/><Text name="topic" label={t.topicCategory} value={row.topic} optional/><label className="md:col-span-2"><span className="label">{t.primary}</span><textarea className="input min-h-32" name="primary" defaultValue={row.primary} required/></label><label className="md:col-span-2"><span className="label">{t.secondary}</span><textarea className="input min-h-24" name="secondary" defaultValue={row.secondary}/></label><Level value={row.level}/><button className="button-primary">{t.saveRevision}</button></form><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value={row.type}/><input type="hidden" name="id" value={row.id}/><select className="input" name="status" defaultValue={row.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select><button className="button-ghost">{t.updateStatus}</button></form></div></details>)}{!rows.length && <p className="text-muted">{t.empty}</p>}</div>
  </div>;
}

function CreateCard({ title, submit, action, children }: { title: string; submit:string; action: (formData: FormData) => Promise<void>; children: React.ReactNode }) { return <details className="card"><summary className="cursor-pointer text-lg font-black">{title}</summary><form action={action} className="mt-4 space-y-3">{children}<button className="button-primary w-full">{submit}</button></form></details>; }
function Text({ name, label, optional = false, value }: { name: string; label: string; optional?: boolean; value?: string }) { return <input className="input" name={name} placeholder={label} defaultValue={value} required={!optional}/>; }
function Area({ name, label, optional = false }: { name: string; label: string; optional?: boolean }) { return <textarea className="input min-h-24" name={name} placeholder={label} required={!optional}/>; }
function Level({ value = "A2" }: { value?: string }) { return <select className="input" name="level" defaultValue={value}>{levels.map((level) => <option key={level}>{level}</option>)}</select>; }
