import Link from "next/link";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { updateContentStatus, updateWritingAssignment } from "@/modules/admin/actions";
import { writingPublishReadiness } from "@/modules/admin/content-schemas";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";

const levels=["PRE_A1","A1","A2","B1","B2","C1","C2"];
const types=["SENTENCES","PARAGRAPH","EMAIL","HIGH_SCHOOL_ESSAY","JOURNAL","IMAGE_DESCRIPTION","OPINION","WORKPLACE"];
export default async function WritingEditorPage({params}:{params:Promise<{id:string}>}){
  await requireSystemAdmin();const english=(await cookies()).get("ui_locale")?.value==="en";const {id}=await params;const assignment=await db.writingAssignment.findUnique({where:{id},include:{_count:{select:{submissions:true}}}});if(!assignment)notFound();const missing=writingPublishReadiness(assignment);
  const t=english?{back:"Back to content",editor:"Writing assignment editor",submissions:"learner submissions",status:"Status",update:"Update status",readiness:"Publication readiness",ready:"Ready to publish",missing:"Still required",info:"Assignment information",title:"Title",type:"Writing type",prompt:"Clear instructions for the learner",target:"Target word count",save:"Save assignment",notice:"Editing an assignment does not change or delete learners' previous submissions."}:{back:"返回内容管理",editor:"写作任务编辑器",submissions:"份学习者提交",status:"状态",update:"更新状态",readiness:"发布完整度",ready:"已经达到发布标准",missing:"仍需补齐",info:"任务信息",title:"标题",type:"写作类型",prompt:"给学习者的清晰写作要求",target:"目标字数",save:"保存写作任务",notice:"修改题目不会更改或删除学习者已经提交的历史版本。"};
  return <div className="mx-auto max-w-5xl"><Link className="text-sm font-bold text-brand" href="/admin/content">← {t.back}</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-brand">{assignment.level} · {assignment.type}</p><h1 className="mt-1 text-4xl font-black">{t.editor}</h1><p className="mt-2 text-muted">{assignment._count.submissions} {t.submissions}</p></div><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value="writing"/><input type="hidden" name="id" value={assignment.id}/><label><span className="label">{t.status}</span><select className="input" name="status" defaultValue={assignment.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><button className="button-primary">{t.update}</button></form></div><section className={missing.length?"mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-100":"mt-6 rounded-2xl border border-emerald-300 bg-emerald-50 p-5 text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"}><h2 className="font-black">{t.readiness}</h2><p className="mt-2">{missing.length?`${t.missing}: ${missing.join(english?", ":"、")}`:`✓ ${t.ready}`}</p></section><section className="card mt-6"><h2 className="text-2xl font-black">{t.info}</h2><p className="mt-2 text-sm text-muted">{t.notice}</p><form action={updateWritingAssignment} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="assignmentId" value={assignment.id}/><Field name="title" label={t.title} value={assignment.title}/><label><span className="label">{t.type}</span><select className="input" name="type" defaultValue={assignment.type}>{types.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">CEFR</span><select className="input" name="level" defaultValue={assignment.level}>{levels.map(x=><option key={x}>{x}</option>)}</select></label><label><span className="label">{t.target}</span><input className="input" type="number" name="targetWords" min="20" max="2000" defaultValue={assignment.targetWords} required/></label><label className="md:col-span-2"><span className="label">{t.prompt}</span><textarea className="input min-h-52" name="prompt" defaultValue={assignment.prompt} required/></label><button className="button-primary md:col-span-2">{t.save}</button></form></section></div>;
}
function Field({name,label,value}:{name:string;label:string;value:string}){return <label><span className="label">{label}</span><input className="input" name={name} defaultValue={value} required/></label>}
