import { auth } from "@/auth";
import { db } from "@/lib/db";
import { ProfilePicker } from "@/components/profile-picker";
import { getAccessibleProfiles } from "@/modules/learner/access";
import { completeDailyTask, generateDailyTasks, skipDailyTask } from "@/modules/tasks/actions";
import { updateStudyMode, useMakeupCredit } from "@/modules/streaks/actions";

export default async function TasksPage({ searchParams }: { searchParams: Promise<{ profile?: string }> }) {
  const session = await auth(); const query = await searchParams; const profiles = await getAccessibleProfiles(session!.user.id); const selected = profiles.find((profile) => profile.id === query.profile) ?? profiles[0]; const today = new Date(); const taskDate = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));
  const tasks = selected ? await db.dailyTask.findMany({ where: { learnerProfileId: selected.id, taskDate }, include: { completions: true }, orderBy: { createdAt: "asc" } }) : [];
  const learner = selected ? await db.learnerProfile.findUnique({ where: { id: selected.id }, include: { studyStreak: true, achievements: { include: { achievement: true }, orderBy: { earnedAt: "desc" } } } }) : null; const mode = learner?.studyStreak; const vacation = mode?.vacationUntil && mode.vacationUntil >= taskDate;
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Daily plan</p><h1 className="mt-2 text-4xl font-black">每日学习任务</h1><ProfilePicker profiles={profiles} selectedId={selected?.id} pathname="/tasks"/>{selected && <><section className="mt-6 grid gap-4 sm:grid-cols-3"><div className="metric"><span className="text-muted">连续学习</span><strong className="text-3xl">{mode?.currentDays ?? 0} 天</strong></div><div className="metric"><span className="text-muted">最长纪录</span><strong className="text-3xl">{mode?.longestDays ?? 0} 天</strong></div><div className="metric"><span className="text-muted">补签额度</span><strong className="text-3xl">{mode?.freezeCredits ?? 1}</strong></div></section><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><p className="text-muted">今日目标 {selected.dailyMinutes} 分钟 · 累计 {learner?.totalXp ?? 0} XP</p><form action={generateDailyTasks}><input type="hidden" name="profileId" value={selected.id}/><button className="button-primary" disabled={Boolean(mode?.planPaused || vacation)}>{mode?.planPaused ? "计划已暂停" : vacation ? "假期模式中" : tasks.length ? "今日计划已生成" : "生成今日计划"}</button></form></div><details className="card mt-5"><summary className="cursor-pointer font-black">学习节奏设置</summary><form action={updateStudyMode} className="mt-4 grid gap-4 md:grid-cols-2"><input type="hidden" name="profileId" value={selected.id}/><label className="flex items-center gap-2"><input type="checkbox" name="planPaused" defaultChecked={mode?.planPaused}/>暂停自动计划</label><label className="flex items-center gap-2"><input type="checkbox" name="weekendMode" defaultChecked={mode?.weekendMode}/>周末轻量模式（10 分钟）</label><label><span className="label">假期模式截止日</span><input className="input" type="date" name="vacationUntil" defaultValue={mode?.vacationUntil?.toISOString().slice(0, 10)}/></label><button className="button-primary self-end">保存学习模式</button></form>{(mode?.freezeCredits ?? 1) > 0 && <form action={useMakeupCredit} className="mt-4 border-t pt-4"><input type="hidden" name="profileId" value={selected.id}/><button className="button-ghost">使用 1 次补签额度</button></form>}</details></>}
    <div className="mt-6 space-y-4">{tasks.map((task) => <article className="card" key={task.id}><div className="flex flex-wrap items-center justify-between gap-5"><div><span className="text-xs font-bold text-brand">{task.taskType}</span><h2 className="mt-1 text-xl font-black">{task.title}</h2><p className="mt-1 text-muted">{task.description} · {task.estimatedMinutes} 分钟 · +{task.xpReward} XP</p><p className="mt-1 text-xs text-muted">{task.generationReason}</p></div>{task.status === "COMPLETED" ? <span className="rounded-full bg-green-100 px-4 py-2 font-bold text-green-800">已完成 ✓</span> : task.status === "SKIPPED" ? <span className="rounded-full bg-amber-100 px-4 py-2 font-bold text-amber-800">待补做</span> : <form action={completeDailyTask} className="flex items-end gap-2"><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="durationSeconds" value={task.estimatedMinutes * 60}/><label><span className="label">正确率（可选）</span><input className="input mt-1 w-24" type="number" name="accuracy" min="0" max="100" placeholder="%"/></label><button className="button-primary">完成</button></form>}</div>{task.status === "PENDING" && <details className="mt-4 border-t pt-3"><summary className="cursor-pointer text-sm text-muted">今天无法完成</summary><form action={skipDailyTask} className="mt-3 flex gap-2"><input type="hidden" name="taskId" value={task.id}/><input className="input mt-0" name="reason" placeholder="未完成原因" required/><button className="button-ghost whitespace-nowrap">标记待补做</button></form></details>}</article>)}</div>
    {selected && !tasks.length && <div className="card mt-6 text-center"><p>{mode?.planPaused ? "计划处于暂停状态。" : vacation ? `假期模式至 ${mode?.vacationUntil?.toLocaleDateString("zh-CN")}。` : "今天还没有计划。"}</p><p className="mt-2 text-sm text-muted">恢复计划后可按每日时长自动分配任务。</p></div>}
    {learner && learner.achievements.length > 0 && <section className="card mt-6"><h2 className="text-xl font-black">个人成就</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{learner.achievements.map((item) => <div className={item.earnedAt ? "rounded-xl bg-brand/10 p-4" : "rounded-xl bg-slate-100 p-4 opacity-70 dark:bg-slate-800"} key={item.id}><span className="text-2xl">{item.achievement.icon}</span><strong className="ml-2">{item.achievement.name}</strong><p className="mt-1 text-sm text-muted">{item.achievement.description} · {Math.min(item.progress, item.achievement.threshold)}/{item.achievement.threshold}</p></div>)}</div></section>}
  </div>;
}
