import { auth } from "@/auth";
import { db } from "@/lib/db";
import { ProfilePicker } from "@/components/profile-picker";
import { getAccessibleProfiles } from "@/modules/learner/access";
import { completeDailyTask, generateDailyTasks } from "@/modules/tasks/actions";

export default async function TasksPage({ searchParams }: { searchParams: Promise<{ profile?: string }> }) {
  const session = await auth(); const query = await searchParams; const profiles = await getAccessibleProfiles(session!.user.id); const selected = profiles.find((p) => p.id === query.profile) ?? profiles[0]; const today = new Date(); const taskDate = new Date(Date.UTC(today.getUTCFullYear(), today.getUTCMonth(), today.getUTCDate()));
  const tasks = selected ? await db.dailyTask.findMany({ where: { learnerProfileId: selected.id, taskDate }, include: { completions: true }, orderBy: { createdAt: "asc" } }) : []; const learner = selected ? await db.learnerProfile.findUnique({ where: { id: selected.id } }) : null;
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Daily plan</p><h1 className="mt-2 text-4xl font-black">每日学习任务</h1><ProfilePicker profiles={profiles} selectedId={selected?.id} pathname="/tasks"/>{selected && <div className="mt-6 flex flex-wrap items-center justify-between gap-3"><p className="text-muted">今日目标 {selected.dailyMinutes} 分钟 · 累计 {learner?.totalXp ?? 0} XP</p><form action={generateDailyTasks}><input type="hidden" name="profileId" value={selected.id}/><button className="button-primary">{tasks.length ? "今日计划已生成" : "生成今日计划"}</button></form></div>}<div className="mt-6 space-y-4">{tasks.map((task) => <article className="card flex flex-wrap items-center justify-between gap-5" key={task.id}><div><span className="text-xs font-bold text-brand">{task.taskType}</span><h2 className="mt-1 text-xl font-black">{task.title}</h2><p className="mt-1 text-muted">{task.description} · {task.estimatedMinutes} 分钟 · +{task.xpReward} XP</p></div>{task.status === "COMPLETED" ? <span className="rounded-full bg-green-100 px-4 py-2 font-bold text-green-800">已完成 ✓</span> : <form action={completeDailyTask}><input type="hidden" name="taskId" value={task.id}/><input type="hidden" name="durationSeconds" value={task.estimatedMinutes * 60}/><button className="button-primary">标记完成</button></form>}</article>)}</div>{selected && !tasks.length && <div className="card mt-6 text-center"><p>今天还没有计划。</p><p className="mt-2 text-sm text-muted">点击“生成今日计划”，系统会按学习时间自动分配任务。</p></div>}</div>;
}
