export const achievementCatalog = [
  { code:"FIRST_TASK",name:"迈出第一步",nameEn:"First Step",description:"完成第一个学习任务",descriptionEn:"Complete your first learning task",icon:"🌱",category:"CONSISTENCY",metric:"TASKS",threshold:1,rewardXp:10 },
  { code:"TEN_TASKS",name:"稳定前进",nameEn:"Steady Progress",description:"累计完成 10 个学习任务",descriptionEn:"Complete 10 learning tasks",icon:"⭐",category:"CONSISTENCY",metric:"TASKS",threshold:10,rewardXp:30 },
  { code:"TASKS_50",name:"学习达人",nameEn:"Learning Hero",description:"累计完成 50 个学习任务",descriptionEn:"Complete 50 learning tasks",icon:"🏆",category:"CONSISTENCY",metric:"TASKS",threshold:50,rewardXp:100 },
  { code:"STREAK_3",name:"三日启航",nameEn:"Three-day Start",description:"连续学习 3 天",descriptionEn:"Study for 3 consecutive days",icon:"✨",category:"CONSISTENCY",metric:"STREAK",threshold:3,rewardXp:20 },
  { code:"STREAK_7",name:"一周坚持",nameEn:"Seven-day Streak",description:"连续学习 7 天",descriptionEn:"Study for 7 consecutive days",icon:"🔥",category:"CONSISTENCY",metric:"STREAK",threshold:7,rewardXp:50 },
  { code:"STREAK_30",name:"月度坚持者",nameEn:"Monthly Regular",description:"连续学习 30 天",descriptionEn:"Study for 30 consecutive days",icon:"🗓️",category:"CONSISTENCY",metric:"STREAK",threshold:30,rewardXp:200 },
  { code:"MINUTES_60",name:"专注一小时",nameEn:"Focused Hour",description:"累计有效学习 60 分钟",descriptionEn:"Study for 60 effective minutes",icon:"⏱️",category:"TIME",metric:"MINUTES",threshold:60,rewardXp:30 },
  { code:"MINUTES_600",name:"十小时里程碑",nameEn:"Ten-hour Milestone",description:"累计有效学习 10 小时",descriptionEn:"Study for 10 effective hours",icon:"⌛",category:"TIME",metric:"MINUTES",threshold:600,rewardXp:120 },
  { code:"XP_500",name:"成长 500",nameEn:"500 XP",description:"累计获得 500 XP",descriptionEn:"Earn 500 XP",icon:"🏅",category:"GROWTH",metric:"XP",threshold:500,rewardXp:50 },
  { code:"XP_2000",name:"英语探索家",nameEn:"English Explorer",description:"累计获得 2000 XP",descriptionEn:"Earn 2,000 XP",icon:"🧭",category:"GROWTH",metric:"XP",threshold:2000,rewardXp:150 },
  { code:"WORDS_50",name:"单词收藏家",nameEn:"Word Collector",description:"掌握 50 个单词",descriptionEn:"Master 50 words",icon:"🔤",category:"VOCABULARY",metric:"VOCABULARY",threshold:50,rewardXp:60 },
  { code:"WORDS_200",name:"词汇建筑师",nameEn:"Vocabulary Builder",description:"掌握 200 个单词",descriptionEn:"Master 200 words",icon:"🧱",category:"VOCABULARY",metric:"VOCABULARY",threshold:200,rewardXp:150 },
  { code:"READING_5",name:"阅读起步",nameEn:"Reading Starter",description:"完成 5 篇分级阅读",descriptionEn:"Complete 5 graded readings",icon:"📖",category:"READING",metric:"READING",threshold:5,rewardXp:40 },
  { code:"READING_20",name:"阅读探险家",nameEn:"Reading Adventurer",description:"完成 20 篇分级阅读",descriptionEn:"Complete 20 graded readings",icon:"📚",category:"READING",metric:"READING",threshold:20,rewardXp:120 },
  { code:"SPEAKING_10",name:"勇敢开口",nameEn:"Brave Speaker",description:"累计开口练习 10 分钟",descriptionEn:"Practice speaking for 10 minutes",icon:"🎙️",category:"SPEAKING",metric:"SPEAKING_MINUTES",threshold:10,rewardXp:40 },
  { code:"SPEAKING_60",name:"自信表达者",nameEn:"Confident Speaker",description:"累计开口练习 60 分钟",descriptionEn:"Practice speaking for 60 minutes",icon:"🗣️",category:"SPEAKING",metric:"SPEAKING_MINUTES",threshold:60,rewardXp:120 },
  { code:"SCENARIO_3",name:"生活新手",nameEn:"Life Skills Starter",description:"完成 3 个美国生活场景",descriptionEn:"Complete 3 US-life scenarios",icon:"🗽",category:"SCENARIO",metric:"SCENARIOS",threshold:3,rewardXp:50 },
  { code:"SCENARIO_10",name:"美国生活通",nameEn:"US Life Navigator",description:"完成 10 个美国生活场景",descriptionEn:"Complete 10 US-life scenarios",icon:"🏙️",category:"SCENARIO",metric:"SCENARIOS",threshold:10,rewardXp:150 },
  { code:"MODULES_5",name:"全面发展",nameEn:"All-round Learner",description:"体验 5 种不同学习模块",descriptionEn:"Practice in 5 different modules",icon:"🌈",category:"EXPLORATION",metric:"MODULES",threshold:5,rewardXp:60 },
  { code:"HIGH_SCORE_10",name:"精准学习者",nameEn:"Accuracy Ace",description:"完成 10 次正确率不低于 80% 的练习",descriptionEn:"Complete 10 activities at 80% accuracy or higher",icon:"🎯",category:"MASTERY",metric:"HIGH_SCORE",threshold:10,rewardXp:100 },
] as const;
