import { CefrLevel, PrismaClient, QuestionType, RoleScope } from "@prisma/client";
import { uniqueScenarioVocabulary } from "../modules/scenario/vocabulary";
import { achievementCatalog } from "../modules/achievements/catalog";

const db = new PrismaClient();
const permissions = [
  ["system.manage", "system", "manage"], ["family.manage", "family", "manage"],
  ["family.read", "family", "read"], ["profile.manage", "profile", "manage"],
  ["profile.read.own", "profile", "read-own"], ["report.read.family", "report", "read-family"]
] as const;
const roleMap = {
  SYSTEM_ADMIN: permissions.map(([code]) => code),
  FAMILY_OWNER: ["family.manage", "family.read", "profile.manage", "report.read.family"],
  PARENT: ["family.read", "profile.manage", "report.read.family"],
  LEARNER: ["family.read", "profile.read.own"],
  CHILD: ["profile.read.own"]
};

async function main() {
  for (const [code, resource, action] of permissions) {
    await db.permission.upsert({ where: { code }, update: {}, create: { code, resource, action } });
  }
  for (const [code, permissionCodes] of Object.entries(roleMap)) {
    const role = await db.role.upsert({
      where: { code }, update: {},
      create: { code, name: code.replaceAll("_", " "), scope: code === "SYSTEM_ADMIN" ? RoleScope.SYSTEM : RoleScope.FAMILY }
    });
    const rows = await db.permission.findMany({ where: { code: { in: permissionCodes } } });
    for (const permission of rows) await db.rolePermission.upsert({
      where: { roleId_permissionId: { roleId: role.id, permissionId: permission.id } }, update: {},
      create: { roleId: role.id, permissionId: permission.id }
    });
  }

  const words = [
    { word: "grocery", phonetic: "/ˈɡroʊsəri/", partOfSpeech: "noun", definitionEn: "food and household items sold in a store", definitionZh: "食品杂货", level: CefrLevel.A1, topic: "Daily life", sentence: "We need to buy some groceries after work.", translation: "我们下班后需要买些食品杂货。" },
    { word: "appointment", phonetic: "/əˈpɔɪntmənt/", partOfSpeech: "noun", definitionEn: "an arranged time to meet someone", definitionZh: "预约；约会", level: CefrLevel.A2, topic: "Daily life", sentence: "I have a doctor's appointment at three.", translation: "我三点预约了医生。" },
    { word: "improve", phonetic: "/ɪmˈpruːv/", partOfSpeech: "verb", definitionEn: "to become or make something better", definitionZh: "改善；提高", level: CefrLevel.A2, topic: "Learning", sentence: "Reading every day can improve your English.", translation: "每天阅读可以提高你的英语。" },
    { word: "confident", phonetic: "/ˈkɑːnfɪdənt/", partOfSpeech: "adjective", definitionEn: "feeling sure about your abilities", definitionZh: "自信的", level: CefrLevel.B1, topic: "Growth", sentence: "She feels confident speaking in meetings.", translation: "她在会议上发言时感到自信。" },
    { word: "market", phonetic: "/ˈmɑːrkɪt/", partOfSpeech: "noun", definitionEn: "a place where people buy and sell goods", definitionZh: "市场", level: CefrLevel.A2, topic: "US life", sentence: "We buy fresh fruit at the market.", translation: "我们在市场买新鲜水果。" },
    { word: "local", phonetic: "/ˈloʊkəl/", partOfSpeech: "adjective", definitionEn: "connected with a particular nearby area", definitionZh: "当地的", level: CefrLevel.A2, topic: "US life", sentence: "Local farmers sell fresh vegetables.", translation: "当地农户出售新鲜蔬菜。" },
    { word: "cost", phonetic: "/kɔːst/", partOfSpeech: "verb", definitionEn: "to have a particular price", definitionZh: "价钱为；花费", level: CefrLevel.A2, topic: "Shopping", sentence: "How much do the strawberries cost?", translation: "这些草莓多少钱？" }
  ];
  for (const item of words) {
    const vocabulary = await db.vocabulary.upsert({
      where: { word_partOfSpeech: { word: item.word, partOfSpeech: item.partOfSpeech } },
      update: { phonetic: item.phonetic, definitionEn: item.definitionEn, level: item.level, topic: item.topic },
      create: { word: item.word, phonetic: item.phonetic, partOfSpeech: item.partOfSpeech, definitionEn: item.definitionEn, level: item.level, topic: item.topic }
    });
    await db.vocabularyMeaning.upsert({ where: { vocabularyId_locale_senseOrder: { vocabularyId: vocabulary.id, locale: "zh-CN", senseOrder: 1 } }, update: { definition: item.definitionZh }, create: { vocabularyId: vocabulary.id, locale: "zh-CN", definition: item.definitionZh } });
    const example = await db.vocabularyExample.findFirst({ where: { vocabularyId: vocabulary.id, sentence: item.sentence } });
    if (!example) await db.vocabularyExample.create({ data: { vocabularyId: vocabulary.id, sentence: item.sentence, translation: item.translation, collocations: [], difficulty: item.level } });
  }

  const articleSeed = {
    title: "A Saturday at the Farmers' Market", level: CefrLevel.A2, audience: "青少年与成人", topic: "US life",
    body: "On Saturday morning, Mia visits the farmers' market with her father. The market is busy but friendly. Local farmers sell fresh apples, tomatoes, bread, and honey. Mia asks a farmer how much the strawberries cost. He says they are four dollars a box. Mia buys one box and thanks him. Before they leave, Mia and her father listen to a musician near the entrance. They plan to return next weekend.",
    translation: "星期六早上，米娅和爸爸去了农贸市场。市场很繁忙，但气氛友好。本地农户售卖新鲜的苹果、西红柿、面包和蜂蜜。米娅询问一位农户草莓多少钱。他说每盒四美元。米娅买了一盒并向他道谢。离开前，米娅和爸爸听了入口附近一位音乐家的演奏。他们计划下周末再来。",
    summary: "Mia and her father visit a farmers' market, buy strawberries, and enjoy local music.", oralRetellingPrompt: "Retell Mia's visit in three English sentences.", writingExtensionPrompt: "What would you buy at a farmers' market, and why?",
    questions: [
      { order: 1, type: QuestionType.MULTIPLE_CHOICE, prompt: "When does Mia visit the market?", options: ["Saturday morning", "Sunday evening", "Monday afternoon"], answerKey: "Saturday morning", explanation: "The first sentence says Saturday morning." },
      { order: 2, type: QuestionType.MULTIPLE_CHOICE, prompt: "How much are the strawberries?", options: ["Two dollars", "Four dollars", "Five dollars"], answerKey: "Four dollars", explanation: "The farmer says they are four dollars a box." },
      { order: 3, type: QuestionType.TRUE_FALSE, prompt: "Mia buys two boxes of strawberries.", options: ["True", "False"], answerKey: "False", explanation: "Mia buys one box." },
      { order: 4, type: QuestionType.VOCABULARY, prompt: "Which word means ‘当地的’ in the article?", options: ["local", "busy", "fresh"], answerKey: "local", explanation: "Local means connected with the nearby area." },
      { order: 5, type: QuestionType.SHORT_ANSWER, prompt: "Summarize the article in one English sentence.", answerKey: "Mia visits the farmers' market with her father.", explanation: "Mention Mia, her father, and the farmers' market." },
      { order: 6, type: QuestionType.SHORT_ANSWER, prompt: "Oral retelling: type the key sentence you practiced saying aloud.", answerKey: "Mia visits the farmers' market.", explanation: "Retell the main event in your own words." },
      { order: 7, type: QuestionType.SHORT_ANSWER, prompt: "Writing extension: What would you buy at a farmers' market and why?", answerKey: "I would buy fresh fruit.", explanation: "Write a complete sentence with a reason." }
    ]
  };
  let article = await db.readingArticle.findFirst({ where: { title: articleSeed.title, level: articleSeed.level } });
  if (!article) article = await db.readingArticle.create({ data: { title: articleSeed.title, body: articleSeed.body, translation: articleSeed.translation, summary: articleSeed.summary, oralRetellingPrompt: articleSeed.oralRetellingPrompt, writingExtensionPrompt: articleSeed.writingExtensionPrompt, level: articleSeed.level, audience: articleSeed.audience, wordCount: articleSeed.body.split(/\s+/).length, topic: articleSeed.topic, targetVocabulary: ["market", "local", "cost"], targetGrammar: ["simple present"] } }); else await db.readingArticle.update({ where: { id: article.id }, data: { summary: articleSeed.summary, oralRetellingPrompt: articleSeed.oralRetellingPrompt, writingExtensionPrompt: articleSeed.writingExtensionPrompt } });
  for (const question of articleSeed.questions) await db.readingQuestion.upsert({ where: { articleId_order: { articleId: article.id, order: question.order } }, update: question, create: { articleId: article.id, ...question } });

  const grammarDetails = { commonErrors: ["Missing -s after he, she, or it.", "Using am/is/are before an ordinary verb."], useCases: ["Daily routines", "Habits", "Facts and schedules"], contrastExamples: [{ correct: "She works on Monday.", incorrect: "She work on Monday.", note: "Third-person singular needs -s." }] };
  const grammar = await db.grammarTopic.upsert({ where: { slug: "simple-present" }, update: grammarDetails, create: { slug: "simple-present", title: "Simple Present 一般现在时", ruleEn: "Use the simple present for habits, routines, and facts. Add -s or -es after the verb when the subject is he, she, or it.", ruleZh: "一般现在时用于习惯、日常活动和客观事实。主语是 he、she 或 it 时，动词通常加 -s 或 -es。", level: CefrLevel.A1, ...grammarDetails } });
  if (!await db.grammarExample.findFirst({ where: { topicId: grammar.id } })) await db.grammarExample.createMany({ data: [{ topicId: grammar.id, sentence: "She walks to school every day.", translation: "她每天步行上学。" }, { topicId: grammar.id, sentence: "He walk to school every day.", translation: "错误：第三人称单数缺少 s。", isError: true, explanation: "Use walks after he." }] });
  const grammarQuestions = [{ order: 1, type: QuestionType.MULTIPLE_CHOICE, prompt: "My father ___ coffee every morning.", options: ["drink", "drinks", "drinking"], answerKey: "drinks", explanation: "Father is third-person singular." }, { order: 2, type: QuestionType.FILL_BLANK, prompt: "They ___ near the library. (live)", answerKey: "live", explanation: "Use the base verb after they." }, { order: 3, type: QuestionType.ERROR_CORRECTION, prompt: "Correct: She walk to school every day.", answerKey: "She walks to school every day.", explanation: "Add -s after she." }, { order: 4, type: QuestionType.REORDER, prompt: "Reorder: every / cooks / he / evening", answerKey: "He cooks every evening.", explanation: "Subject + verb + time expression." }, { order: 5, type: QuestionType.TRANSLATION, prompt: "Translate: 我每天学习英语。", answerKey: "I study English every day.", explanation: "Use simple present for a routine." }, { order: 6, type: QuestionType.SENTENCE_CREATION, prompt: "Write a sentence about one weekly habit.", answerKey: "I exercise every week.", explanation: "Answers can vary; compare subject-verb agreement." }];
  for (const question of grammarQuestions) await db.grammarExercise.upsert({ where: { topicId_order: { topicId: grammar.id, order: question.order } }, update: question, create: { topicId: grammar.id, ...question } });

  let listening = await db.listeningExercise.findFirst({ where: { title: "Ordering at a Coffee Shop", level: CefrLevel.A2 } });
  if (!listening) listening = await db.listeningExercise.create({ data: { title: "Ordering at a Coffee Shop", level: CefrLevel.A2, topic: "US life", transcript: "Good morning. Could I have a medium coffee with milk, please? Sure. Would you like anything to eat? Yes, one blueberry muffin. That's six dollars and fifty cents.", translation: "早上好。请给我一杯加牛奶的中杯咖啡。好的。您需要吃点什么吗？需要，一个蓝莓松饼。一共六美元五十美分。" } });
  const listeningQuestions = [{ order: 1, prompt: "What size coffee does the customer order?", options: ["Small", "Medium", "Large"], answerKey: "Medium", explanation: "The customer asks for a medium coffee." }, { order: 2, prompt: "What food does the customer buy?", options: ["A sandwich", "A muffin", "A cookie"], answerKey: "A muffin", explanation: "The customer orders a blueberry muffin." }];
  for (const question of listeningQuestions) await db.listeningQuestion.upsert({ where: { exerciseId_order: { exerciseId: listening.id, order: question.order } }, update: question, create: { exerciseId: listening.id, ...question } });

  const writingSeeds = [{ title: "Introduce Your Daily Routine", type: "PARAGRAPH", prompt: "Write a short paragraph about your weekday routine.", level: CefrLevel.A2, targetWords: 80 }, { title: "A Helpful Work Email", type: "EMAIL", prompt: "Write a polite email asking a coworker for information.", level: CefrLevel.B1, targetWords: 120 }, { title: "My Week in a Journal", type: "JOURNAL", prompt: "Write a journal entry about one challenge and one success this week.", level: CefrLevel.A2, targetWords: 100 }, { title: "Describe a Busy Street", type: "IMAGE_DESCRIPTION", prompt: "Imagine a busy city street and describe people, places, and actions.", level: CefrLevel.B1, targetWords: 130 }, { title: "Should Students Have Homework?", type: "HIGH_SCHOOL_ESSAY", prompt: "State your opinion and support it with two reasons and an example.", level: CefrLevel.B2, targetWords: 250 }, { title: "A Better Community", type: "OPINION", prompt: "Explain one change that would improve your community.", level: CefrLevel.B1, targetWords: 150 }, { title: "Report a Workplace Problem", type: "WORKPLACE", prompt: "Write a clear message reporting a workplace problem and suggesting a solution.", level: CefrLevel.B1, targetWords: 140 }, { title: "Five Useful Sentences", type: "SENTENCES", prompt: "Write five natural sentences you could use during an appointment.", level: CefrLevel.A1, targetWords: 50 }];
  for (const item of writingSeeds) if (!await db.writingAssignment.findFirst({ where: { title: item.title, level: item.level } })) await db.writingAssignment.create({ data: item });

  const coffeeLessonData = { intro: "完成一次真实的美国咖啡店点单：选择杯型和奶类、控制温度与甜度、追加食品、理解小费界面、核对订单，并处理做错饮品的情况。", level: CefrLevel.A2, cultureTips: ["店员询问名字通常是为了标记订单，不是正式介绍。", "Would you like room for cream? 是询问是否要给奶油留空间。", "刷卡屏幕常会显示小费选项；是否给以及给多少由顾客自行决定。"], misunderstandings: ["A regular coffee 有时表示滴滤咖啡，但不同地区含义可能不同。", "For here or to go? 是询问堂食还是带走。"], naturalExpressions: ["Could I get a medium latte?", "Can I have that with oat milk?", "Could you make it not too hot?", "That's all, thank you."], sourceType: "ORIGINAL" as const, sourceNote: "HomeLingua 原创家庭学习内容" };
  const scenario = await db.scenarioLesson.upsert({ where: { category_title_version: { category: "餐厅与咖啡店", title: "在咖啡店自然点单", version: 1 } }, update: coffeeLessonData, create: { category: "餐厅与咖啡店", title: "在咖啡店自然点单", ...coffeeLessonData } });
  const dialogueRows = [
    { sequence: 1, speaker: "Barista", roleName: "咖啡师", textEn: "Hi! What can I get started for you?", textZh: "你好！想喝点什么？", cameraCue: "咖啡师微笑迎接顾客" },
    { sequence: 2, speaker: "Customer", roleName: "顾客", textEn: "Could I get a medium latte with oat milk, please?", textZh: "请给我一杯用燕麦奶做的中杯拿铁。", cameraCue: "顾客查看菜单后点单" },
    { sequence: 3, speaker: "Barista", roleName: "咖啡师", textEn: "Absolutely. Would you like that hot or iced?", textZh: "当然，您想要热的还是冰的？", cameraCue: "确认饮品温度" },
    { sequence: 4, speaker: "Customer", roleName: "顾客", textEn: "Hot, please, but not too hot. Could you make it about 140 degrees?", textZh: "热的，但不要太烫，可以做成大约140华氏度吗？", cameraCue: "提出具体定制要求" },
    { sequence: 5, speaker: "Barista", roleName: "咖啡师", textEn: "Sure. Would you like an extra shot or any flavored syrup?", textZh: "可以，需要额外浓缩咖啡或风味糖浆吗？", cameraCue: "询问附加选项" },
    { sequence: 6, speaker: "Customer", roleName: "顾客", textEn: "No extra shot. Could I get just one pump of vanilla?", textZh: "不要额外浓缩，请加一泵香草糖浆。", cameraCue: "控制甜度" },
    { sequence: 7, speaker: "Barista", roleName: "咖啡师", textEn: "Of course. Is that for here or to go?", textZh: "好的。堂食还是带走？", cameraCue: "确认堂食或外带" },
    { sequence: 8, speaker: "Customer", roleName: "顾客", textEn: "To go, please. And could I add a warmed blueberry muffin?", textZh: "外带。另外可以加一个加热的蓝莓松饼吗？", cameraCue: "追加食品" },
    { sequence: 9, speaker: "Barista", roleName: "咖啡师", textEn: "Yes. The total is eight dollars and seventy-five cents. May I have a name for the order?", textZh: "可以。一共8.75美元。请问订单写什么名字？", cameraCue: "确认价格和取餐姓名" },
    { sequence: 10, speaker: "Customer", roleName: "顾客", textEn: "Chen. Can I pay by card?", textZh: "陈。可以刷卡吗？", cameraCue: "说明姓名和付款方式" },
    { sequence: 11, speaker: "Barista", roleName: "咖啡师", textEn: "Yes. You can tap or insert your card. The screen will ask about a tip.", textZh: "可以，感应或插卡都行。屏幕会询问小费。", cameraCue: "说明刷卡与小费界面" },
    { sequence: 12, speaker: "Customer", roleName: "顾客", textEn: "Great, thank you. Where should I wait for the order?", textZh: "好的，谢谢。我应该在哪里等餐？", cameraCue: "确认取餐位置" },
    { sequence: 13, speaker: "Barista", roleName: "咖啡师", textEn: "Right by the pickup counter. We'll call your name when it's ready.", textZh: "在取餐台旁边，做好后会叫您的名字。", cameraCue: "完成订单并指引取餐" },
    { sequence: 14, speaker: "Customer", roleName: "顾客", textEn: "Excuse me, I ordered oat milk, but this tastes like regular milk.", textZh: "不好意思，我点的是燕麦奶，但这杯喝起来像普通牛奶。", cameraCue: "发现饮品可能做错后礼貌说明" },
    { sequence: 15, speaker: "Barista", roleName: "咖啡师", textEn: "I'm sorry about that. Let me check the label and remake it for you right away.", textZh: "非常抱歉，我检查一下标签并马上为您重做。", cameraCue: "店员核对并提出补救方案" },
    { sequence: 16, speaker: "Customer", roleName: "顾客", textEn: "Thank you. Could you also make sure it is still one pump of vanilla and about 140 degrees?", textZh: "谢谢，也请确认仍然是一泵香草、约140华氏度。", cameraCue: "重做前再次核对所有定制要求" },
    { sequence: 17, speaker: "Barista", roleName: "咖啡师", textEn: "Yes: medium hot latte, oat milk, one pump of vanilla, 140 degrees. The remake is free.", textZh: "好的：中杯热拿铁、燕麦奶、一泵香草、140华氏度。重做不收费。", cameraCue: "逐项复述订单并确认不额外收费" },
    { sequence: 18, speaker: "Customer", roleName: "顾客", textEn: "Perfect. I appreciate you fixing it so quickly.", textZh: "太好了，谢谢您这么快帮我解决。", cameraCue: "礼貌结束异常处理" }
  ];
  for (const row of dialogueRows) await db.scenarioDialogue.upsert({ where: { lessonId_sequence: { lessonId: scenario.id, sequence: row.sequence } }, update: row, create: { lessonId: scenario.id, ...row } });
  const scenarioQuestions = [{ order: 1, prompt: "Which milk does the customer request?", options: ["Whole milk", "Oat milk", "Soy milk"], answerKey: "Oat milk", explanation: "The customer asks for oat milk." }, { order: 2, prompt: "Is the order for here or to go?", options: ["For here", "To go"], answerKey: "To go", explanation: "The customer says 'To go, please.'" }, { order:3,prompt:"How does the customer customize the sweetness?",options:["No syrup","One pump of vanilla","Three pumps of caramel"],answerKey:"One pump of vanilla",explanation:"The customer asks for just one pump of vanilla." }, {order:4,prompt:"Where should the customer wait?",options:["Outside","At the table","By the pickup counter"],answerKey:"By the pickup counter",explanation:"The barista directs the customer to the pickup counter."},{order:5,prompt:"What problem does the customer notice?",options:["The drink may contain regular milk.","The muffin is too large.","The store is closed."],answerKey:"The drink may contain regular milk.",explanation:"The customer says the drink tastes like regular milk instead of oat milk."},{order:6,prompt:"What does the barista do before remaking the drink?",options:["Checks the label and repeats every customization.","Charges for a second drink.","Asks the customer to leave."],answerKey:"Checks the label and repeats every customization.",explanation:"The barista verifies oat milk, vanilla, temperature, and confirms the remake is free."}];
  for (const row of scenarioQuestions) await db.scenarioExercise.upsert({ where: { lessonId_order: { lessonId: scenario.id, order: row.order } }, update: row, create: { lessonId: scenario.id, type: QuestionType.MULTIPLE_CHOICE, ...row } });
  const coffeeTimeline = [{at:0,title:"查看菜单",note:"判断排队和点单方式"},{at:100,title:"点饮品",note:"说清杯型、饮品和奶类"},{at:220,title:"定制要求",note:"温度、甜度和额外浓缩"},{at:350,title:"追加食品",note:"询问加热和库存"},{at:460,title:"付款",note:"理解刷卡、小费界面和总价"},{at:570,title:"等待取餐",note:"确认取餐台和叫号方式"},{at:660,title:"处理做错订单",note:"礼貌指出问题、核对标签并要求重做"},{at:780,title:"完整角色挑战",note:"隐藏顾客或咖啡师台词完成整段对话"}];
  await db.videoLesson.upsert({ where: { scenarioLessonId: scenario.id }, update: { title:"咖啡店完整点单任务课",durationSeconds:840,timeline:coffeeTimeline }, create: { scenarioLessonId: scenario.id, title: "咖啡店完整点单任务课", durationSeconds:840, timeline:coffeeTimeline } });
  for (const item of [{order:1,word:"order",meaningZh:"点单；订单",example:"I'd like to place an order."},{order:2,word:"medium",meaningZh:"中杯；中等的",example:"Could I get a medium coffee?"},{order:3,word:"to go",meaningZh:"外带",example:"That's to go, please."}]) await db.scenarioVocabulary.upsert({where:{lessonId_word:{lessonId:scenario.id,word:item.word}},update:item,create:{lessonId:scenario.id,...item}});
  const lifeScenarios = [
    { category:"超市购物", need:"I'm looking for gluten-free bread, but I can't find the right aisle.", needZh:"我在找无麸质面包，但找不到对应货架。", question:"Do you need a specific brand, and do you have any food allergies?", questionZh:"您需要特定品牌吗？有没有食物过敏？", detail:"Any brand is fine, but it must be completely nut-free.", detailZh:"品牌不限，但必须完全不含坚果。", solution:"Aisle twelve has a nut-free section. I'll show you the allergen label.", solutionZh:"12号通道有无坚果专区，我帮您看过敏原标签。", issue:"If the shelf price is different from the checkout price, who should I ask?", issueZh:"如果货架价格和结账价格不同，我该找谁？", resolution:"Take a photo of the shelf tag and ask customer service to verify it.", resolutionZh:"拍下货架价签，请客服核对。", words:[["aisle","货架通道"],["allergen","过敏原"],["shelf tag","货架价签"]] },
    { category:"医院看病", need:"I have had a sore throat and a fever since yesterday.", needZh:"我从昨天开始喉咙痛并发烧。", question:"What was your highest temperature, and are you having trouble breathing?", questionZh:"最高体温多少？呼吸是否困难？", detail:"It reached 102 degrees, but I can breathe normally.", detailZh:"最高102华氏度，但呼吸正常。", solution:"The nurse will check your vital signs, and the doctor may order a strep test.", solutionZh:"护士会检查生命体征，医生可能安排链球菌检测。", issue:"Does my insurance cover the test, and where will the prescription be sent?", issueZh:"保险是否覆盖检测？处方会发到哪里？", resolution:"We will verify coverage and send the prescription to your preferred pharmacy.", resolutionZh:"我们会核实保险，并把处方发到您指定的药房。", words:[["symptom","症状"],["coverage","保险范围"],["prescription","处方"]] },
    { category:"学校沟通", need:"I'd like to understand why my child is falling behind in reading.", needZh:"我想了解孩子为什么在阅读方面落后。", question:"Have you noticed the same difficulty with homework at home?", questionZh:"您在家做作业时也注意到同样困难吗？", detail:"Yes. New vocabulary takes a long time, and the instructions are sometimes confusing.", detailZh:"是的，新词学习很慢，有时也看不懂题目要求。", solution:"We can provide small-group support and send home a weekly practice list.", solutionZh:"学校可以提供小组辅导，并每周发送家庭练习清单。", issue:"How will we measure progress, and when should we meet again?", issueZh:"如何衡量进步？下次什么时候再沟通？", resolution:"We'll review reading scores in six weeks and schedule a follow-up conference.", resolutionZh:"六周后复查阅读成绩并安排后续会议。", words:[["fall behind","落后"],["support","辅导支持"],["follow-up","后续跟进"]] },
    { category:"银行开户", need:"I'd like to open a checking account with no monthly fee.", needZh:"我想开一个没有月费的支票账户。", question:"Do you receive direct deposit, and would you like a debit card?", questionZh:"您有工资直接存款吗？需要借记卡吗？", detail:"Yes to both. I also need online bill pay.", detailZh:"都有需要，我还需要网上账单支付。", solution:"This account waives the fee with direct deposit and includes online banking.", solutionZh:"这个账户有直接存款可免月费，也包含网上银行。", issue:"Is there a minimum balance or an overdraft charge?", issueZh:"有最低余额或透支费用吗？", resolution:"There is no minimum balance; let me explain the optional overdraft settings.", resolutionZh:"没有最低余额，我来说明可选的透支设置。", words:[["direct deposit","直接存款"],["minimum balance","最低余额"],["overdraft","透支"]] },
    { category:"DMV 办事", need:"I need to transfer my out-of-state driver's license.", needZh:"我需要把外州驾照转到本州。", question:"Do you have proof of identity, residency, and your Social Security number?", questionZh:"您有身份证明、居住证明和社会安全号码吗？", detail:"I brought my passport, lease, utility bill, and current license.", detailZh:"我带了护照、租约、水电账单和现有驾照。", solution:"Great. You'll take a vision test and then have your photo taken.", solutionZh:"很好，您需要视力测试，然后拍照。", issue:"Will I receive the permanent license today?", issueZh:"今天能拿到正式驾照吗？", resolution:"You'll receive a temporary paper license; the card arrives by mail.", resolutionZh:"您会先拿临时纸质驾照，卡片随后邮寄。", words:[["residency","居住证明"],["vision test","视力测试"],["temporary license","临时驾照"]] },
    { category:"加油站", need:"The pump accepted my card, but it isn't dispensing any gas.", needZh:"加油机刷卡成功了，但没有出油。", question:"Did you select the fuel grade and lift the correct nozzle?", questionZh:"您选择油号并拿起正确油枪了吗？", detail:"Yes, I selected regular, but the screen says to see the cashier.", detailZh:"是的，我选了普通汽油，但屏幕提示去找收银员。", solution:"I'll reset pump six and place a temporary authorization on your card.", solutionZh:"我会重置6号泵，银行卡会有一笔临时预授权。", issue:"Why is the pending charge much higher than the gas I bought?", issueZh:"为什么待处理金额比实际油费高很多？", resolution:"It's only a hold and normally disappears after the final charge posts.", resolutionZh:"那只是预授权，实际扣款入账后通常会消失。", words:[["fuel grade","汽油标号"],["pump","加油机"],["authorization hold","预授权冻结"]] },
    { category:"汽车维修", need:"The check-engine light is on, and the car shakes when I accelerate.", needZh:"发动机故障灯亮了，加速时车会抖。", question:"Is the light steady or flashing, and when did the shaking begin?", questionZh:"灯是常亮还是闪烁？抖动什么时候开始？", detail:"It is flashing, and the problem started this morning.", detailZh:"灯在闪，问题今天早上开始。", solution:"Please don't drive it further. We'll run a diagnostic scan first.", solutionZh:"请不要继续驾驶，我们先做故障诊断。", issue:"Can you call me with an estimate before doing any repairs?", issueZh:"维修前能先打电话告诉我报价吗？", resolution:"Absolutely. We won't begin work until you approve the written estimate.", resolutionZh:"当然，您批准书面报价后我们才开始维修。", words:[["diagnostic","故障诊断"],["estimate","报价"],["approve","批准"]] },
    { category:"房屋租赁", need:"I'm interested in the two-bedroom apartment listed online.", needZh:"我对网上发布的两居室公寓感兴趣。", question:"When would you like to move in, and do you have any pets?", questionZh:"您什么时候入住？有宠物吗？", detail:"Next month. I have one small cat.", detailZh:"下个月，我有一只小猫。", solution:"The unit is available, and cats are allowed with a pet deposit.", solutionZh:"房子可以入住，交宠物押金即可养猫。", issue:"Which utilities are included, and how long is the lease?", issueZh:"包含哪些水电费用？租期多长？", resolution:"Water is included; electricity is separate, and the lease is twelve months.", resolutionZh:"包水费，电费另付，租期12个月。", words:[["security deposit","押金"],["utilities","水电杂费"],["lease term","租期"]] },
    { category:"工作面试", need:"Thank you for meeting with me. I'm excited about the warehouse coordinator role.", needZh:"谢谢您面试我，我对仓库协调员职位很感兴趣。", question:"Can you describe a time you solved an inventory problem?", questionZh:"请讲一次您解决库存问题的经历。", detail:"I found a receiving error, checked the records, and corrected the count before shipment.", detailZh:"我发现收货错误，核对记录并在发货前修正了数量。", solution:"That experience fits the role. We also use scanners and inventory software daily.", solutionZh:"这段经验很符合岗位，我们每天也使用扫描器和库存软件。", issue:"What does training look like during the first month?", issueZh:"第一个月的培训是怎样的？", resolution:"You'll shadow a lead for two weeks and then manage a small section independently.", resolutionZh:"前两周跟随组长学习，之后独立管理一个小区域。", words:[["inventory","库存"],["receiving","收货"],["shadow","跟岗学习"]] },
    { category:"仓库工作", need:"The shipment count doesn't match the packing list.", needZh:"货物数量与装箱单不符。", question:"Which item number is short, and have you checked the receiving area?", questionZh:"哪个货号短缺？检查过收货区吗？", detail:"Item 482 is short by six units, and I checked both pallets.", detailZh:"482号货少了6件，两托盘都检查过了。", solution:"Put the shipment on hold and document the discrepancy with photos.", solutionZh:"先暂停这批货，并拍照记录差异。", issue:"Should I adjust the inventory before the supervisor reviews it?", issueZh:"主管审核前要修改库存吗？", resolution:"No. Leave the count unchanged until the supervisor approves the adjustment.", resolutionZh:"不要，等主管批准后再调整。", words:[["packing list","装箱单"],["discrepancy","差异"],["put on hold","暂停处理"]] },
    { category:"会计和 QuickBooks", need:"This customer payment isn't matching the open invoice in QuickBooks.", needZh:"这笔客户付款在QuickBooks里无法匹配未结发票。", question:"Does the payment amount include multiple invoices or a bank fee?", questionZh:"付款是否包含多张发票或银行手续费？", detail:"It covers two invoices, but the customer deducted a small credit.", detailZh:"它支付两张发票，但客户扣除了一笔小额贷项。", solution:"Apply the payment to both invoices and confirm the credit memo first.", solutionZh:"先确认贷项通知单，再把付款分配到两张发票。", issue:"What should I do with the remaining difference?", issueZh:"剩余差额该怎么处理？", resolution:"Leave it unapplied until the account manager confirms the deduction.", resolutionZh:"先保持未分配，等客户经理确认扣款。", words:[["open invoice","未结发票"],["credit memo","贷项通知单"],["unapplied payment","未分配付款"]] },
    { category:"电话沟通", need:"I'm calling about an order that was supposed to arrive yesterday.", needZh:"我来电询问本应昨天送达的订单。", question:"May I have the order number and the name on the account?", questionZh:"请提供订单号和账户姓名。", detail:"The order number is 51824, under Chen Yong.", detailZh:"订单号51824，账户名陈勇。", solution:"The carrier reported a delay, and the new delivery date is tomorrow.", solutionZh:"承运商报告延误，新的送达日期是明天。", issue:"Could you send that update to me by email?", issueZh:"能把更新通过邮件发给我吗？", resolution:"Yes. I'll email the tracking link and a case number before we hang up.", resolutionZh:"可以，挂电话前我会发送追踪链接和案件编号。", words:[["order number","订单号"],["carrier","承运商"],["case number","案件编号"]] },
    { category:"预约", need:"I'd like to schedule a dental cleaning sometime next week.", needZh:"我想预约下周洗牙。", question:"Are mornings or afternoons better, and are you a new patient?", questionZh:"上午还是下午方便？您是新患者吗？", detail:"Afternoons are better, and this will be my first visit.", detailZh:"下午方便，这是我第一次来。", solution:"We have Tuesday at 2:30 or Thursday at 4:00.", solutionZh:"周二2:30或周四4点有空。", issue:"What should I bring, and is there a cancellation fee?", issueZh:"需要带什么？取消预约收费吗？", resolution:"Bring your ID and insurance card; please cancel at least 24 hours ahead.", resolutionZh:"带身份证和保险卡；至少提前24小时取消。", words:[["availability","可预约时间"],["new patient","新患者"],["cancellation fee","取消费用"]] },
    { category:"投诉", need:"I'm calling because the internet has disconnected repeatedly for three days.", needZh:"网络连续三天反复断线，我想投诉。", question:"How often does it disconnect, and have you restarted the modem?", questionZh:"多久断一次？重启过调制解调器吗？", detail:"About every hour. I restarted it twice and checked the cables.", detailZh:"大约每小时一次，我重启了两次并检查了线缆。", solution:"I'll run a line test and schedule a technician if the signal is unstable.", solutionZh:"我会测试线路，信号不稳定就安排技术员。", issue:"Can the service charge be adjusted for the outage?", issueZh:"停网期间的服务费能调整吗？", resolution:"I'll document the outage and submit a credit request after the repair.", resolutionZh:"我会记录故障，维修后提交费用减免申请。", words:[["outage","服务中断"],["technician","技术员"],["service credit","费用减免"]] },
    { category:"退货", need:"I'd like to return this blender because it stopped working after two uses.", needZh:"搅拌机用了两次就坏了，我想退货。", question:"Do you have the receipt, and would you prefer a refund or exchange?", questionZh:"有收据吗？想退款还是换货？", detail:"I have the digital receipt, and I'd prefer a refund.", detailZh:"我有电子收据，希望退款。", solution:"The purchase is within thirty days, so it qualifies for a refund.", solutionZh:"购买未超过30天，符合退款条件。", issue:"Will the refund go back to my original card?", issueZh:"退款会退回原银行卡吗？", resolution:"Yes. It may take three to five business days to appear.", resolutionZh:"是的，通常3到5个工作日到账。", words:[["digital receipt","电子收据"],["refund","退款"],["original payment method","原付款方式"]] },
    { category:"快递", need:"My tracking says delivered, but the package isn't at my door.", needZh:"物流显示已送达，但门口没有包裹。", question:"Have you checked the mailroom, side entrance, and nearby units?", questionZh:"检查过邮件室、侧门和邻居门口吗？", detail:"Yes, and the delivery photo shows a different building.", detailZh:"检查过，送货照片显示的是另一栋楼。", solution:"I'll open a missing-package investigation with the local station.", solutionZh:"我会联系本地站点开启丢件调查。", issue:"When should I contact the seller for a replacement?", issueZh:"什么时候联系卖家补发？", resolution:"Wait until tomorrow evening; if it isn't recovered, use this case number.", resolutionZh:"等到明晚，如未找回，可用这个案件编号联系。", words:[["tracking","物流追踪"],["delivery photo","送货照片"],["investigation","调查"]] },
    { category:"Uber", need:"I think I left my phone in the car after my last ride.", needZh:"上次乘车后，我可能把手机落在车里了。", question:"Can you confirm the trip time and describe the phone case?", questionZh:"请确认行程时间并描述手机壳。", detail:"The ride ended at 8:15, and the case is dark blue.", detailZh:"行程8:15结束，手机壳是深蓝色。", solution:"Use the app to contact the driver through a masked phone number.", solutionZh:"通过App的匿名号码联系司机。", issue:"What if I can't log in because the app is on my missing phone?", issueZh:"App在丢失的手机上，无法登录怎么办？", resolution:"Sign in on the website and choose 'I lost an item' for that trip.", resolutionZh:"在网站登录，对该行程选择“物品遗失”。", words:[["last ride","上次行程"],["masked number","匿名号码"],["lost item","遗失物品"]] },
    { category:"机场", need:"My connecting flight leaves soon, but my first flight arrived late.", needZh:"第一程航班晚点，转机航班很快就起飞。", question:"What is your destination and the connecting flight number?", questionZh:"目的地和转机航班号是什么？", detail:"I'm going to Chicago on flight 247, departing in forty minutes.", detailZh:"去芝加哥，247航班，40分钟后起飞。", solution:"The gate is B18. Take the train and follow the connection signs.", solutionZh:"登机口B18，乘小火车并跟随转机标志。", issue:"What happens to my checked bag if I miss the connection?", issueZh:"如果没赶上转机，托运行李怎么办？", resolution:"The airline will reroute the bag when it rebooks your flight.", resolutionZh:"航空公司改签时会重新安排您的行李。", words:[["connecting flight","转机航班"],["departure gate","登机口"],["rebook","改签"]] },
    { category:"酒店", need:"I have a reservation, but the room is much noisier than expected.", needZh:"我有预订，但房间比预期吵很多。", question:"May I have your room number, and what noise are you hearing?", questionZh:"请问房间号？是什么噪音？", detail:"Room 614. The elevator and ice machine are right outside.", detailZh:"614房，电梯和制冰机就在门外。", solution:"I can move you to a quieter room on the eighth floor.", solutionZh:"可以为您换到8楼安静的房间。", issue:"Will there be an extra charge, and can someone help with the luggage?", issueZh:"会额外收费吗？有人能帮搬行李吗？", resolution:"There is no charge, and a bell attendant will bring new keys.", resolutionZh:"不收费，行李员会送新钥匙并协助搬行李。", words:[["reservation","预订"],["room change","换房"],["extra charge","额外费用"]] },
    { category:"家长与老师沟通", need:"I'd like to talk about my child's participation and homework habits.", needZh:"我想了解孩子的课堂参与和作业习惯。", question:"What changes have you noticed at home recently?", questionZh:"您最近在家观察到什么变化？", detail:"Homework takes longer, and my child is afraid to ask questions.", detailZh:"作业时间变长，而且孩子不敢提问。", solution:"I'll check in privately and give written steps for larger assignments.", solutionZh:"我会私下沟通，并为大作业提供书面步骤。", issue:"How can we support the same plan at home?", issueZh:"在家如何配合相同计划？", resolution:"Use the weekly checklist and email me if a task takes over thirty minutes.", resolutionZh:"使用每周清单，单项超过30分钟就给老师邮件。", words:[["participation","课堂参与"],["checklist","清单"],["check in","主动关心"]] },
    { category:"Costco 购物", need:"I bought this item last month, and now it is on sale.", needZh:"这个商品上月买的，现在降价了。", question:"Do you have the membership card and the original receipt?", questionZh:"有会员卡和原始收据吗？", detail:"I have the card, and the purchase appears in the app.", detailZh:"有会员卡，App里能看到购买记录。", solution:"We can check whether it qualifies for a price adjustment.", solutionZh:"我们可以查看是否符合补差价条件。", issue:"Do I need to bring the item back for the adjustment?", issueZh:"补差价需要把商品带回来吗？", resolution:"Usually no; the purchase record and membership card are enough.", resolutionZh:"通常不需要，购买记录和会员卡即可。", words:[["membership card","会员卡"],["price adjustment","补差价"],["purchase history","购买记录"]] },
    { category:"Walmart 购物", need:"The app says this medicine is in stock, but the shelf is empty.", needZh:"App显示药品有货，但货架是空的。", question:"Can you show me the item page and the store location selected in the app?", questionZh:"请出示商品页面和App中选择的门店。", detail:"This is the correct store, and the app shows four available.", detailZh:"门店正确，App显示还有4件。", solution:"I'll check the top stock and the back room using the item number.", solutionZh:"我用货号检查货架上层和后仓。", issue:"If it is unavailable, can another store hold it for me?", issueZh:"如果没货，其他门店能为我保留吗？", resolution:"We can check nearby inventory, but you'll need to place a pickup order.", resolutionZh:"可查附近库存，但需要下自提订单。", words:[["in stock","有现货"],["item number","货号"],["pickup order","自提订单"]] },
    { category:"Home Depot 购物", need:"I need the right anchors to mount a heavy shelf on drywall.", needZh:"我要在石膏板墙上安装重架子，需要合适的锚栓。", question:"How much does the shelf weigh, and can you attach any screws to studs?", questionZh:"架子多重？螺丝能否固定在墙柱上？", detail:"It is about sixty pounds, and only one bracket lines up with a stud.", detailZh:"约60磅，只有一个支架能对准墙柱。", solution:"Use a stud screw there and rated toggle bolts for the other brackets.", solutionZh:"墙柱处用螺丝，其他支架用额定承重的蝴蝶栓。", issue:"What drill-bit size do these toggle bolts require?", issueZh:"这些蝴蝶栓需要多大钻头？", resolution:"The package calls for a half-inch bit; verify the wall is clear first.", resolutionZh:"包装要求半英寸钻头，钻孔前先确认墙内无管线。", words:[["drywall","石膏板"],["wall stud","墙柱"],["toggle bolt","蝴蝶栓"]] }
  ];
  for (const item of lifeScenarios) {
    const lessonData = { intro: `完成一个真实的美国${item.category}任务：清楚说明需求、回答追问、处理意外情况、确认费用或下一步，并自然结束对话。`, level: CefrLevel.A2, cultureTips: ["先用一句话说明主要需求，再提供号码、日期、症状或尺寸等关键信息。", "涉及费用、保险、退换、合同或预约时，应复述并确认下一步。", "没有听懂时可以请对方放慢或重复，不必假装听懂。"], misunderstandings: ["只说 I need help 信息不足，工作人员通常必须继续追问。", "Okay 不一定表示所有细节都确认了；离开前应确认金额、时间、地址或凭证。"], naturalExpressions: ["Could you walk me through the next step?", "Let me make sure I understood correctly.", "Is there anything else I need to bring or do?", "Could I get that in writing, please?"], sourceType: "ORIGINAL" as const, sourceNote: "HomeLingua 原创美国生活任务型课程" };
    const lesson = await db.scenarioLesson.upsert({ where: { category_title_version: { category: item.category, title: `${item.category}实用英语`, version: 1 } }, update: lessonData, create: { category: item.category, title: `${item.category}实用英语`, ...lessonData } });
    const lines = [
      { speaker:"Staff", roleName:"工作人员", textEn:"Good morning. How can I help you today?", textZh:"早上好，今天有什么可以帮您？", cameraCue:"进入场景并开始沟通" },
      { speaker:"Customer", roleName:"顾客", textEn:item.need, textZh:item.needZh, cameraCue:"用一句完整的话说明主要需求" },
      { speaker:"Staff", roleName:"工作人员", textEn:"I can help with that. I'll ask a few questions so we can choose the right process.", textZh:"我可以帮您。我先问几个问题，以便选择正确的处理流程。", cameraCue:"说明为什么需要进一步询问" },
      { speaker:"Staff", roleName:"工作人员", textEn:item.question, textZh:item.questionZh, cameraCue:"工作人员追问关键信息" },
      { speaker:"Customer", roleName:"顾客", textEn:item.detail, textZh:item.detailZh, cameraCue:"提供具体号码、时间或限制条件" },
      { speaker:"Staff", roleName:"工作人员", textEn:item.solution, textZh:item.solutionZh, cameraCue:"工作人员提出处理方案" },
      { speaker:"Customer", roleName:"顾客", textEn:item.issue, textZh:item.issueZh, cameraCue:"提出真实场景中的额外问题" },
      { speaker:"Staff", roleName:"工作人员", textEn:item.resolution, textZh:item.resolutionZh, cameraCue:"解决费用、时间或异常情况" },
      { speaker:"Customer", roleName:"顾客", textEn:"What should I do if that option doesn't solve the problem?", textZh:"如果这个办法没有解决问题，我接下来该怎么办？", cameraCue:"追问备用方案" },
      { speaker:"Staff", roleName:"工作人员", textEn:`Keep the written confirmation and contact us again. Ask for your ${item.category} case to be reviewed by a supervisor or specialist.`, textZh:`请保留书面确认并再次联系我们，要求主管或专业人员复核这项${item.category}事务。`, cameraCue:"了解升级处理途径" },
      { speaker:"Customer", roleName:"顾客", textEn:"Is there a deadline, fee, or reference number I should know about?", textZh:"是否有截止日期、费用或需要记录的编号？", cameraCue:"主动确认时间、费用和凭证" },
      { speaker:"Staff", roleName:"工作人员", textEn:"I'll include those details in the written confirmation so you don't have to rely on memory.", textZh:"我会把这些细节写进确认信息，您不必只靠记忆。", cameraCue:"把重要细节落实为书面记录" },
      { speaker:"Customer", roleName:"顾客", textEn:"Could you write that down or send me a confirmation?", textZh:"可以写下来或给我发送确认信息吗？", cameraCue:"索取书面凭证" },
      { speaker:"Staff", roleName:"工作人员", textEn:"Of course. Please review the details and let us know if anything is incorrect.", textZh:"当然，请核对信息，如有错误请告诉我们。", cameraCue:"工作人员提供确认信息" },
      { speaker:"Customer", roleName:"顾客", textEn:`I see the main request and next step here. Could you also confirm the details about ${item.words[1][0]}?`, textZh:`我看到主要需求和下一步了，也请确认一下关于“${item.words[1][1]}”的细节。`, cameraCue:"使用本场景核心词汇核对细节" },
      { speaker:"Staff", roleName:"工作人员", textEn:"Yes, both details are correct. I have also added a note about the backup option we discussed.", textZh:"是的，两项信息都正确，我也加上了我们讨论的备用方案。", cameraCue:"完成最后核对" },
      { speaker:"Customer", roleName:"顾客", textEn:"Everything looks correct. Is there anything else I need to do today?", textZh:"信息都正确，今天还需要做什么吗？", cameraCue:"离开前确认是否还有步骤" },
      { speaker:"Staff", roleName:"工作人员", textEn:"No, you're all set. Keep the confirmation for your records.", textZh:"没有了，已经办好。请保存确认信息。", cameraCue:"明确表示流程完成" },
      { speaker:"Customer", roleName:"顾客", textEn:"Great. Thank you for explaining everything clearly.", textZh:"太好了，谢谢您解释得这么清楚。", cameraCue:"自然礼貌地结束对话" }
    ];
    for (const [index, line] of lines.entries()) { const row = { ...line, sequence:index+1 }; await db.scenarioDialogue.upsert({ where: { lessonId_sequence: { lessonId: lesson.id, sequence:row.sequence } }, update:row, create:{ lessonId:lesson.id, ...row } }); }
    const questions = [
      { prompt:"What is the customer's main request?", options:[item.need,"They are only saying hello.","They want to leave immediately."], answerKey:item.need, explanation:"The customer states the main need near the beginning." },
      { prompt:"Why does the staff member ask a follow-up question?", options:["To collect the details needed to solve the problem.","To avoid helping the customer.","To change the subject."], answerKey:"To collect the details needed to solve the problem.", explanation:"Specific details help the staff choose the right process." },
      { prompt:"Which sentence is best for confirming the next step?", options:["Let me make sure I understand the next step.","Whatever.","You are wrong."], answerKey:"Let me make sure I understand the next step.", explanation:"This phrase politely checks understanding." },
      { prompt:"What solution does the staff member offer?", options:[item.solution,"The staff refuses to help.","The customer must start over without guidance."], answerKey:item.solution, explanation:"The staff explains a concrete process for this situation." },
      { prompt:"How is the additional problem resolved?", options:[item.resolution,"The problem is ignored.","The customer is told to guess."], answerKey:item.resolution, explanation:"The dialogue gives a specific response to the complication." },
      { prompt:"What should the customer keep after the conversation?", options:["The written confirmation.","Nothing at all.","Only the staff member's first name."], answerKey:"The written confirmation.", explanation:"Written confirmation helps if there is a later problem." },
      { prompt:"What should the customer do if the first option fails?", options:["Use the confirmation and request a supervisor or specialist review.","Give up immediately.","Repeat the same action without contacting anyone."], answerKey:"Use the confirmation and request a supervisor or specialist review.", explanation:"The expanded dialogue teaches an escalation path, not only the ideal outcome." }
    ];
    for (const [index, question] of questions.entries()) { const row={...question,order:index+1,type:QuestionType.MULTIPLE_CHOICE}; await db.scenarioExercise.upsert({where:{lessonId_order:{lessonId:lesson.id,order:row.order}},update:row,create:{lessonId:lesson.id,...row}}); }
    const timeline = [{at:0,title:"任务预演",note:"理解办理目标、角色和需要准备的信息"},{at:90,title:"说明真实需求",note:"一句话说清要办理的事情"},{at:190,title:"回答追问",note:"提供号码、时间、症状、尺寸或限制条件"},{at:310,title:"理解解决方案",note:"听取流程并确认具体处理办法"},{at:430,title:"处理意外情况",note:"询问费用、保险、延误、失败后的备用方案"},{at:560,title:"书面确认",note:"核对核心词汇、截止日期、费用和凭证"},{at:660,title:"角色挑战",note:"隐藏自己的台词完成整段对话"},{at:750,title:"理解测验",note:"用六道题检查主旨、细节和应变能力"}];
    await db.videoLesson.upsert({ where: { scenarioLessonId: lesson.id }, update: { title:`${item.category}完整任务课`,durationSeconds:840,timeline }, create: { scenarioLessonId: lesson.id, title:`${item.category}完整任务课`,durationSeconds:840,timeline } });
    await db.scenarioVocabulary.deleteMany({where:{lessonId:lesson.id}});
    const scenarioWords = uniqueScenarioVocabulary(item.words, [["follow-up","后续追问"],["confirmation","确认信息"],["next step","下一步"]]);
    await db.scenarioVocabulary.createMany({data:scenarioWords.map(([word,meaningZh],index)=>({lessonId:lesson.id,word,meaningZh,example:index<3?[item.need,item.question,item.solution][index]:`Could you confirm the ${word}?`,order:index+1}))});
  }
  for (const achievement of achievementCatalog) await db.achievement.upsert({ where: { code: achievement.code }, update: achievement, create: achievement });
}

main().finally(() => db.$disconnect());
