import { auth } from "@/auth";
import { db } from "@/lib/db";
import { ProfilePicker } from "@/components/profile-picker";
import { SpeakingRecorder } from "@/components/speaking-recorder";
import { getAccessibleProfiles } from "@/modules/learner/access";

const prompts = ["Could I have a glass of water, please?", "I would like to make an appointment for tomorrow.", "Excuse me, could you tell me where the nearest grocery store is?"];

export default async function SpeakingPage({ searchParams }: { searchParams: Promise<{ profile?: string; prompt?: string }> }) {
  const session = await auth(); const query = await searchParams; const profiles = await getAccessibleProfiles(session!.user.id); const selected = profiles.find((profile) => profile.id === query.profile) ?? profiles[0]; const prompt = prompts.includes(query.prompt ?? "") ? query.prompt! : prompts[0];
  const history = selected ? await db.speakingSession.findMany({ where: { learnerProfileId: selected.id }, include: { attempts: { include: { pronunciation: true, audioFile: true } } }, orderBy: { startedAt: "desc" }, take: 20 }) : [];
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Speaking</p><h1 className="mt-2 text-4xl font-black">口语跟读与录音</h1><ProfilePicker profiles={profiles} selectedId={selected?.id} pathname="/learn/speaking"/>{selected && <><section className="card mt-7"><p className="label">本次练习</p><h2 className="mt-2 text-2xl font-black">{prompt}</h2><div className="mt-5"><SpeakingRecorder profileId={selected.id} prompt={prompt}/></div></section><section className="mt-7"><h2 className="text-2xl font-black">评分历史与趋势</h2><div className="mt-4 space-y-3">{history.map((item) => { const attempt = item.attempts[0]; return <article className="card" key={item.id}><div className="flex flex-wrap justify-between gap-2"><p className="font-bold">{item.prompt}</p><span className="text-sm text-muted">第 {attempt?.retryNo ?? 1} 次 · {item.startedAt.toLocaleString("zh-CN")}</span></div><p className="mt-2 text-muted">你说：{attempt?.transcript}</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5"><Score label="准确" value={attempt?.accuracyScore}/><Score label="流利" value={attempt?.fluencyScore}/><Score label="语法" value={attempt?.grammarScore}/><Score label="完整" value={attempt?.completenessScore}/><Score label="自然" value={attempt?.naturalnessScore}/></div><p className="mt-3 text-sm">语速：{attempt?.speechRateWpm ? `${Math.round(attempt.speechRateWpm)} 词/分钟` : "未记录"} · 停顿提示：{attempt?.pauseCount ?? 0}</p>{attempt?.audioFileId && <audio className="mt-3 w-full" controls src={`/api/uploads/${attempt.audioFileId}`}/>}<p className="mt-3 text-sm text-brand">{attempt?.feedback}</p>{attempt?.pronunciation.length ? <ul className="mt-3 list-disc pl-5 text-sm text-amber-800">{attempt.pronunciation.map((feedback) => <li key={feedback.id}>{feedback.word}：{feedback.suggestion}</li>)}</ul> : null}</article>; })}</div></section></>}</div>;
}

function Score({ label, value }: { label: string; value: number | null | undefined }) { return <div className="rounded-xl bg-slate-100 p-3 text-center dark:bg-slate-800"><span className="text-xs text-muted">{label}</span><p className="font-black">{Math.round((value ?? 0) * 100)}%</p></div>; }
