import { cookies } from "next/headers";
import { auth } from "@/auth"; import { db } from "@/lib/db"; import { ProfilePicker } from "@/components/profile-picker"; import { SpeechPlayer } from "@/components/speech-player"; import { getAccessibleProfiles } from "@/modules/learner/access"; import { placementQuestions } from "@/modules/placement/questions"; import { submitPlacementTest } from "@/modules/placement/actions";

const sectionEn: Record<string, string> = { "词汇": "Vocabulary", "句子理解": "Sentence comprehension", "听力": "Listening", "阅读": "Reading", "语法": "Grammar", "写作": "Writing", "口语（可选）": "Speaking (optional)" };

export default async function PlacementPage({ searchParams }: { searchParams: Promise<{ profile?: string; completed?: string }> }) {
  const session = await auth(); const english = (await cookies()).get("ui_locale")?.value === "en"; const query = await searchParams; const profiles = await getAccessibleProfiles(session!.user.id); const selected = profiles.find((profile) => profile.id === query.profile) ?? profiles[0]; const history = selected ? await db.placementTest.findMany({ where: { learnerProfileId: selected.id, status: "COMPLETED" }, include: { answers: true }, orderBy: { version: "desc" } }) : [];
  const t = english ? { title: "English placement test", help: "Covers vocabulary, comprehension, listening, reading, grammar, and writing. Retakes preserve all previous results.", complete: "Test completed", level: "Assessed level", strengths: "Strengths", building: "Developing", focus: "Focus areas", balanced: "Balanced improvement", plan: "Your first-week plan was generated automatically.", speakingPlaceholder: "Optional: type your speech-recognition result", submit: "Submit test and generate first-week plan", history: "Test history", attempt: "Attempt", weak: "weak areas" } : { title: "英语水平测试", help: "覆盖词汇、理解、听力、阅读、语法和写作；可以重新测试，历史结果会保留。", complete: "测试已完成", level: "评估等级", strengths: "优势", building: "正在建立", focus: "重点", balanced: "综合提升", plan: "第一周计划已自动生成。", speakingPlaceholder: "此项可留空，或输入语音识别结果", submit: "提交测试并生成第一周计划", history: "历史测试", attempt: "第", weak: "薄弱" };
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Placement test</p><h1 className="mt-2 text-4xl font-black">{t.title}</h1><p className="mt-2 text-muted">{t.help}</p><ProfilePicker profiles={profiles} selectedId={selected?.id} pathname="/placement"/>{query.completed && history[0] && <section className="card mt-6 border-brand"><p className="font-bold text-brand">{t.complete}</p><h2 className="mt-2 text-3xl font-black">{t.level}: {history[0].assessedLevel?.replace("_", "-")}</h2><p className="mt-3">{t.strengths}: {history[0].strengths.join(english ? ", " : "、") || t.building}</p><p className="mt-2">{t.focus}: {history[0].weakAreas.join(english ? ", " : "、") || t.balanced}</p><p className="mt-2 text-muted">{t.plan}</p></section>}{selected && <form action={submitPlacementTest} className="mt-6 space-y-5"><input type="hidden" name="profileId" value={selected.id}/>{placementQuestions.map((question, index) => <fieldset className="card" key={question.id}><legend className="text-lg font-black">{index + 1}. {english ? sectionEn[question.section] ?? question.section : question.section}</legend><p className="mt-2">{question.prompt}</p>{question.section === "听力" && question.passage && <div className="mt-4"><SpeechPlayer text={question.passage}/></div>}{question.section === "阅读" && question.passage && <blockquote className="mt-4 rounded-xl bg-slate-100 p-4 leading-7 dark:bg-slate-800">{question.passage}</blockquote>}{question.options ? <div className="mt-4 space-y-2">{question.options.map((option) => <label className="block rounded-xl border p-3" key={option}><input className="mr-2" type="radio" name={question.id} value={option} required/>{option}</label>)}</div> : <textarea className="input min-h-32" name={question.id} required={question.id === "writing-1"} placeholder={question.id === "speaking-1" ? t.speakingPlaceholder : "Write in English…"}/>}</fieldset>)}<button className="button-primary w-full">{t.submit}</button></form>} {history.length > 0 && <details className="card mt-6"><summary className="cursor-pointer text-xl font-black">{t.history} ({history.length})</summary><div className="mt-4 space-y-3">{history.map((test) => <div className="rounded-xl bg-slate-100 p-4 dark:bg-slate-800" key={test.id}><strong>{t.attempt} {test.version} · {test.assessedLevel?.replace("_", "-")}</strong><p className="text-sm text-muted">{test.submittedAt?.toLocaleString(english ? "en-US" : "zh-CN")} · {t.strengths} {test.strengths.join(english ? ", " : "、") || "—"} · {t.weak} {test.weakAreas.join(english ? ", " : "、") || "—"}</p></div>)}</div></details>}</div>;
}
