"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";

type License = { id: string; name: string; type: string; publicationAllowed: boolean };
type Source = { id: string; name: string; baseUrl: string; enabled: boolean; approved: boolean; license: License };

async function jsonPost(url: string, body: unknown) {
  const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "操作失败"); return data;
}

export function ContentImportCenter({ licenses, sources }: { licenses: License[]; sources: Source[] }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function run(action: () => Promise<unknown>) { setBusy(true); setMessage(""); try { await action(); setMessage("操作成功。"); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "操作失败"); } finally { setBusy(false); } }
  return <div className="space-y-6">
    <section className="card"><h2 className="text-xl font-black">1. 新增许可证</h2><p className="mt-1 text-sm text-muted">UNKNOWN 和 RESTRICTED 不能设置为允许发布。</p><form className="mt-4 grid gap-3 md:grid-cols-2" action={(form)=>run(()=>jsonPost("/api/admin/content/licenses",{type:form.get("type"),name:form.get("name"),url:String(form.get("url")||"")||null,allowsModification:form.get("allowsModification")==="on",allowsCommercialUse:form.get("allowsCommercialUse")==="on",requiresAttribution:form.get("requiresAttribution")==="on",requiresShareAlike:form.get("requiresShareAlike")==="on",publicationAllowed:form.get("publicationAllowed")==="on"}))}><select className="input" name="type">{["PUBLIC_DOMAIN","CC0","CC_BY","CC_BY_SA","GOVERNMENT_OPEN_DATA","CUSTOM_ALLOWED","UNKNOWN","RESTRICTED"].map(x=><option key={x}>{x}</option>)}</select><input className="input" name="name" placeholder="许可证名称" required/><input className="input md:col-span-2" type="url" name="url" placeholder="许可证说明网址"/><div className="flex flex-wrap gap-4 md:col-span-2">{[["allowsModification","允许修改"],["allowsCommercialUse","允许商业使用"],["requiresAttribution","要求署名"],["requiresShareAlike","相同方式共享"],["publicationAllowed","允许发布"]].map(([name,label])=><label className="flex gap-2" key={name}><input type="checkbox" name={name}/>{label}</label>)}</div><button className="button-primary" disabled={busy}>保存许可证</button></form></section>
    <section className="card"><h2 className="text-xl font-black">2. 新增导入源</h2><p className="mt-1 text-sm text-muted">只有明确批准且启用的数据源才能执行导入。域名使用纯主机名，路径每行一个。</p><form className="mt-4 grid gap-3 md:grid-cols-2" action={(form)=>run(()=>jsonPost("/api/admin/content/sources",{name:form.get("name"),baseUrl:form.get("baseUrl"),defaultAuthor:String(form.get("defaultAuthor")||"")||undefined,allowedDomains:String(form.get("allowedDomains")||"").split(/[\s,]+/).filter(Boolean),allowedPathPrefixes:String(form.get("paths")||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean),licenseId:form.get("licenseId"),rateLimitPerMinute:Number(form.get("rate")),approved:form.get("approved")==="on",enabled:form.get("enabled")==="on"}))}><input className="input" name="name" placeholder="来源名称" required/><input className="input" type="url" name="baseUrl" placeholder="https://example.org" required/><input className="input" name="defaultAuthor" placeholder="默认作者 / 机构"/><input className="input" name="allowedDomains" placeholder="example.org" required/><textarea className="input" name="paths" placeholder="/open-data/&#10;/education/"/><select className="input" name="licenseId" required><option value="">选择许可证</option>{licenses.map(x=><option value={x.id} key={x.id}>{x.name} · {x.type}</option>)}</select><input className="input" type="number" name="rate" min="1" max="120" defaultValue="10"/><label className="flex gap-2"><input type="checkbox" name="approved"/>管理员批准</label><label className="flex gap-2"><input type="checkbox" name="enabled"/>启用</label><button className="button-primary" disabled={busy}>保存导入源</button></form></section>
    <section className="card"><h2 className="text-xl font-black">3. 创建导入批次</h2><form className="mt-4 grid gap-3" action={(form)=>run(()=>jsonPost("/api/admin/content/import",{importSourceId:form.get("sourceId"),urls:String(form.get("urls")||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean),priority:100,maxRetries:1}))}><select className="input" name="sourceId" required><option value="">选择已批准来源</option>{sources.filter(x=>x.approved&&x.enabled).map(x=><option value={x.id} key={x.id}>{x.name} · {x.license.type}</option>)}</select><textarea className="input min-h-40" name="urls" placeholder="每行一个 HTTPS 资源网址" required/><button className="button-primary" disabled={busy}>安全检查并加入队列</button></form></section>
    {message&&<p className="card text-sm font-bold">{message}</p>}
    <section className="card"><h2 className="text-xl font-black">已配置来源</h2><div className="mt-3 space-y-2">{sources.map(x=><div className="rounded-xl border p-3" key={x.id}><strong>{x.name}</strong><p className="text-sm text-muted">{x.baseUrl} · {x.license.type} · {x.approved?"已批准":"未批准"} · {x.enabled?"已启用":"未启用"}</p></div>)}{!sources.length&&<p className="text-muted">暂无导入源。</p>}</div></section>
  </div>;
}
