"use client";
import { useEffect, useRef, useState } from "react";
type ResultEvent={results:ArrayLike<{0:{transcript:string}}>};
type Recognition={lang:string;continuous:boolean;interimResults:boolean;start():void;stop():void;onresult:((event:ResultEvent)=>void)|null;onend:(()=>void)|null;onerror:(()=>void)|null};
type RecognitionCtor=new()=>Recognition;
export function PlacementSpeakingInput({profileId,english=false}:{profileId:string;english?:boolean}){
  const [transcript,setTranscript]=useState("");const [recognizing,setRecognizing]=useState(false);const [recording,setRecording]=useState(false);const [audioId,setAudioId]=useState("");const [status,setStatus]=useState("");const [supported,setSupported]=useState(false);const recognition=useRef<Recognition|null>(null);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([]);
  const t=english?{start:"Start speech recognition",stop:"Stop recognition",record:"Record optional audio",stopRecord:"Stop and save recording",unsupported:"Speech recognition is unavailable; you can type your answer.",placeholder:"Introduce yourself in English (optional)",recording:"Recording…",saving:"Saving recording…",saved:"Recording saved",failed:"Could not save recording",microphone:"Microphone access failed"}:{start:"开始语音识别",stop:"停止识别",record:"录制可选口语音频",stopRecord:"停止并保存录音",unsupported:"当前浏览器不支持语音识别，也可以手动输入口语回答。",placeholder:"请用英语介绍自己（可选）",recording:"正在录音……",saving:"正在保存录音……",saved:"录音已保存",failed:"录音保存失败",microphone:"无法使用麦克风"};
  useEffect(()=>{const win=window as typeof window&{SpeechRecognition?:RecognitionCtor;webkitSpeechRecognition?:RecognitionCtor};const Ctor=win.SpeechRecognition??win.webkitSpeechRecognition;setSupported(Boolean(Ctor));if(Ctor){const instance=new Ctor();instance.lang="en-US";instance.continuous=true;instance.interimResults=false;instance.onresult=event=>setTranscript(value=>`${value} ${event.results[event.results.length-1][0].transcript}`.trim());instance.onend=()=>setRecognizing(false);instance.onerror=()=>setRecognizing(false);recognition.current=instance;}return()=>{recognition.current?.stop();if(recorder.current?.state==="recording")recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());};},[]);
  async function startRecording(){if(!navigator.mediaDevices||!("MediaRecorder" in window)){setStatus(t.microphone);return;}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});const media=new MediaRecorder(stream.current,MediaRecorder.isTypeSupported("audio/webm")?{mimeType:"audio/webm"}:undefined);chunks.current=[];media.ondataavailable=event=>{if(event.data.size)chunks.current.push(event.data);};media.onstop=async()=>{stream.current?.getTracks().forEach(track=>track.stop());setStatus(t.saving);const mime=media.mimeType.split(";",1)[0]||"audio/webm";const form=new FormData();form.set("profileId",profileId);form.set("file",new File([new Blob(chunks.current,{type:mime})],"placement-speaking.webm",{type:mime}));const response=await fetch("/api/uploads",{method:"POST",body:form});const result=await response.json();if(response.ok){setAudioId(result.id);setStatus(t.saved);}else setStatus(`${t.failed}: ${result.error??"unknown"}`);};recorder.current=media;media.start(500);setRecording(true);setStatus(t.recording);}catch{setStatus(t.microphone);}}
  function stopRecording(){if(recorder.current?.state==="recording")recorder.current.stop();setRecording(false);}
  return <div className="mt-4"><input type="hidden" name="speakingAudioFileId" value={audioId}/><div className="flex flex-wrap gap-2">{supported&&!recognizing&&<button type="button" className="button-primary" onClick={()=>{setRecognizing(true);recognition.current?.start();}}>{t.start}</button>}{recognizing&&<button type="button" className="button-primary" onClick={()=>recognition.current?.stop()}>{t.stop}</button>}{!recording?<button type="button" className="button-ghost" onClick={startRecording}>● {t.record}</button>:<button type="button" className="button-ghost" onClick={stopRecording}>■ {t.stopRecord}</button>}</div>{!supported&&<p className="mt-2 text-sm text-muted">{t.unsupported}</p>}{status&&<p className="mt-2 text-sm text-brand">{status}</p>}{audioId&&<audio className="mt-3 w-full" controls src={`/api/uploads/${audioId}`}/>}<textarea className="input min-h-28" name="speaking-1" value={transcript} onChange={event=>setTranscript(event.target.value)} placeholder={t.placeholder}/></div>;
}
