"use client";
import{useMemo,useState}from"react";
import{Gauge,Headphones,BookOpen,PenLine,MessageCircle,ChevronRight,Send}from"lucide-react";
import{SpeechPlayer}from"@/components/speech-player";
import{submitPlacementTest}from"@/modules/placement/actions";
import{chooseAdaptiveQuestion,openAnswerIsStrong}from"@/modules/placement/adaptive";
import type{PlacementQuestion}from"@/modules/placement/questions";

const sectionEn:Record<string,string>={基础词汇:"Vocabulary",句子理解:"Sentence comprehension",听力:"Listening",阅读:"Reading",语法:"Grammar",简单写作:"Writing","口语（可选）":"Speaking"};
const levelDifficulty:Record<string,number>={PRE_A1:1,A1:1,A2:1,B1:2,B2:2,C1:3,C2:3};

export function PlacementTestDeck({profileId,testId,questions,english,initialLevel}:{profileId:string;testId:string;questions:PlacementQuestion[];english:boolean;initialLevel:string|null}){
  const startingDifficulty=levelDifficulty[initialLevel??""]??2;
  const initial=useMemo(()=>[...questions].sort((a,b)=>Math.abs(a.maxScore-startingDifficulty)-Math.abs(b.maxScore-startingDifficulty))[0],[questions,startingDifficulty]);
  const[active,setActive]=useState(initial);const[remaining,setRemaining]=useState(()=>questions.filter(question=>question.id!==initial?.id));const[answers,setAnswers]=useState<Record<string,string>>({});const[value,setValue]=useState("");const[completed,setCompleted]=useState<PlacementQuestion[]>([]);
  const t=english?{progress:"Adaptive progress",difficulty:"Current difficulty",easy:"Foundation",medium:"Intermediate",hard:"Advanced",next:"Next question",finish:"Review and submit",submit:"Submit test",answered:"questions answered",required:"Please answer before continuing",writing:"Write your answer in English…",speaking:"Type what you would say in English…",adaptive:"The next question changes according to this answer."}:{progress:"自适应进度",difficulty:"当前难度",easy:"基础",medium:"中等",hard:"进阶",next:"下一题",finish:"检查并提交",submit:"提交测试",answered:"题已完成",required:"请先回答本题",writing:"请用英语完成写作……",speaking:"请输入你会说的英文……",adaptive:"下一题难度会根据本题表现自动调整。"};
  if(!active)return null;const total=questions.length;const finished=completed.length===total;
  function advance(){if(!value.trim())return;const correct=active.answerKey?value.trim().toLowerCase()===active.answerKey.toLowerCase():openAnswerIsStrong(value,active.maxScore);setAnswers(current=>({...current,[active.id]:value}));setCompleted(current=>[...current,active]);if(!remaining.length){setValue("");return}const next=chooseAdaptiveQuestion(remaining,active.maxScore,correct)!;setRemaining(items=>items.filter(item=>item.id!==next.id));setActive(next);setValue("")}
  if(finished)return <form action={submitPlacementTest} className="mt-7 rounded-[2rem] bg-gradient-to-br from-teal-950 to-cyan-800 p-8 text-center text-white"><input type="hidden" name="profileId" value={profileId}/><input type="hidden" name="testId" value={testId}/>{Object.entries(answers).map(([id,answer])=><input type="hidden" name={id} value={answer} key={id}/>) }<Send className="mx-auto" size={54}/><h2 className="mt-4 text-3xl font-black">{t.finish}</h2><p className="mt-2 text-white/70">{completed.length} {t.answered}</p><button className="mt-7 rounded-xl bg-white px-7 py-3 font-black text-teal-900">{t.submit}</button></form>;
  const Icon=active.section==="听力"?Headphones:active.section==="阅读"?BookOpen:active.section==="简单写作"?PenLine:active.section.startsWith("口语")?MessageCircle:Gauge;const difficulty=[t.easy,t.medium,t.hard][Math.max(1,active.maxScore)-1];
  return <section className="mt-7 overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-950 via-violet-900 to-cyan-800 p-6 text-white shadow-2xl md:p-10"><div className="flex items-center justify-between gap-4"><span className="font-bold">{t.progress} · {completed.length+1}/{total}</span><span className="rounded-full bg-white/15 px-3 py-1 text-sm font-bold">{t.difficulty}: {difficulty}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-300 transition-all" style={{width:`${(completed.length+1)/total*100}%`}}/></div><div className="mx-auto flex min-h-[34rem] max-w-3xl flex-col justify-center py-8"><Icon size={40}/><p className="mt-4 text-sm font-bold uppercase tracking-[.25em] text-white/60">{english?sectionEn[active.section]??active.section:active.section}</p><h2 className="mt-4 text-2xl font-black leading-relaxed md:text-4xl">{active.prompt}</h2>{active.section==="听力"&&active.passage&&<div className="mt-6 rounded-2xl bg-white p-4 text-slate-950"><SpeechPlayer text={active.passage}/></div>}{active.section==="阅读"&&active.passage&&<blockquote className="mt-6 rounded-2xl bg-white/10 p-5 text-lg leading-8">{active.passage}</blockquote>}{active.options?<div className="mt-7 grid gap-3">{active.options.map(option=><button type="button" className={`rounded-2xl border p-4 text-left font-bold transition ${value===option?"border-amber-300 bg-amber-300 text-slate-950":"border-white/20 bg-white/10 hover:bg-white/20"}`} onClick={()=>setValue(option)} key={option}>{option}</button>)}</div>:<textarea className="mt-7 min-h-40 rounded-2xl bg-white p-5 text-slate-950" value={value} onChange={event=>setValue(event.target.value)} placeholder={active.section.startsWith("口语")?t.speaking:t.writing}/>}<p className="mt-4 text-sm text-white/60">{t.adaptive}</p><button type="button" disabled={!value.trim()} className="mt-6 self-end rounded-xl bg-white px-6 py-3 font-black text-violet-900 disabled:opacity-40" onClick={advance}>{remaining.length?t.next:t.finish}<ChevronRight className="ml-2 inline" size={18}/></button>{!value.trim()&&<span className="mt-2 self-end text-xs text-white/50">{t.required}</span>}</div></section>;
}
