"use client";
import { useCallback, useEffect, useMemo, useState } from "react";

type Dialogue = { id: string; speaker: string; roleName: string; textEn: string; textZh: string | null; sequence: number; cameraCue: string | null };

export function ScenarioPlayer({ dialogues }: { dialogues: Dialogue[] }) {
  const ordered = useMemo(() => [...dialogues].sort((a, b) => a.sequence - b.sequence), [dialogues]);
  const [index, setIndex] = useState(0); const [showZh, setShowZh] = useState(true); const [autoPlay, setAutoPlay] = useState(false); const current = ordered[index];
  const speak = useCallback((item = current) => { if (!item || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(item.textEn); utterance.lang = "en-US"; utterance.rate = 0.88; utterance.onend = () => { if (autoPlay && index < ordered.length - 1) setIndex((value) => value + 1); }; window.speechSynthesis.speak(utterance); }, [autoPlay, current, index, ordered.length]);
  useEffect(() => { if (autoPlay && current) { const timer = window.setTimeout(() => speak(current), 100); return () => window.clearTimeout(timer); } }, [autoPlay, current, speak]);
  if (!current) return <p>课程尚无台词。</p>;
  return <div><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-teal-950 to-slate-900 p-7 text-white"><p className="text-sm text-teal-200">镜头：{current.cameraCue ?? "对话场景"}</p><p className="mt-8 text-sm font-bold uppercase tracking-wider">{current.roleName} · {current.speaker}</p><p className="mt-3 text-2xl font-black leading-relaxed">{current.textEn}</p>{showZh && <p className="mt-3 text-teal-100">{current.textZh}</p>}<div className="mt-8 h-2 overflow-hidden rounded-full bg-white/20"><div className="h-full bg-teal-300" style={{ width: `${(index + 1) / ordered.length * 100}%` }}/></div></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" className="button-primary" onClick={() => speak()}>▶ 播放本句</button><button type="button" className="button-ghost" disabled={index === 0} onClick={() => setIndex((value) => Math.max(0, value - 1))}>上一句</button><button type="button" className="button-ghost" disabled={index === ordered.length - 1} onClick={() => setIndex((value) => Math.min(ordered.length - 1, value + 1))}>下一句</button><button type="button" className="button-ghost" onClick={() => setShowZh((value) => !value)}>{showZh ? "隐藏中文" : "显示中文"}</button><label className="button-ghost"><input className="mr-2" type="checkbox" checked={autoPlay} onChange={(event) => setAutoPlay(event.target.checked)}/>连续播放</label></div><div className="mt-5 grid gap-2 sm:grid-cols-2">{ordered.map((item, itemIndex) => <button type="button" className={itemIndex === index ? "rounded-xl border border-brand bg-brand/10 p-3 text-left" : "rounded-xl border p-3 text-left"} onClick={() => setIndex(itemIndex)} key={item.id}><strong>{item.roleName}</strong><span className="ml-2 line-clamp-1 text-sm text-muted">{item.textEn}</span></button>)}</div></div>;
}
