"use client";
import { useEffect, useRef, useState } from "react";
import { saveSpeakingAttempt } from "@/modules/speaking/actions";

type RecognitionResult = { results: ArrayLike<{ 0: { transcript: string } }> };
type Recognition = { lang: string; interimResults: boolean; continuous: boolean; start(): void; stop(): void; onresult: ((event: RecognitionResult) => void) | null; onend: (() => void) | null; onerror: (() => void) | null };
type RecognitionCtor = new () => Recognition;

export function SpeakingRecorder({ profileId, prompt }: { profileId: string | undefined; prompt: string }) {
  const [transcript, setTranscript] = useState(""); const [recognizing, setRecognizing] = useState(false); const [recognitionSupported, setRecognitionSupported] = useState(false); const [recording, setRecording] = useState(false); const [audioFileId, setAudioFileId] = useState(""); const [uploadStatus, setUploadStatus] = useState(""); const [durationSeconds, setDurationSeconds] = useState(0); const recognition = useRef<Recognition | null>(null); const recorder = useRef<MediaRecorder | null>(null); const stream = useRef<MediaStream | null>(null); const chunks = useRef<Blob[]>([]); const started = useRef(0);
  useEffect(() => { const win = window as typeof window & { SpeechRecognition?: RecognitionCtor; webkitSpeechRecognition?: RecognitionCtor }; const Ctor = win.SpeechRecognition ?? win.webkitSpeechRecognition; setRecognitionSupported(Boolean(Ctor)); if (Ctor) { const instance = new Ctor(); instance.lang = "en-US"; instance.continuous = true; instance.interimResults = false; instance.onresult = (event) => setTranscript((value) => `${value} ${event.results[event.results.length - 1][0].transcript}`.trim()); instance.onend = () => setRecognizing(false); instance.onerror = () => setRecognizing(false); recognition.current = instance; } return () => { recognition.current?.stop(); recorder.current?.stop(); stream.current?.getTracks().forEach((track) => track.stop()); }; }, []);
  function startRecognition() { started.current ||= Date.now(); setRecognizing(true); recognition.current?.start(); }
  function stopRecognition() { recognition.current?.stop(); setRecognizing(false); if (started.current) setDurationSeconds(Math.max(1, Math.round((Date.now() - started.current) / 1000))); }
  async function startRecording() { if (!profileId || !navigator.mediaDevices || !("MediaRecorder" in window)) { setUploadStatus("当前浏览器不支持录音"); return; } try { stream.current = await navigator.mediaDevices.getUserMedia({ audio: true }); const mediaRecorder = new MediaRecorder(stream.current, MediaRecorder.isTypeSupported("audio/webm") ? { mimeType: "audio/webm" } : undefined); chunks.current = []; mediaRecorder.ondataavailable = (event) => { if (event.data.size) chunks.current.push(event.data); }; mediaRecorder.onstop = async () => { stream.current?.getTracks().forEach((track) => track.stop()); const blob = new Blob(chunks.current, { type: mediaRecorder.mimeType || "audio/webm" }); const form = new FormData(); form.set("profileId", profileId); form.set("file", new File([blob], "speaking.webm", { type: blob.type || "audio/webm" })); setUploadStatus("正在安全保存录音…"); const response = await fetch("/api/uploads", { method: "POST", body: form }); const result = await response.json(); if (response.ok) { setAudioFileId(result.id); setUploadStatus("录音已保存"); } else setUploadStatus(`录音保存失败：${result.error}`); }; recorder.current = mediaRecorder; started.current = Date.now(); mediaRecorder.start(500); setRecording(true); setUploadStatus("录音中…"); } catch { setUploadStatus("无法使用麦克风，请检查浏览器权限"); } }
  function stopRecording() { recorder.current?.stop(); setRecording(false); if (started.current) setDurationSeconds(Math.max(1, Math.round((Date.now() - started.current) / 1000))); }
  return <div><SpeechPlayerInline text={prompt}/><div className="mt-4 flex flex-wrap gap-2">{recognitionSupported && !recognizing && <button type="button" className="button-primary" onClick={startRecognition}>开始语音识别</button>}{recognizing && <button type="button" className="button-primary" onClick={stopRecognition}>停止识别</button>}{!recording ? <button type="button" className="button-ghost" onClick={startRecording}>● 保存录音</button> : <button type="button" className="button-ghost" onClick={stopRecording}>■ 停止录音</button>}<button type="button" className="button-ghost" onClick={() => setTranscript("")}>清空文字</button></div>{!recognitionSupported && <p className="mt-3 text-sm text-muted">当前浏览器不支持语音识别，可手动输入；录音能力会单独检测。</p>}{uploadStatus && <p className="mt-3 text-sm text-brand">{uploadStatus}</p>}{audioFileId && <audio className="mt-3 w-full" controls src={`/api/uploads/${audioFileId}`}/>}<form action={saveSpeakingAttempt} className="mt-4"><input type="hidden" name="profileId" value={profileId}/><input type="hidden" name="prompt" value={prompt}/><input type="hidden" name="provider" value={recognitionSupported ? "Web Speech API" : "manual"}/><input type="hidden" name="durationSeconds" value={durationSeconds}/><input type="hidden" name="audioFileId" value={audioFileId}/><textarea className="input min-h-28" name="transcript" value={transcript} onChange={(event) => setTranscript(event.target.value)} placeholder="识别结果会显示在这里，也可以手动修改" required/><button className="button-primary mt-3">保存并评分</button></form></div>;
}
function SpeechPlayerInline({ text }: { text: string }) { function play() { window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = "en-US"; utterance.rate = 0.85; window.speechSynthesis.speak(utterance); } return <button type="button" className="button-ghost" onClick={play}>▶ 听示范</button>; }
