"use client";
import { useState, useTransition } from "react";
import { reviewVocabulary } from "@/modules/vocabulary/actions";
const modes = ["EN_TO_ZH", "ZH_TO_EN", "LISTEN", "SPELL", "FILL", "UNDERSTAND", "SENTENCE", "READ"] as const;
type Mode = (typeof modes)[number];

export function VocabularyPractice({ profileId, vocabularyId, word, meaning, example, english = false }: { profileId: string; vocabularyId: string; word: string; meaning: string; example?: string; english?: boolean }) {
  const [mode, setMode] = useState<Mode>("EN_TO_ZH"); const [answer, setAnswer] = useState(""); const [result, setResult] = useState(""); const [pending, startTransition] = useTransition();
  const labels: Record<Mode, string> = english ? { EN_TO_ZH: "English → Chinese", ZH_TO_EN: "Chinese → English", LISTEN: "Listen", SPELL: "Spell", FILL: "Fill the blank", UNDERSTAND: "Understand example", SENTENCE: "Make a sentence", READ: "Read aloud" } : { EN_TO_ZH: "英译中", ZH_TO_EN: "中译英", LISTEN: "听音选词", SPELL: "拼写", FILL: "填空", UNDERSTAND: "例句理解", SENTENCE: "造句", READ: "口头朗读" };
  const ui = english ? { title: "Practice types", play: "Play pronunciation", input: "Type your answer", checking: "Saving…", readDone: "I finished reading", check: "Check answer", correct: "Correct. Saved as a successful review.", retry: "Try again. Reference" } : { title: "多类型练习", play: "播放发音", input: "输入答案", checking: "记录中…", readDone: "我已完成朗读", check: "检查答案", correct: "回答正确，已按熟练复习记录。", retry: "再试一次。参考" };
  function speak() { const utterance = new SpeechSynthesisUtterance(word); utterance.lang = "en-US"; utterance.rate = 0.8; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); }
  function expected() { if (mode === "EN_TO_ZH") return meaning; if (["ZH_TO_EN", "LISTEN", "SPELL", "FILL"].includes(mode)) return word; return ""; }
  function check() { const target = expected().toLowerCase(); const value = answer.trim().toLowerCase(); const correct = mode === "SENTENCE" ? value.includes(word.toLowerCase()) && value.split(/\s+/).length >= 4 : mode === "UNDERSTAND" ? value.length >= 4 : mode === "READ" ? true : value === target || (mode === "EN_TO_ZH" && meaning.includes(answer.trim())); setResult(correct ? ui.correct : `${ui.retry}: ${expected() || example || word}`); const data = new FormData(); data.set("profileId", profileId); data.set("vocabularyId", vocabularyId); data.set("quality", correct ? "5" : "1"); startTransition(() => reviewVocabulary(data)); }
  const prompt = mode === "EN_TO_ZH" ? (english ? `Write the Chinese meaning of ${word}` : `写出 ${word} 的中文意思`) : mode === "ZH_TO_EN" ? (english ? `Write the English word for “${meaning}”` : `写出“${meaning}”对应的英文`) : mode === "LISTEN" ? (english ? "Play the audio and type the word you hear" : "点击播放后输入听到的单词") : mode === "SPELL" ? `${english ? "Spell this word" : "拼写这个单词"}: ${word[0]}${"_".repeat(Math.max(1, word.length - 1))}` : mode === "FILL" ? (example ?? "Please use ___ in a sentence.").replace(new RegExp(word, "ig"), "___") : mode === "UNDERSTAND" ? (english ? `Explain this example in your own words: ${example ?? word}` : `用中文解释：${example ?? word}`) : mode === "SENTENCE" ? (english ? `Write a complete sentence using ${word}` : `使用 ${word} 写一个完整句子`) : (english ? `Play the pronunciation, read ${word} aloud, then confirm` : `点击发音，朗读 ${word}，然后自我确认`);
  return <details className="mt-5 border-t pt-4"><summary className="cursor-pointer font-bold text-brand">{ui.title}</summary><div className="mt-3 flex flex-wrap gap-2">{modes.map((item) => <button type="button" className={item === mode ? "button-primary" : "button-ghost"} onClick={() => { setMode(item); setAnswer(""); setResult(""); }} key={item}>{labels[item]}</button>)}</div><p className="mt-4 font-bold">{prompt}</p>{["LISTEN", "READ"].includes(mode) && <button type="button" className="button-ghost mt-3" onClick={speak}>▶ {ui.play}</button>}{mode !== "READ" && <input className="input" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder={ui.input}/>}<button type="button" className="button-primary mt-3" disabled={pending || (mode !== "READ" && !answer.trim())} onClick={check}>{pending ? ui.checking : mode === "READ" ? ui.readDone : ui.check}</button>{result && <p className="mt-3 text-sm">{result}</p>}</details>;
}
