"use client";
import { useMemo,useState,useTransition } from "react";
import { Gamepad2,Headphones,Keyboard,Link2,Trophy,Volume2,Zap } from "lucide-react";
import { submitVocabularyGame } from "@/modules/vocabulary/actions";
import type { VocabularySlide } from "./vocabulary-slide-deck";

type Mode="DAILY"|"WEEKLY";type Kind="MEANING"|"AUDIO"|"SPELLING"|"CONTEXT";
function shuffledOptions(slides:VocabularySlide[],index:number){const target=slides[index].word;const others=slides.filter((_,i)=>i!==index).map(item=>item.word).sort((a,b)=>`${a}-${index}`.localeCompare(`${b}-${index}`)).slice(0,3);return[target,...others].sort((a,b)=>`${a.length+index}-${a}`.localeCompare(`${b.length+index}-${b}`));}
export function VocabularyGame({profileId,slides,english}:{profileId:string;slides:VocabularySlide[];english:boolean}){
  const [mode,setMode]=useState<Mode>("DAILY");const [started,setStarted]=useState(false);const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Array<{vocabularyId:string;questionType:Kind;answer:string;responseMs:number}>>([]);const [value,setValue]=useState("");const [streak,setStreak]=useState(0);const [feedback,setFeedback]=useState<null|boolean>(null);const [startedAt,setStartedAt]=useState(Date.now());const [result,setResult]=useState<null|{correct:number;total:number;maxStreak:number;score:number;earnedXp:number}>(null);const [pending,startTransition]=useTransition();
  const deck=useMemo(()=>mode==="WEEKLY"?slides.slice(0,Math.min(20,slides.length)):slides,[mode,slides]);const slide=deck[index];const kind=(['MEANING','AUDIO','SPELLING','CONTEXT'] as Kind[])[index%4];const options=slide?shuffledOptions(deck,index):[];
  const t=english?{title:"Vocabulary Quest",daily:"Daily quest",weekly:"Weekly exam",intro:"Four game types, automatic scoring, streak bonuses and weak-word review.",start:"Start challenge",meaning:"Match the word",audio:"Listen and choose",spelling:"Spell the word",context:"Complete the sentence",submit:"Check answer",next:"Next challenge",correct:"Correct!",wrong:"Not quite",streak:"streak",finish:"Challenge complete",score:"Score",xp:"XP earned",again:"Play again",more:"Continue with another batch"}:{title:"单词趣味闯关",daily:"每日闯关",weekly:"本周词汇考试",intro:"四种游戏题型、系统自动判分、连击奖励，并自动强化错词。",start:"开始挑战",meaning:"释义配对",audio:"听音选词",spelling:"拼写挑战",context:"情境填空",submit:"确认答案",next:"下一关",correct:"回答正确！",wrong:"再接再厉",streak:"连击",finish:"闯关完成",score:"总分",xp:"获得 XP",again:"再玩一次",more:"继续学习下一组"};
  function speak(){if(!slide)return;const utterance=new SpeechSynthesisUtterance(slide.word);utterance.lang="en-US";utterance.rate=.78;speechSynthesis.cancel();speechSynthesis.speak(utterance)}
  function check(answer=value){if(feedback!==null||!slide)return;const correct=answer.trim().toLowerCase()===slide.word.toLowerCase();setValue(answer);setFeedback(correct);setStreak(correct?streak+1:0);setAnswers([...answers,{vocabularyId:slide.id,questionType:kind,answer,responseMs:Math.min(300000,Date.now()-startedAt)}]);}
  function next(){if(index<deck.length-1){setIndex(index+1);setValue("");setFeedback(null);setStartedAt(Date.now());return}const data=new FormData();data.set("profileId",profileId);data.set("mode",mode);data.set("answers",JSON.stringify(answers));startTransition(async()=>setResult(await submitVocabularyGame(data)));}
  function reset(){setStarted(false);setIndex(0);setAnswers([]);setValue("");setFeedback(null);setStreak(0);setResult(null)}
  if(!slides.length)return null;
  if(result)return <section className="mt-8 rounded-[2rem] bg-gradient-to-br from-indigo-950 via-violet-800 to-fuchsia-700 p-8 text-center text-white shadow-2xl"><Trophy className="mx-auto text-amber-300" size={64}/><h2 className="mt-4 text-4xl font-black">{t.finish}</h2><div className="mx-auto mt-7 grid max-w-xl grid-cols-3 gap-3"><Metric label={t.score} value={result.score}/><Metric label={t.xp} value={`+${result.earnedXp}`}/><Metric label={t.streak} value={result.maxStreak}/></div><p className="mt-5 text-white/75">{result.correct}/{result.total} · {Math.round(result.correct/result.total*100)}%</p><div className="mt-7 flex flex-wrap justify-center gap-3"><button className="rounded-xl bg-white/15 px-6 py-3 font-black" onClick={reset}>{t.again}</button><button className="rounded-xl bg-white px-6 py-3 font-black text-violet-900" onClick={()=>window.location.reload()}>{t.more}</button></div></section>;
  if(!started)return <section className="card mt-8 overflow-hidden bg-gradient-to-r from-violet-950 to-indigo-800 text-white"><Gamepad2 size={42}/><h2 className="mt-3 text-3xl font-black">{t.title}</h2><p className="mt-2 text-white/70">{t.intro}</p><div className="mt-5 flex flex-wrap gap-3"><button className={mode==="DAILY"?"rounded-xl bg-white px-4 py-2 font-bold text-violet-900":"rounded-xl bg-white/15 px-4 py-2 font-bold"} onClick={()=>setMode("DAILY")}>{t.daily}</button><button className={mode==="WEEKLY"?"rounded-xl bg-white px-4 py-2 font-bold text-violet-900":"rounded-xl bg-white/15 px-4 py-2 font-bold"} onClick={()=>setMode("WEEKLY")}>{t.weekly}</button></div><button className="mt-6 rounded-xl bg-amber-300 px-6 py-3 font-black text-slate-950" onClick={()=>{setStarted(true);setStartedAt(Date.now())}}>{t.start} · {deck.length} {english?"questions":"题"}</button></section>;
  const prompt=kind==="MEANING"?(english?slide.definitionEn:slide.meaning):kind==="CONTEXT"?(slide.example?.replace(new RegExp(`\\b${slide.word}\\b`,'i'),"____")??slide.definitionEn):"";const title={MEANING:t.meaning,AUDIO:t.audio,SPELLING:t.spelling,CONTEXT:t.context}[kind];
  return <section className="mt-8 overflow-hidden rounded-[2rem] bg-gradient-to-br from-indigo-950 via-violet-900 to-fuchsia-800 p-6 text-white shadow-2xl md:p-10"><div className="flex items-center justify-between"><span className="font-bold">{mode==="DAILY"?t.daily:t.weekly} · {index+1}/{deck.length}</span><span className="rounded-full bg-amber-300 px-3 py-1 font-black text-slate-950"><Zap className="mr-1 inline" size={16}/>{streak} {t.streak}</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-amber-300" style={{width:`${(index+1)/deck.length*100}%`}}/></div><div className="grid min-h-[28rem] place-items-center py-8 text-center"><div className="w-full max-w-2xl">{kind==="AUDIO"?<Headphones className="mx-auto" size={42}/>:kind==="SPELLING"?<Keyboard className="mx-auto" size={42}/>:kind==="MEANING"?<Link2 className="mx-auto" size={42}/>:<Gamepad2 className="mx-auto" size={42}/>}<h2 className="mt-3 text-3xl font-black">{title}</h2>{kind==="AUDIO"&&<button className="mt-8 rounded-full bg-white/15 p-6 hover:bg-white/25" onClick={speak}><Volume2 size={38}/></button>}{prompt&&<p className="mx-auto mt-7 max-w-xl text-2xl font-bold leading-relaxed">{prompt}</p>}{kind==="SPELLING"&&<p className="mt-7 text-xl">{english?slide.definitionEn:slide.meaning}</p>}{kind==="SPELLING"?<div className="mx-auto mt-7 flex max-w-md gap-3"><input className="input mt-0 bg-white text-slate-950" value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')check()}} autoFocus/><button className="rounded-xl bg-white px-4 font-bold text-violet-900" onClick={()=>check()}>{t.submit}</button></div>:<div className="mt-8 grid gap-3 sm:grid-cols-2">{options.map(option=><button className="rounded-2xl bg-white/15 p-4 text-lg font-bold hover:bg-white/25 disabled:opacity-70" disabled={feedback!==null} key={option} onClick={()=>check(option)}>{option}</button>)}</div>}{feedback!==null&&<div className={`mt-7 rounded-2xl p-4 font-black ${feedback?"bg-emerald-400/20":"bg-rose-400/20"}`}>{feedback?t.correct:`${t.wrong} · ${slide.word}`}<button className="ml-4 rounded-xl bg-white px-4 py-2 text-violet-900 disabled:opacity-50" disabled={pending} onClick={next}>{t.next}</button></div>}</div></div></section>;
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-white/15 p-4"><strong className="block text-3xl">{value}</strong><span className="text-xs text-white/70">{label}</span></div>}
