import { auth } from "@/auth";
import { db } from "@/lib/db";
import { getAccessContext } from "@/modules/authorization/context";
import { canManageFamily } from "@/modules/authorization/policy";
import { createFamily, createMember } from "@/modules/family/actions";

export default async function FamilyPage() {
  const session = await auth(); const ctx = await getAccessContext(session!.user.id);
  const families = await db.family.findMany({ where: { deletedAt: null, OR: [{ ownerUserId: session!.user.id }, { members: { some: { userId: session!.user.id, deletedAt: null } } }] }, include: { members: { where: { deletedAt: null }, include: { learnerProfile: true }, orderBy: { createdAt: "asc" } } } });
  return <div className="mx-auto max-w-6xl"><h1 className="text-4xl font-black">家庭与成员</h1><p className="mt-2 text-muted">家庭数据仅对有权限的成员开放。</p>
    {!families.length && <form action={createFamily} className="card mt-8 max-w-xl"><h2 className="text-xl font-bold">创建第一个家庭</h2><label className="mt-5 block"><span className="label">家庭名称</span><input className="input" name="name" required defaultValue="我的家庭" /></label><label className="mt-4 block"><span className="label">时区</span><input className="input" name="timezone" required defaultValue="America/Chicago" /></label><button className="button-primary mt-5">创建家庭</button></form>}
    <div className="mt-8 space-y-6">{families.map((family) => <section className="card" key={family.id}><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-2xl font-bold">{family.name}</h2><p className="text-sm text-muted">{family.timezone} · {family.members.length} 位成员</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-2">{family.members.map((m) => <div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-700" key={m.id}><strong>{m.displayName}</strong>{m.nickname && <span className="ml-2 text-muted">({m.nickname})</span>}<p className="mt-1 text-sm text-muted">{m.memberType} · {m.learnerProfile ? `${m.learnerProfile.dailyMinutes} 分钟/天` : "管理成员"}</p></div>)}</div>
      {canManageFamily(ctx, family.id) && <form action={createMember} className="mt-7 grid gap-3 border-t border-slate-200 pt-6 dark:border-slate-700 md:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="familyId" value={family.id}/><input className="input mt-0" name="displayName" placeholder="成员姓名" required/><input className="input mt-0" name="nickname" placeholder="昵称（可选）"/><select className="input mt-0" name="memberType" defaultValue="LEARNER"><option value="PARENT">家长</option><option value="LEARNER">普通成员</option><option value="CHILD">学生/儿童</option></select><select className="input mt-0" name="ageBand" defaultValue="ADULT"><option value="CHILD">儿童</option><option value="TEEN">青少年</option><option value="ADULT">成人</option><option value="SENIOR">长者</option></select><div className="flex gap-2"><select className="input mt-0" name="dailyMinutes" defaultValue="20">{[10,15,20,30,45,60].map(v=><option key={v}>{v}</option>)}</select><button className="button-primary whitespace-nowrap">添加</button></div></form>}</section>)}</div>
  </div>;
}
