import type { Prisma } from "@prisma/client";
import { db } from "@/lib/db";
import type { PipelineGrammarOutput, PipelineReadingOutput, PipelineScenarioOutput, PipelineVocabularyOutput } from "./generation-schemas";
import type { SupportedGenerationType } from "./generator";

export async function persistGeneratedDraft(type:SupportedGenerationType,output:unknown,jobId:string){
  if(type==="VOCABULARY_GENERATION")return persistVocabulary(output as PipelineVocabularyOutput,jobId);
  if(type==="READING_GENERATION")return persistReading(output as PipelineReadingOutput,jobId);
  if(type==="GRAMMAR_GENERATION")return persistGrammar(output as PipelineGrammarOutput,jobId);
  return persistScenario(output as PipelineScenarioOutput,jobId);
}

async function persistVocabulary(value:PipelineVocabularyOutput,jobId:string){return db.$transaction(async tx=>{
  const duplicate=await tx.vocabulary.findFirst({where:{word:{equals:value.word,mode:"insensitive"},partOfSpeech:value.partOfSpeech}});if(duplicate)throw new Error(`DUPLICATE_CONTENT:${duplicate.id}`);
  const row=await tx.vocabulary.create({data:{word:value.word,phonetic:value.phonetic,partOfSpeech:value.partOfSpeech,definitionEn:value.definitionEn,level:value.level,topic:value.topic,status:"DRAFT",sourceType:"AI",generationJobId:jobId,aiGenerated:true,reviewStatus:"PENDING",meanings:{create:{locale:"zh-CN",definition:value.definitionZh}},examples:{create:value.examples.map(example=>({sentence:example.sentence,translation:example.translation,collocations:value.collocations,difficulty:value.level}))}}});return{contentType:"Vocabulary",contentId:row.id};
})}
async function persistReading(value:PipelineReadingOutput,jobId:string){return db.$transaction(async tx=>{const row=await tx.readingArticle.create({data:{title:value.title,body:value.body,translation:value.translation,level:value.level,audience:value.audience,wordCount:value.body.trim().split(/\s+/).length,topic:value.topic,targetVocabulary:value.targetVocabulary,targetGrammar:value.targetGrammar,summary:value.summary,oralRetellingPrompt:value.oralRetellingPrompt,writingExtensionPrompt:value.writingExtensionPrompt,status:"DRAFT",sourceType:"AI",generationJobId:jobId,aiGenerated:true,reviewStatus:"PENDING",questions:{create:value.questions.map((q,index)=>({type:q.type,prompt:q.prompt,options:q.options as Prisma.InputJsonValue|undefined,answerKey:q.answerKey,explanation:q.explanation,order:index+1}))}}});return{contentType:"ReadingArticle",contentId:row.id}})}
async function persistGrammar(value:PipelineGrammarOutput,jobId:string){return db.$transaction(async tx=>{const base=value.slug.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"grammar";const slug=`${base}-${jobId.slice(0,8)}-${Date.now().toString(36)}`;const row=await tx.grammarTopic.create({data:{slug,title:value.title,ruleEn:value.ruleEn,ruleZh:value.ruleZh,commonErrors:value.commonErrors,useCases:value.useCases,contrastExamples:value.contrastExamples,status:"DRAFT",level:value.level,sourceType:"AI",generationJobId:jobId,aiGenerated:true,reviewStatus:"PENDING",examples:{create:value.examples.map(x=>({sentence:x.sentence,translation:x.translation,isError:x.isError,explanation:x.explanation}))},exercises:{create:value.exercises.map((q,index)=>({type:q.type,prompt:q.prompt,options:q.options as Prisma.InputJsonValue|undefined,answerKey:q.answerKey,explanation:q.explanation,order:index+1}))}}});return{contentType:"GrammarTopic",contentId:row.id}})}
async function persistScenario(value:PipelineScenarioOutput,jobId:string){return db.$transaction(async tx=>{const version=await tx.scenarioLesson.count({where:{category:value.category,title:value.title}})+1;const row=await tx.scenarioLesson.create({data:{category:value.category,title:value.title,intro:value.intro,level:value.level,cultureTips:value.cultureTips,misunderstandings:value.misunderstandings,naturalExpressions:value.naturalExpressions,sourceType:"AI_GENERATED",sourceNote:"HomeLingua structured AI generation",status:"DRAFT",version,contentSourceType:"AI",generationJobId:jobId,aiGenerated:true,reviewStatus:"PENDING",dialogues:{create:value.dialogues.map((x,index)=>({...x,sequence:index+1}))},exercises:{create:value.exercises.map((q,index)=>({type:q.type,prompt:q.prompt,options:q.options as Prisma.InputJsonValue|undefined,answerKey:q.answerKey,explanation:q.explanation,order:index+1}))},vocabulary:{create:value.vocabulary.map((x,index)=>({...x,order:index+1}))}}});return{contentType:"ScenarioLesson",contentId:row.id}})}
