import Link from "next/link";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { SpeechPlayer } from "@/components/speech-player";
import { db } from "@/lib/db";
import { addListeningQuestion, deleteListeningQuestion, updateContentStatus, updateListeningMetadata } from "@/modules/admin/actions";
import { listeningPublishReadiness } from "@/modules/admin/content-schemas";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";

const levels = ["PRE_A1", "A1", "A2", "B1", "B2", "C1", "C2"];

export default async function ListeningEditorPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSystemAdmin(); const english = (await cookies()).get("ui_locale")?.value === "en"; const { id } = await params;
  const exercise = await db.listeningExercise.findUnique({ where: { id }, include: { questions: { orderBy: { order: "asc" } } } }); if (!exercise) notFound();
  const missing = listeningPublishReadiness({ questions: exercise.questions.length, transcript: exercise.transcript });
  const t = english ? { back:"Back to content", editor:"Listening lesson editor", preview:"Audio preview", readiness:"Publication readiness", ready:"Ready to publish", missing:"Still required", status:"Status", update:"Update status", info:"Lesson information", title:"Title", transcript:"English transcript", translation:"Chinese translation (optional)", topic:"Topic", audio:"External audio URL (optional; browser speech is used when empty)", save:"Save lesson", questions:"Automatically scored listening questions", add:"Add question", prompt:"Question", options:"Options, one per line", answer:"Answer key (must exactly match an option)", explanation:"Explanation (optional)", remove:"Remove" } : { back:"返回内容管理", editor:"听力课程编辑器", preview:"试听课程内容", readiness:"发布完整度", ready:"已经达到发布标准", missing:"仍需补齐", status:"状态", update:"更新状态", info:"课程信息", title:"标题", transcript:"英文听力稿", translation:"中文翻译（可选）", topic:"主题", audio:"外部音频 URL（可选；留空使用浏览器朗读）", save:"保存课程", questions:"自动判分听力题", add:"新增题目", prompt:"题目", options:"选项（每行一项）", answer:"标准答案（必须与某个选项完全一致）", explanation:"答案解析（可选）", remove:"删除" };
  return <div className="mx-auto max-w-6xl"><Link className="text-sm font-bold text-brand" href="/admin/content">← {t.back}</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-brand">{exercise.level} · {exercise.topic}</p><h1 className="mt-1 text-4xl font-black">{t.editor}</h1><p className="mt-2 text-muted">{exercise.title}</p></div><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value="listening"/><input type="hidden" name="id" value={exercise.id}/><label><span className="label">{t.status}</span><select className="input" name="status" defaultValue={exercise.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><button className="button-primary">{t.update}</button></form></div>
  <section className={missing.length ? "mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-100" : "mt-6 rounded-2xl border border-emerald-300 bg-emerald-50 p-5 text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"}><h2 className="font-black">{t.readiness}</h2><p className="mt-2">{missing.length ? `${t.missing}: ${missing.join(english ? ", " : "、")}` : `✓ ${t.ready}`}</p></section>
  <section className="card mt-6"><h2 className="text-2xl font-black">{t.preview}</h2><div className="mt-4"><SpeechPlayer text={exercise.transcript}/></div>{exercise.audioUrl&&<audio className="mt-4 w-full" controls src={exercise.audioUrl}/>}</section>
  <section className="card mt-6"><h2 className="text-2xl font-black">{t.info}</h2><form action={updateListeningMetadata} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="exerciseId" value={exercise.id}/><Field name="title" label={t.title} value={exercise.title}/><label><span className="label">CEFR</span><select className="input" name="level" defaultValue={exercise.level}>{levels.map(level=><option key={level}>{level}</option>)}</select></label><Field name="topic" label={t.topic} value={exercise.topic}/><Field name="audioUrl" label={t.audio} value={exercise.audioUrl ?? ""} optional/><Area name="transcript" label={t.transcript} value={exercise.transcript} tall/><Area name="translation" label={t.translation} value={exercise.translation ?? ""} tall/><button className="button-primary md:col-span-2">{t.save}</button></form></section>
  <section className="card mt-6"><h2 className="text-2xl font-black">{t.questions} ({exercise.questions.length})</h2><div className="mt-4 grid gap-3">{exercise.questions.map(item=><div key={item.id} className="flex items-start justify-between gap-3 rounded-xl bg-slate-100 p-4 dark:bg-slate-800"><div><strong>{item.order}. {item.prompt}</strong><p className="mt-1 text-sm text-muted">{t.answer}: {item.answerKey}</p>{item.explanation&&<p className="mt-1 text-sm text-muted">{item.explanation}</p>}</div><form action={deleteListeningQuestion}><input type="hidden" name="exerciseId" value={exercise.id}/><input type="hidden" name="id" value={item.id}/><button className="text-xs font-bold text-red-700">{t.remove}</button></form></div>)}</div><form action={addListeningQuestion} className="mt-6 grid gap-3 border-t pt-6 md:grid-cols-2"><input type="hidden" name="exerciseId" value={exercise.id}/><Field name="prompt" label={t.prompt}/><Field name="answerKey" label={t.answer}/><Area name="options" label={t.options}/><Field name="explanation" label={t.explanation} optional/><button className="button-primary md:col-span-2">{t.add}</button></form></section></div>;
}
function Field({name,label,value="",optional=false}:{name:string;label:string;value?:string;optional?:boolean}){return <label><span className="label">{label}</span><input className="input" name={name} defaultValue={value} required={!optional}/></label>}
function Area({name,label,value="",tall=false}:{name:string;label:string;value?:string;tall?:boolean}){return <label><span className="label">{label}</span><textarea className={`input ${tall?"min-h-72":"min-h-28"}`} name={name} defaultValue={value}/></label>}
