import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { auth } from "@/auth"; import { db } from "@/lib/db"; import { getAccessibleProfiles } from "@/modules/learner/access"; import { getActiveProfile } from "@/modules/learner/selection"; import { submitGrammar } from "@/modules/grammar/actions";

export default async function GrammarTopicPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await auth(); const { id } = await params; const english = (await cookies()).get("ui_locale")?.value === "en"; const selected = await getActiveProfile(await getAccessibleProfiles(session!.user.id)); if (!selected) notFound(); const profileId = selected.id;
  const topic = await db.grammarTopic.findFirst({ where: { id, status: "PUBLISHED" }, include: { examples: true, exercises: { orderBy: { order: "asc" } }, progress: { where: { learnerProfileId: profileId }, include: { attempts: { orderBy: { createdAt: "desc" }, take: 20 } } } } }); if (!topic) notFound();
  const recent = topic.progress[0]?.attempts ?? []; const contrasts = Array.isArray(topic.contrastExamples) ? topic.contrastExamples as Array<{ correct?: string; incorrect?: string; note?: string }> : [];
  const t = english ? { rule: "Short rule", uses: "When to use it", mistakes: "Common mistakes", practice: "Practice", correct: "Your last answer was correct", wrong: "Last answer was incorrect. Answer", submit: "Submit practice" } : { rule: "简短规则", uses: "适用场景", mistakes: "常见错误", practice: "多类型练习", correct: "上次回答正确", wrong: "上次回答错误。答案", submit: "提交练习" };
  return <div className="mx-auto max-w-4xl"><p className="font-bold text-brand">{topic.level}</p><h1 className="mt-2 text-4xl font-black">{topic.title}</h1><section className="card mt-7"><h2 className="text-xl font-black">{t.rule}</h2><p className="mt-3 whitespace-pre-wrap leading-7">{topic.ruleEn}</p>{!english && <p className="mt-4 whitespace-pre-wrap leading-7 text-muted">{topic.ruleZh}</p>}<div className="mt-5 grid gap-4 md:grid-cols-2"><div><h3 className="font-black">{t.uses}</h3><ul className="mt-2 list-disc pl-5">{topic.useCases.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3 className="font-black">{t.mistakes}</h3><ul className="mt-2 list-disc pl-5 text-amber-800">{topic.commonErrors.map((item) => <li key={item}>{item}</li>)}</ul></div></div>{contrasts.map((item, index) => <div className="mt-4 grid gap-2 rounded-xl bg-slate-100 p-3 dark:bg-slate-800 sm:grid-cols-2" key={index}><span className="text-green-700">✓ {item.correct}</span><span className="text-red-700">✕ {item.incorrect}</span><small className="sm:col-span-2">{item.note}</small></div>)}<div className="mt-5 space-y-2">{topic.examples.map((item) => <div className={item.isError ? "rounded-xl bg-red-50 p-3 text-red-900" : "rounded-xl bg-green-50 p-3 text-green-900"} key={item.id}>{item.sentence}{!english && <span className="ml-2 opacity-70">{item.translation}</span>}{item.explanation && <p className="text-sm">{item.explanation}</p>}</div>)}</div></section><form action={submitGrammar} className="card mt-5"><input type="hidden" name="profileId" value={profileId}/><input type="hidden" name="topicId" value={topic.id}/><h2 className="text-xl font-black">{t.practice}</h2><div className="mt-5 space-y-6">{topic.exercises.map((exercise, index) => { const options = Array.isArray(exercise.options) ? exercise.options as string[] : []; const last = recent.find((attempt) => attempt.exerciseId === exercise.id); return <fieldset key={exercise.id}><legend className="font-bold">{index + 1}. [{exercise.type}] {exercise.prompt}</legend>{options.length ? options.map((option) => <label className="mt-2 block rounded-xl border p-3" key={option}><input className="mr-2" type="radio" name={`exercise_${exercise.id}`} value={option}/>{option}</label>) : <input className="input" name={`exercise_${exercise.id}`}/>} {last && <p className={last.isCorrect ? "mt-2 text-green-700" : "mt-2 text-red-700"}>{last.isCorrect ? t.correct : `${t.wrong}: ${exercise.answerKey}`}</p>}</fieldset>; })}</div><button className="button-primary mt-6">{t.submit}</button></form></div>;
}

