import Link from "next/link";
import { notFound } from "next/navigation";
import { cookies } from "next/headers";
import { db } from "@/lib/db";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";
import { addScenarioDialogue, addScenarioExercise, addScenarioVocabulary, deleteScenarioItem, updateContentStatus, updateScenarioMetadata } from "@/modules/admin/actions";
import { scenarioPublishReadiness } from "@/modules/admin/content-schemas";

const levels = ["PRE_A1", "A1", "A2", "B1", "B2", "C1"];

export default async function ScenarioEditorPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSystemAdmin();
  const english = (await cookies()).get("ui_locale")?.value === "en";
  const { id } = await params;
  const lesson = await db.scenarioLesson.findUnique({
    where: { id },
    include: { dialogues: { orderBy: { sequence: "asc" } }, vocabulary: { orderBy: { order: "asc" } }, exercises: { orderBy: { order: "asc" } } },
  });
  if (!lesson) notFound();
  const missing = scenarioPublishReadiness({ dialogues: lesson.dialogues.length, vocabulary: lesson.vocabulary.length, exercises: lesson.exercises.length, cultureTips: lesson.cultureTips.length, naturalExpressions: lesson.naturalExpressions.length });
  const t = english ? {
    back: "Back to content", title: "Scenario lesson editor", readiness: "Publication readiness", ready: "Ready to publish", missing: "Still required", metadata: "Lesson information", category: "Category", lessonTitle: "Title", intro: "Scenario introduction", culture: "Culture tips (one per line)", misunderstandings: "Common misunderstandings (one per line)", expressions: "Natural expressions (one per line)", source: "Source note", save: "Save lesson information", dialogue: "Dialogue script", addDialogue: "Add dialogue line", speaker: "Speaker key", role: "Displayed role", englishLine: "English line", chineseLine: "Chinese translation", camera: "Scene / camera cue", vocabulary: "Scenario vocabulary", addWord: "Add vocabulary", word: "Word or phrase", meaning: "Chinese meaning", example: "Example sentence", exercises: "Comprehension exercises", addExercise: "Add multiple-choice question", prompt: "Question", options: "Options, one per line", answer: "Correct option (must exactly match one option)", explanation: "Explanation", remove: "Remove", status: "Lesson status", update: "Update status",
  } : {
    back: "返回内容管理", title: "场景课程编辑器", readiness: "发布完整度", ready: "已经达到发布标准", missing: "仍需补齐", metadata: "课程信息", category: "分类", lessonTitle: "标题", intro: "场景介绍", culture: "文化提示（每行一条）", misunderstandings: "常见误解（每行一条）", expressions: "自然表达（每行一条）", source: "内容来源说明", save: "保存课程信息", dialogue: "完整对话脚本", addDialogue: "新增一句对话", speaker: "说话者标识", role: "显示角色", englishLine: "英文台词", chineseLine: "中文翻译", camera: "镜头/场景提示", vocabulary: "场景常用词汇", addWord: "新增词汇", word: "单词或短语", meaning: "中文含义", example: "例句", exercises: "理解练习", addExercise: "新增选择题", prompt: "题目", options: "选项，每行一项", answer: "正确选项（必须与某个选项完全相同）", explanation: "答案解释", remove: "删除", status: "课程状态", update: "更新状态",
  };

  return <div className="mx-auto max-w-6xl">
    <Link className="text-sm font-bold text-brand" href="/admin/content">← {t.back}</Link>
    <div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-bold text-brand">{lesson.category} · {lesson.level} · v{lesson.version}</p><h1 className="mt-1 text-4xl font-black">{t.title}</h1><p className="mt-2 text-muted">{lesson.title}</p></div><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value="scenario"/><input type="hidden" name="id" value={lesson.id}/><label><span className="label">{t.status}</span><select className="input" name="status" defaultValue={lesson.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><button className="button-primary">{t.update}</button></form></div>
    <section className={missing.length ? "mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-100" : "mt-6 rounded-2xl border border-emerald-300 bg-emerald-50 p-5 text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"}><h2 className="font-black">{t.readiness}</h2><p className="mt-2">{missing.length ? `${t.missing}: ${missing.join(english ? ", " : "、")}` : `✓ ${t.ready}`}</p></section>

    <section className="card mt-6"><h2 className="text-2xl font-black">{t.metadata}</h2><form action={updateScenarioMetadata} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="lessonId" value={lesson.id}/><Field name="category" label={t.category} value={lesson.category}/><Field name="title" label={t.lessonTitle} value={lesson.title}/><label className="md:col-span-2"><span className="label">{t.intro}</span><textarea className="input min-h-28" name="intro" defaultValue={lesson.intro} required/></label><label><span className="label">CEFR</span><select className="input" name="level" defaultValue={lesson.level}>{levels.map(level => <option key={level}>{level}</option>)}</select></label><Field name="sourceNote" label={t.source} value={lesson.sourceNote ?? ""}/><TextLines name="cultureTips" label={t.culture} values={lesson.cultureTips}/><TextLines name="misunderstandings" label={t.misunderstandings} values={lesson.misunderstandings}/><TextLines name="naturalExpressions" label={t.expressions} values={lesson.naturalExpressions}/><button className="button-primary md:col-span-2">{t.save}</button></form></section>

    <section className="card mt-6"><h2 className="text-2xl font-black">{t.dialogue} ({lesson.dialogues.length})</h2><div className="mt-4 space-y-2">{lesson.dialogues.map(item => <ItemRow key={item.id} title={`${item.sequence}. ${item.roleName}: ${item.textEn}`} subtitle={item.textZh ?? ""} lessonId={lesson.id} id={item.id} type="dialogue" remove={t.remove}/>)}</div><form action={addScenarioDialogue} className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-2"><input type="hidden" name="lessonId" value={lesson.id}/><Field name="speaker" label={t.speaker}/><Field name="roleName" label={t.role}/><label><span className="label">{t.englishLine}</span><textarea className="input min-h-24" name="textEn" required/></label><label><span className="label">{t.chineseLine}</span><textarea className="input min-h-24" name="textZh"/></label><Field name="cameraCue" label={t.camera}/><button className="button-primary self-end">{t.addDialogue}</button></form></section>

    <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card"><h2 className="text-2xl font-black">{t.vocabulary} ({lesson.vocabulary.length})</h2><div className="mt-4 space-y-2">{lesson.vocabulary.map(item => <ItemRow key={item.id} title={`${item.order}. ${item.word} · ${item.meaningZh}`} subtitle={item.example ?? ""} lessonId={lesson.id} id={item.id} type="vocabulary" remove={t.remove}/>)}</div><form action={addScenarioVocabulary} className="mt-5 grid gap-3 border-t pt-5"><input type="hidden" name="lessonId" value={lesson.id}/><Field name="word" label={t.word}/><Field name="meaningZh" label={t.meaning}/><Field name="example" label={t.example}/><button className="button-primary">{t.addWord}</button></form></div>
    <div className="card"><h2 className="text-2xl font-black">{t.exercises} ({lesson.exercises.length})</h2><div className="mt-4 space-y-2">{lesson.exercises.map(item => <ItemRow key={item.id} title={`${item.order}. ${item.prompt}`} subtitle={`${t.answer}: ${item.answerKey}`} lessonId={lesson.id} id={item.id} type="exercise" remove={t.remove}/>)}</div><form action={addScenarioExercise} className="mt-5 grid gap-3 border-t pt-5"><input type="hidden" name="lessonId" value={lesson.id}/><Field name="prompt" label={t.prompt}/><label><span className="label">{t.options}</span><textarea className="input min-h-28" name="options" required/></label><Field name="answerKey" label={t.answer}/><Field name="explanation" label={t.explanation}/><button className="button-primary">{t.addExercise}</button></form></div></section>
  </div>;
}

function Field({ name, label, value = "" }: { name: string; label: string; value?: string }) { return <label><span className="label">{label}</span><input className="input" name={name} defaultValue={value} required={!['sourceNote','cameraCue','example','explanation'].includes(name)}/></label>; }
function TextLines({ name, label, values }: { name: string; label: string; values: string[] }) { return <label><span className="label">{label}</span><textarea className="input min-h-28" name={name} defaultValue={values.join("\n")}/></label>; }
function ItemRow({ title, subtitle, lessonId, id, type, remove }: { title: string; subtitle: string; lessonId: string; id: string; type: "dialogue" | "vocabulary" | "exercise"; remove: string }) { return <div className="flex items-start justify-between gap-3 rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><div className="min-w-0"><strong className="block">{title}</strong>{subtitle && <p className="mt-1 text-sm text-muted">{subtitle}</p>}</div><form action={deleteScenarioItem}><input type="hidden" name="lessonId" value={lessonId}/><input type="hidden" name="id" value={id}/><input type="hidden" name="type" value={type}/><button className="text-xs font-bold text-red-700 dark:text-red-300">{remove}</button></form></div>; }
