import { auth } from "@/auth";
import { cookies } from "next/headers";
import { db } from "@/lib/db";
import { ProfilePicker } from "@/components/profile-picker";
import { getAccessibleProfiles } from "@/modules/learner/access";
import { adjustLearningPlan, generateLearningPlan, rollbackLearningPlan } from "@/modules/planning/actions";

export default async function PlansPage({ searchParams }: { searchParams: Promise<{ profile?: string }> }) {
  const session = await auth(); const english = (await cookies()).get("ui_locale")?.value === "en"; const query = await searchParams; const profiles = await getAccessibleProfiles(session!.user.id); const selected = profiles.find((profile) => profile.id === query.profile) ?? profiles[0];
  const plans = selected ? await db.learningPlan.findMany({ where: { learnerProfileId: selected.id }, include: { items: { orderBy: { scheduledDate: "asc" } } }, orderBy: [{ periodStart: "desc" }, { version: "desc" }], take: 10 }) : [];
  const active = plans.find((plan) => plan.status === "ACTIVE");
  const locale = english ? "en-US" : "zh-CN";
  const t = english ? { title: "Personalized learning plan", regenerate: "Regenerate from recent performance", generate: "Generate this week's plan", version: "Version", goals: "Weekly goals", rollback: "Restore previous version", focus: "Priority weak areas", courses: "Recommended courses", review: "Recommended review", stages: "Four-week milestones", adjustments: "Dynamic adjustment suggestions", monthly: "Monthly evaluation", daily: "Daily task schedule", minutes: "min", manual: "Adjust plan manually", newGoal: "New goal", reason: "Reason for adjustment", save: "Save as new version", none: "No learning plan has been generated yet.", history: "Version history", fallback: "Generated from future learning data" } : { title: "个性化学习计划", regenerate: "依据最近表现重新生成", generate: "生成本周计划", version: "第", goals: "本周目标", rollback: "回滚上一版", focus: "重点薄弱项目", courses: "推荐课程", review: "推荐复习内容", stages: "四周阶段目标", adjustments: "动态调整建议", monthly: "月度评估", daily: "每日任务安排", minutes: "分钟", manual: "人工调整计划", newGoal: "新目标", reason: "调整原因", save: "保存为新版本", none: "尚未生成学习计划。", history: "历史版本", fallback: "根据后续学习数据生成" };
  return <div className="mx-auto max-w-6xl">
    <p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Learning plan</p><h1 className="mt-2 text-4xl font-black">{t.title}</h1>
    <ProfilePicker profiles={profiles} selectedId={selected?.id} pathname="/plans"/>
    {selected && <div className="mt-6 flex justify-end"><form action={generateLearningPlan}><input type="hidden" name="profileId" value={selected.id}/><button className="button-primary">{active ? t.regenerate : t.generate}</button></form></div>}
    {active && <section className="card mt-5">
      <div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold text-brand">{t.version} {active.version} · {active.generationSource}</p><h2 className="mt-1 text-2xl font-black">{active.periodStart.toLocaleDateString(locale)} — {active.periodEnd.toLocaleDateString(locale)}</h2><p className="mt-2">{t.goals}: {active.goals.join(english ? ", " : "、")}</p><p className="mt-2 text-sm text-muted">{active.adjustmentReason}</p></div>{active.supersedesId && <form action={rollbackLearningPlan}><input type="hidden" name="planId" value={active.id}/><button className="button-ghost">{t.rollback}</button></form>}</div>
      <div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><PlanList title={t.focus} items={active.focusAreas} fallback={t.fallback}/><PlanList title={t.courses} items={active.recommendedCourses} fallback={t.fallback}/><PlanList title={t.review} items={active.reviewContent} fallback={t.fallback}/><PlanList title={t.stages} items={active.stageGoals} fallback={t.fallback}/><PlanList title={t.adjustments} items={active.adjustmentSuggestions} fallback={t.fallback}/><div className="rounded-2xl bg-slate-100 p-4 dark:bg-slate-800"><h3 className="font-black">{t.monthly}</h3><p className="mt-2 text-sm text-muted">{active.monthlyEvaluation ?? (english ? "Reassess from all modules at month end." : "月底根据所有模块表现重新评估。")}</p></div></div>
      <h3 className="mt-7 text-xl font-black">{t.daily}</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{active.items.map((item) => <div className="rounded-2xl border p-4" key={item.id}><p className="text-xs font-bold text-brand">{item.scheduledDate.toLocaleDateString(locale)} · {item.module}</p><h4 className="mt-1 font-black">{item.title}</h4><p className="mt-2 text-sm text-muted">{item.target} · {item.durationMinutes} {t.minutes}</p></div>)}</div>
      <details className="mt-6 border-t pt-4"><summary className="cursor-pointer font-bold text-brand">{t.manual}</summary><form action={adjustLearningPlan} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="planId" value={active.id}/><label><span className="label">{t.newGoal}</span><input className="input" name="goal" defaultValue={active.goals[0]} required/></label><label><span className="label">{t.reason}</span><input className="input" name="reason" placeholder={english ? "For example: an exam this week; add grammar practice" : "例如：本周考试，增加语法练习"} required/></label><button className="button-primary md:col-span-2">{t.save}</button></form></details>
    </section>}
    {selected && !active && <div className="card mt-6 text-center">{t.none}</div>}
    {plans.some((plan) => plan.status !== "ACTIVE") && <details className="card mt-5"><summary className="cursor-pointer font-bold">{t.history}</summary><div className="mt-4 space-y-2">{plans.filter((plan) => plan.status !== "ACTIVE").map((plan) => <p className="rounded-xl bg-slate-100 p-3 dark:bg-slate-800" key={plan.id}>{t.version} {plan.version} · {plan.status} · {plan.adjustmentReason ?? plan.generationSource}</p>)}</div></details>}
  </div>;
}

function PlanList({ title, items, fallback }: { title: string; items: string[]; fallback: string }) { return <div className="rounded-2xl bg-slate-100 p-4 dark:bg-slate-800"><h3 className="font-black">{title}</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-muted">{items.map((item) => <li key={item}>{item}</li>)}{!items.length && <li>{fallback}</li>}</ul></div>; }
