import { cookies } from "next/headers";
import { auth } from "@/auth"; import { db } from "@/lib/db"; import { SpeechPlayer } from "@/components/speech-player"; import { getAccessibleProfiles } from "@/modules/learner/access"; import { getActiveProfile } from "@/modules/learner/selection"; import { submitListening } from "@/modules/listening/actions"; import {vocabularyLevelFallbacks} from "@/modules/vocabulary/levels";import{selectClosestLevelItems}from"@/modules/content/level-selection";

export default async function ListeningPage() {
  const session = await auth(); const english = (await cookies()).get("ui_locale")?.value === "en"; const selected = await getActiveProfile(await getAccessibleProfiles(session!.user.id));
  const preferredLevels=selected?.level?vocabularyLevelFallbacks(selected.level):[];const exercisesRaw = await db.listeningExercise.findMany({ where: { status: "PUBLISHED", ...(preferredLevels.length ? { level:{in:preferredLevels} } : {}) }, include: { questions: { orderBy: { order: "asc" } }, progress: selected ? { where: { learnerProfileId: selected.id } } : false } });const exercises=selectClosestLevelItems(exercisesRaw,selected?.level,item=>item.level);
  const t = english ? { title: "Listening practice", reveal: "Show transcript and translation", submit: "Submit answers", latest: "Latest score", attempts: "attempts", empty: "No listening lessons are available for this level yet." } : { title: "听力训练", reveal: "显示听力原文和翻译", submit: "提交听力答案", latest: "最近成绩", attempts: "次尝试", empty: "当前级别还没有听力内容。" };
  return <div className="mx-auto max-w-5xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">Listening</p><h1 className="mt-2 text-4xl font-black">{t.title}</h1><div className="mt-7 space-y-5">{selected && exercises.map((exercise) => <article className="card" key={exercise.id}><p className="text-sm font-bold text-brand">{exercise.level} · {exercise.topic}</p><h2 className="mt-2 text-2xl font-black">{exercise.title}</h2><div className="mt-5"><SpeechPlayer text={exercise.transcript}/></div><details className="mt-4"><summary className="cursor-pointer font-bold">{t.reveal}</summary><p className="mt-3 leading-7">{exercise.transcript}</p>{!english && <p className="mt-2 text-muted">{exercise.translation}</p>}</details><form action={submitListening} className="mt-6 border-t pt-5"><input type="hidden" name="profileId" value={selected.id}/><input type="hidden" name="exerciseId" value={exercise.id}/><div className="space-y-5">{exercise.questions.map((question, index) => { const options = Array.isArray(question.options) ? question.options as string[] : []; return <fieldset key={question.id}><legend className="font-bold">{index + 1}. {question.prompt}</legend>{options.map((option) => <label className="mt-2 block rounded-xl border p-3" key={option}><input className="mr-2" type="radio" name={`question_${question.id}`} value={option}/>{option}</label>)}</fieldset>; })}</div><button className="button-primary mt-5">{t.submit}</button>{exercise.progress[0]?.score != null && <p className="mt-3 font-bold">{t.latest}: {Math.round(exercise.progress[0].score * 100)} · {exercise.progress[0].attempts} {t.attempts}</p>}</form></article>)}</div>{selected && !exercises.length && <div className="card mt-7">{t.empty}</div>}</div>;
}

