import { AIUsagePurpose } from "@prisma/client";
import { cookies } from "next/headers";
import { db } from "@/lib/db";
import { maskApiKey } from "@/lib/settings-crypto";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";
import { addModel, deleteProvider, removeModel, removeRouteModel, saveModel, saveProvider, saveRoute, testProvider, testProviderGeneration, toggleProvider, toggleRoute, updateRouteModel } from "@/modules/ai/admin-actions";
import { providerPresets } from "@/modules/ai/provider-presets";
import { summarizeAIUsage } from "@/modules/ai/usage-stats";

const purposeLabels: Record<AIUsagePurpose, string> = {
  TUTOR: "AI 英语老师", VOCABULARY: "单词解释", READING: "阅读生成", QUIZ: "出题", GRAMMAR: "语法批改", WRITING: "写作批改",
  LEARNING_PLAN: "学习计划", TRANSLATION: "翻译", SPEECH_RECOGNITION: "语音识别", TTS: "TTS", IMAGE_GENERATION: "图片生成", VIDEO_GENERATION: "视频生成"
};

export default async function AIAdminPage() {
  await requireSystemAdmin();
  const english=(await cookies()).get("ui_locale")?.value==="en";
  const t=english?{title:"AI model management",security:"API keys are encrypted and stored only on the server. The page never returns the full value of an existing key.",addProvider:"Add provider",name:"Configuration name",type:"Provider type",timeout:"Timeout (ms)",priority:"Priority",notes:"Notes",saveProvider:"Save provider",enabled:"Enabled",disabled:"Disabled",lastTest:"Last test",success:"Success",failure:"Failure",untested:"Not tested",testOutput:"Test output",testGeneration:"Test generation",testConnection:"Test connection",disable:"Disable",enable:"Enable",remove:"Delete",editProvider:"Edit provider",newKey:"New API key (leave blank to keep existing)",saveChanges:"Save changes",models:"Models",default:"Default",displayName:"Display name",capabilities:"Capabilities (comma-separated)",providerDefault:"Set as provider default",saveModel:"Save model",removeModel:"Remove model",noModels:"No models yet. Add one before testing the connection.",modelName:"Model name / API ID",setDefault:"Set as default",addModel:"Add model",usage:"API usage in the last 7 days",requests:"Requests",successRate:"Success rate",latency:"Average latency",inputTokens:"Input tokens",outputTokens:"Output tokens",token:"Tokens",errors:"Error categories",noFailures:"No failures",routes:"AI purpose routing",routeHelp:"Add one or more models for each purpose. Lower numbers have higher priority; failures fall back in order.",addRoute:"Add route",addFirst:"Add a model first.",removeRoute:"Remove from this purpose",noRouteModels:"No models"}:{title:"AI 模型管理",security:"API Key 仅在服务器端加密保存，页面永远不会返回旧 Key 的完整值。",addProvider:"添加 Provider",name:"配置名称",type:"Provider 类型",timeout:"超时（毫秒）",priority:"优先级",notes:"备注",saveProvider:"保存 Provider",enabled:"已启用",disabled:"已停用",lastTest:"最近测试",success:"成功",failure:"失败",untested:"尚未测试",testOutput:"测试生成",testGeneration:"测试生成",testConnection:"测试连接",disable:"停用",enable:"启用",remove:"删除",editProvider:"编辑 Provider",newKey:"新 API Key（留空保持原值）",saveChanges:"保存修改",models:"模型",default:"默认",displayName:"显示名称",capabilities:"Capabilities（逗号分隔）",providerDefault:"设为 Provider 默认模型",saveModel:"保存模型",removeModel:"移除模型",noModels:"尚未添加模型；添加后才能测试连接。",modelName:"模型名称/API ID",setDefault:"设为默认",addModel:"添加模型",usage:"最近 7 天 API 使用统计",requests:"请求",successRate:"成功率",latency:"平均延迟",inputTokens:"输入 Token",outputTokens:"输出 Token",token:"Token",errors:"错误分类",noFailures:"无失败",routes:"AI 用途路由",routeHelp:"为每个用途添加一个或多个模型；数字越小越优先，失败时按顺序切换。",addRoute:"添加路由",addFirst:"请先添加模型。",removeRoute:"从此用途移除",noRouteModels:"无模型"};
  const sevenDaysAgo = new Date(Date.now() - 7 * 86_400_000);
  const [providers, routes, requestLogs] = await Promise.all([
    db.aIProvider.findMany({ where: { deletedAt: null }, include: { models: { orderBy: { priority: "asc" } } }, orderBy: { priority: "asc" } }),
    db.aIUsageRoute.findMany({ include: { models: { include: { model: { include: { provider: true } } }, orderBy: { priority: "asc" } } } }),
    db.aIRequestLog.findMany({ where: { createdAt: { gte: sevenDaysAgo } }, include: { provider: { select: { name: true } } }, orderBy: { createdAt: "desc" }, take: 5000 })
  ]);
  const models = providers.flatMap((provider) => provider.models.map((model) => ({ ...model, providerName: provider.name })));
  const usage = summarizeAIUsage(requestLogs);

  return <div className="mx-auto max-w-6xl">
    <p className="text-sm font-bold uppercase tracking-[.2em] text-brand">AI Platform</p><h1 className="mt-2 text-4xl font-black">{t.title}</h1>
    <p className="mt-2 text-muted">{t.security}</p>

    <details className="card mt-8" open={!providers.length}>
      <summary className="cursor-pointer text-xl font-bold">{t.addProvider}</summary>
      <form action={saveProvider} className="mt-5 grid gap-4 md:grid-cols-2">
        <label><span className="label">{t.name}</span><input className="input" name="name" required /></label>
        <label><span className="label">{english ? "Common provider preset" : "常用 Provider 预设"}</span><select className="input" name="preset" defaultValue="OPENAI"><option value="CUSTOM">{english ? "Custom / advanced" : "自定义 / 高级"}</option>{providerPresets.map((preset) => <option value={preset.id} key={preset.id}>{preset.label} · {preset.models.join(" / ")}</option>)}</select></label>
        <label><span className="label">{t.type}</span><select className="input" name="type" defaultValue="OPENAI"><option>OPENAI</option><option>OPENROUTER</option><option>GEMINI</option><option>OPENAI_COMPATIBLE</option><option>OLLAMA</option></select></label>
        <label className="md:col-span-2"><span className="label">Base URL</span><input className="input" type="url" name="baseUrl" required defaultValue="https://api.openai.com/v1" /></label>
        <label><span className="label">API Key</span><input className="input" type="password" name="apiKey" autoComplete="new-password" /></label>
        <label><span className="label">{t.timeout}</span><input className="input" type="number" name="timeoutMs" defaultValue="30000" /></label>
        <label><span className="label">{t.priority}</span><input className="input" type="number" name="priority" defaultValue="100" /></label>
        <label><span className="label">{t.notes}</span><input className="input" name="notes" /></label>
        <div className="md:col-span-2"><button className="button-primary">{t.saveProvider}</button></div>
      </form>
    </details>

    <div className="mt-6 space-y-5">{providers.map((provider) => <section className="card" key={provider.id}>
      <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-2xl font-bold">{provider.name}</h2><p className="text-sm text-muted">{provider.type} · {provider.baseUrl} · Key {maskApiKey(Boolean(provider.encryptedApiKey))}</p></div><span className={provider.enabled ? "text-brand" : "text-muted"}>{provider.enabled ? t.enabled : t.disabled}</span></div>
      <div className="mt-3 text-sm text-muted">{t.lastTest}: {provider.lastConnectionAt ? `${provider.lastConnectionOk ? t.success : t.failure} · ${provider.lastConnectionMs}ms` : t.untested}{provider.lastConnectionError ? ` · ${provider.lastConnectionError}` : ""}</div>
      {provider.lastTestOutput && <p className="mt-2 rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-800">{t.testOutput}: {provider.lastTestOutput}</p>}
      <form action={testProviderGeneration} className="mt-3"><input type="hidden" name="id" value={provider.id}/><button className="button-ghost">{t.testGeneration}</button></form>
      <div className="mt-4 flex flex-wrap gap-2"><form action={testProvider}><input type="hidden" name="id" value={provider.id}/><button className="button-ghost">{t.testConnection}</button></form><form action={toggleProvider}><input type="hidden" name="id" value={provider.id}/><button className="button-ghost">{provider.enabled ? t.disable : t.enable}</button></form><form action={deleteProvider}><input type="hidden" name="id" value={provider.id}/><button className="button-ghost text-red-700 dark:text-red-300">{t.remove}</button></form></div>

      <details className="mt-5 border-t border-slate-200 pt-4 dark:border-slate-700"><summary className="cursor-pointer font-semibold text-brand">{t.editProvider}</summary><form action={saveProvider} className="mt-4 grid gap-3 md:grid-cols-2"><input type="hidden" name="providerId" value={provider.id}/><input type="hidden" name="type" value={provider.type}/><label><span className="label">{t.name}</span><input className="input" name="name" defaultValue={provider.name}/></label><label><span className="label">Base URL</span><input className="input" name="baseUrl" defaultValue={provider.baseUrl}/></label><label><span className="label">{t.newKey}</span><input className="input" type="password" name="apiKey"/></label><label><span className="label">{t.timeout}</span><input className="input" type="number" name="timeoutMs" defaultValue={provider.timeoutMs}/></label><label><span className="label">{t.priority}</span><input className="input" type="number" name="priority" defaultValue={provider.priority}/></label><label><span className="label">{t.notes}</span><input className="input" name="notes" defaultValue={provider.notes ?? ""}/></label><button className="button-primary">{t.saveChanges}</button></form></details>

      <div className="mt-6"><h3 className="font-bold">{t.models}</h3><div className="mt-2 space-y-2">{provider.models.map((model) => <details className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800" key={model.id}><summary className="cursor-pointer"><strong>{model.displayName}</strong> <span className="text-muted">{model.name} · {model.enabled ? model.status : "DISABLED"} · {t.priority} {model.priority}{model.isDefault ? ` · ${t.default}` : ""}</span></summary><form action={saveModel} className="mt-4 grid gap-3 md:grid-cols-3"><input type="hidden" name="modelId" value={model.id}/><input type="hidden" name="providerId" value={provider.id}/><label><span className="label">API Model ID</span><input className="input" name="name" defaultValue={model.name} required/></label><label><span className="label">{t.displayName}</span><input className="input" name="displayName" defaultValue={model.displayName} required/></label><label><span className="label">{t.capabilities}</span><input className="input" name="capabilities" defaultValue={model.capabilities.join(",")}/></label><label><span className="label">Temperature</span><input className="input" type="number" step="0.1" name="temperature" defaultValue={model.temperature}/></label><label><span className="label">Max Tokens</span><input className="input" type="number" name="maxTokens" defaultValue={model.maxTokens}/></label><label><span className="label">{t.priority}</span><input className="input" type="number" name="priority" defaultValue={model.priority}/></label><label className="flex items-center gap-2"><input type="checkbox" name="enabled" defaultChecked={model.enabled}/>{t.enable}</label><label className="flex items-center gap-2"><input type="checkbox" name="isDefault" defaultChecked={model.isDefault}/>{t.providerDefault}</label><button className="button-primary">{t.saveModel}</button></form><form action={removeModel} className="mt-3"><input type="hidden" name="id" value={model.id}/><button className="button-ghost text-red-700">{t.removeModel}</button></form></details>)}{!provider.models.length && <p className="text-sm text-muted">{t.noModels}</p>}</div>
        <form action={addModel} className="mt-4 grid gap-3 md:grid-cols-3"><input type="hidden" name="providerId" value={provider.id}/><input className="input mt-0" name="name" placeholder={t.modelName} required/><input className="input mt-0" name="displayName" placeholder={t.displayName} required/><input className="input mt-0" name="capabilities" defaultValue="chat,structured-output"/><input className="input mt-0" type="number" step="0.1" name="temperature" defaultValue="0.7"/><input className="input mt-0" type="number" name="maxTokens" defaultValue="2048"/><input className="input mt-0" type="number" name="priority" defaultValue="100"/><label className="flex items-center gap-2"><input type="checkbox" name="isDefault"/>{t.setDefault}</label><button className="button-primary">{t.addModel}</button></form>
      </div>
    </section>)}</div>

    <section className="card mt-6"><h2 className="text-xl font-bold">{t.usage}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Stat label={t.requests} value={usage.total}/><Stat label={t.successRate} value={`${usage.successRate}%`}/><Stat label={t.latency} value={`${usage.averageLatencyMs}ms`}/><Stat label={t.inputTokens} value={usage.inputTokens}/><Stat label={t.outputTokens} value={usage.outputTokens}/></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Provider</th><th>{t.requests}</th><th>{t.successRate}</th><th>{t.latency}</th><th>{t.token}</th></tr></thead><tbody>{usage.providers.map((item) => <tr className="border-t" key={item.name}><td className="p-2 font-bold">{item.name}</td><td>{item.total}</td><td>{item.successRate}%</td><td>{item.averageLatencyMs}ms</td><td>{item.tokens}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm text-muted">{t.errors}: {usage.errors.map(([type, count]) => `${type} ${count}`).join(" · ") || t.noFailures}</p></section>

    <section className="card mt-6"><h2 className="text-xl font-bold">{t.routes}</h2><p className="mt-1 text-sm text-muted">{t.routeHelp}</p>
      {models.length ? <form action={saveRoute} className="mt-5 grid gap-3 md:grid-cols-[1fr_2fr_1fr_auto]"><select className="input mt-0" name="purpose">{Object.values(AIUsagePurpose).map((purpose) => <option value={purpose} key={purpose}>{english?purpose.replaceAll("_"," "):purposeLabels[purpose]}</option>)}</select><select className="input mt-0" name="modelId">{models.map((model) => <option value={model.id} key={model.id}>{model.providerName} / {model.displayName}</option>)}</select><input className="input mt-0" type="number" name="priority" defaultValue="100"/><button className="button-primary">{t.addRoute}</button></form> : <p className="mt-4 text-muted">{t.addFirst}</p>}
      <div className="mt-5 space-y-3">{routes.map((route) => <div className="rounded-xl border border-slate-200 p-4 dark:border-slate-700" key={route.id}><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{english?route.purpose.replaceAll("_"," "):purposeLabels[route.purpose]}</strong><span className={`ml-2 text-xs font-bold ${route.enabled?"text-emerald-700":"text-muted"}`}>{route.enabled?(english?"ACTIVE":"已启用"):(english?"PAUSED":"已暂停")}</span></div><form action={toggleRoute}><input type="hidden" name="id" value={route.id}/><button className="button-ghost">{route.enabled?(english?"Pause route":"暂停整条路由"):(english?"Enable route":"启用整条路由")}</button></form></div><div className="mt-3 grid gap-2">{route.models.map((item) => <div className="rounded-lg bg-slate-100 p-3 text-sm dark:bg-slate-800" key={item.id}><form action={updateRouteModel} className="grid items-end gap-2 sm:grid-cols-[1fr_120px_auto_auto]"><input type="hidden" name="id" value={item.id}/><span className={item.enabled?"font-semibold":"text-muted line-through"}>{item.model.provider.name}/{item.model.displayName}</span><label><span className="text-xs text-muted">{t.priority}</span><input className="input mt-1" type="number" name="priority" min="1" max="10000" defaultValue={item.priority}/></label><label className="flex items-center gap-2 pb-3"><input type="checkbox" name="enabled" defaultChecked={item.enabled}/>{english?"Enabled":"启用"}</label><button className="button-primary">{english?"Save":"保存"}</button></form><form action={removeRouteModel} className="mt-2"><input type="hidden" name="id" value={item.id}/><button className="text-xs font-bold text-red-700">{t.removeRoute}</button></form></div>)}{!route.models.length && <span className="text-sm text-muted">{t.noRouteModels}</span>}</div></div>)}</div>
    </section>
  </div>;
}

function Stat({ label, value }: { label: string; value: string | number }) { return <div className="metric"><span className="text-muted">{label}</span><strong className="text-2xl">{value}</strong></div>; }
