import { auth } from "@/auth";
import { db } from "@/lib/db";
import { ProfilePicker } from "@/components/profile-picker";
import { getAccessibleProfiles } from "@/modules/learner/access";
import { createConversation, sendTutorMessage, toggleMessageReview } from "@/modules/tutor/actions";

export default async function TutorPage({ searchParams }: { searchParams: Promise<{ profile?: string; conversation?: string }> }) {
  const session = await auth(); const params = await searchParams;
  const profiles = await getAccessibleProfiles(session!.user.id); const selected = profiles.find((profile) => profile.id === params.profile) ?? profiles[0];
  const conversations = selected ? await db.aIConversation.findMany({ where: { learnerProfileId: selected.id }, orderBy: { lastMessageAt: "desc" }, take: 20 }) : [];
  const current = params.conversation && selected ? await db.aIConversation.findFirst({ where: { id: params.conversation, learnerProfileId: selected.id }, include: { messages: { orderBy: { sequence: "asc" } } } }) : null;
  return <div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-brand">AI Tutor</p><h1 className="mt-2 text-4xl font-black">AI 英语老师</h1><ProfilePicker profiles={profiles} selectedId={selected?.id} pathname="/learn/tutor" />
    {selected && <div className="mt-7 grid gap-5 lg:grid-cols-[300px_1fr]"><aside className="card"><h2 className="font-bold">开始新主题</h2><form action={createConversation} className="mt-4 space-y-3"><input type="hidden" name="profileId" value={selected.id}/><input className="input mt-0" name="topic" placeholder="例如：餐厅点餐" required/><select className="input mt-0" name="teacherStyle"><option value="GENTLE">温和型</option><option value="STRICT">严格纠错型</option><option value="CHILD">儿童启蒙型</option><option value="ACADEMIC">高中学术型</option><option value="US_LIFE">美国生活英语型</option><option value="WORKPLACE">职场英语型</option></select><button className="button-primary w-full">新建对话</button></form><div className="mt-6 space-y-2">{conversations.map((item) => <a className="block rounded-xl border border-slate-200 p-3 text-sm hover:border-brand dark:border-slate-700" href={`/learn/tutor?profile=${selected.id}&conversation=${item.id}`} key={item.id}>{item.topic}</a>)}</div></aside>
      <section className="card min-h-[32rem]">{current ? <><div className="border-b border-slate-200 pb-4 dark:border-slate-700"><h2 className="text-xl font-bold">{current.topic}</h2><p className="text-sm text-muted">{current.teacherStyle}</p></div><div className="my-5 space-y-4">{current.messages.map((message) => <div className={message.role === "user" ? "ml-auto max-w-[85%] rounded-2xl bg-brand p-4 text-white dark:text-slate-950" : "max-w-[90%] rounded-2xl bg-slate-100 p-4 dark:bg-slate-800"} key={message.id}><p className="whitespace-pre-wrap">{message.content}</p>{message.role === "assistant" && <form action={toggleMessageReview} className="mt-2"><input type="hidden" name="messageId" value={message.id}/><button className="text-xs underline">{message.savedForReview ? "已加入复习" : "加入复习"}</button></form>}</div>)}</div><form action={sendTutorMessage} className="mt-auto flex gap-3"><input type="hidden" name="conversationId" value={current.id}/><textarea className="input mt-0 min-h-24 flex-1" name="content" placeholder="输入英文或中文问题…" required/><button className="button-primary self-end">发送</button></form></> : <div className="grid min-h-[28rem] place-items-center text-center text-muted">选择历史对话或创建一个新主题</div>}</section></div>}
  </div>;
}
