export type PlacementQuestion = { id:string;section:string;prompt:string;options?:string[];answerKey?:string;maxScore:number;passage?:string };

export const placementQuestionPool:PlacementQuestion[]=[
  {id:"vocab-a1-1",section:"基础词汇",prompt:"Choose the word that means ‘预约’.",options:["appointment","argument","apartment"],answerKey:"appointment",maxScore:1},{id:"vocab-a1-2",section:"基础词汇",prompt:"Which word means ‘安静的’ ?",options:["quiet","quite","quick"],answerKey:"quiet",maxScore:1},{id:"vocab-a2-1",section:"基础词汇",prompt:"Choose the best meaning of ‘refund’.",options:["money returned to a customer","a store receipt","a lower price"],answerKey:"money returned to a customer",maxScore:1},{id:"vocab-b1-1",section:"基础词汇",prompt:"Which word best completes: The instructions were clear and ___.",options:["straightforward","temporary","ordinary"],answerKey:"straightforward",maxScore:2},{id:"vocab-b2-1",section:"基础词汇",prompt:"Choose the closest meaning of ‘inevitable’.",options:["impossible to avoid","easy to explain","unlikely to happen"],answerKey:"impossible to avoid",maxScore:2},{id:"vocab-c1-1",section:"基础词汇",prompt:"Choose the closest meaning of ‘meticulous’.",options:["very careful and precise","quick but careless","strongly emotional"],answerKey:"very careful and precise",maxScore:3},
  {id:"sentence-a1-1",section:"句子理解",prompt:"What does ‘I am used to getting up early’ mean?",options:["Getting up early is normal for me.","I got up early once.","I want to stop getting up early."],answerKey:"Getting up early is normal for me.",maxScore:1},{id:"sentence-a2-1",section:"句子理解",prompt:"What does ‘I have lived here for three years’ mean?",options:["I moved away three years ago.","I started living here three years ago and still live here.","I will live here in three years."],answerKey:"I started living here three years ago and still live here.",maxScore:1},{id:"sentence-b1-1",section:"句子理解",prompt:"What does ‘You might want to check the schedule’ imply?",options:["Checking is a suggestion.","Checking is forbidden.","The schedule is certainly wrong."],answerKey:"Checking is a suggestion.",maxScore:2},{id:"sentence-c1-1",section:"句子理解",prompt:"What does ‘His apology fell short of what was expected’ mean?",options:["The apology was insufficient.","He apologized too early.","Everyone accepted the apology."],answerKey:"The apology was insufficient.",maxScore:3},
  {id:"grammar-a1-1",section:"语法",prompt:"She ___ coffee every morning.",options:["drink","drinks","drinking"],answerKey:"drinks",maxScore:1},{id:"grammar-a2-1",section:"语法",prompt:"I ___ dinner when you called.",options:["cooked","was cooking","have cooked"],answerKey:"was cooking",maxScore:1},{id:"grammar-a2-2",section:"语法",prompt:"We have known each other ___ 2019.",options:["for","since","during"],answerKey:"since",maxScore:1},{id:"grammar-b1-1",section:"语法",prompt:"If I ___ more time, I would study another language.",options:["have","had","will have"],answerKey:"had",maxScore:2},{id:"grammar-b2-1",section:"语法",prompt:"The report ___ by Friday, or the project will be delayed.",options:["must finish","must be finished","must have finishing"],answerKey:"must be finished",maxScore:2},{id:"grammar-c1-1",section:"语法",prompt:"Hardly ___ the meeting started when the fire alarm rang.",options:["had","has","did"],answerKey:"had",maxScore:3},
  {id:"listening-a1-1",section:"听力",prompt:"Listen and choose where the speaker is going.",passage:"I need to return these shoes because they are too small.",options:["A store","A hospital","An airport"],answerKey:"A store",maxScore:1},{id:"listening-a2-1",section:"听力",prompt:"Why will the speaker arrive late?",passage:"The train has stopped because of a signal problem, so I will be about twenty minutes late.",options:["A signal problem","Bad weather","A missed alarm"],answerKey:"A signal problem",maxScore:1},{id:"listening-b1-1",section:"听力",prompt:"What does the speaker recommend?",passage:"The museum is crowded in the afternoon. If you want a quieter visit, I would get there as soon as it opens.",options:["Arrive early","Buy tickets in the afternoon","Visit a different city"],answerKey:"Arrive early",maxScore:2},{id:"listening-c1-1",section:"听力",prompt:"What is the speaker's main concern?",passage:"The proposal is promising, but without a realistic timeline and clear ownership, implementation may stall before we see any measurable results.",options:["The implementation plan is unclear","The idea has no value","The results are already available"],answerKey:"The implementation plan is unclear",maxScore:3},
  {id:"reading-a1-1",section:"阅读",prompt:"Why did Maya take the bus?",passage:"Maya usually walks to school, but this morning it was raining heavily, so she took the bus.",options:["She was late.","It was raining.","She hurt her leg."],answerKey:"It was raining.",maxScore:1},{id:"reading-a2-1",section:"阅读",prompt:"What should customers do before visiting?",passage:"The clinic now accepts walk-ins only after 2 p.m. Morning visits must be booked online in advance.",options:["Book morning visits online","Call after every visit","Arrive before the clinic opens"],answerKey:"Book morning visits online",maxScore:1},{id:"reading-b1-1",section:"阅读",prompt:"Why did the company change the schedule?",passage:"After employees reported that the late shift made public transportation difficult, the company moved the shift one hour earlier for a three-month trial.",options:["To improve transportation access","To reduce employee salaries","To close the office earlier forever"],answerKey:"To improve transportation access",maxScore:2},{id:"reading-c1-1",section:"阅读",prompt:"What conclusion does the passage support?",passage:"Although remote work initially raised concerns about collaboration, the study found that teams with clear communication routines maintained productivity while reporting greater schedule flexibility.",options:["Structured communication can support effective remote work","Remote work always reduces collaboration","Schedule flexibility lowers productivity"],answerKey:"Structured communication can support effective remote work",maxScore:3},
  {id:"writing-1",section:"简单写作",prompt:"Write 5–8 English sentences about a goal and the steps you will take to achieve it.",maxScore:3},{id:"writing-2",section:"简单写作",prompt:"Write 5–8 English sentences describing a problem you solved recently.",maxScore:3},{id:"writing-3",section:"简单写作",prompt:"Write a short email asking for information about a class, service, or appointment.",maxScore:3},
  {id:"speaking-1",section:"口语（可选）",prompt:"Introduce yourself and describe one activity you enjoy.",maxScore:2},{id:"speaking-2",section:"口语（可选）",prompt:"Explain what you would say when returning an item to a store.",maxScore:2},{id:"speaking-3",section:"口语（可选）",prompt:"Give your opinion about learning online and support it with one reason.",maxScore:2}
];

const sectionCounts:Record<string,number>={基础词汇:3,句子理解:2,语法:3,听力:2,阅读:2,简单写作:1,"口语（可选）":1};
export function selectPlacementQuestions(version:number,previousQuestionIds:string[]=[],seed=""){const previous=new Set(previousQuestionIds);let hash=version;for(const character of seed)hash=(hash*31+character.charCodeAt(0))>>>0;const selected:PlacementQuestion[]=[];for(const[section,count]of Object.entries(sectionCounts)){const candidates=placementQuestionPool.filter(question=>question.section===section);const fresh=candidates.filter(question=>!previous.has(question.id));const ordered=fresh.length>=count?fresh:[...fresh,...candidates.filter(question=>previous.has(question.id))];const offset=ordered.length?hash%ordered.length:0;for(let index=0;index<Math.min(count,ordered.length);index++)selected.push(ordered[(index+offset)%ordered.length]);hash=(hash*33+section.length)>>>0}return selected}

export function questionsByIds(ids:string[]){const byId=new Map(placementQuestionPool.map(question=>[question.id,question]));return ids.map(id=>byId.get(id)).filter((question):question is PlacementQuestion=>Boolean(question))}
