import Link from "next/link";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { SpeechPlayer } from "@/components/speech-player";
import { db } from "@/lib/db";
import { addVocabularyExample, addVocabularyRelation, deleteVocabularyExample, deleteVocabularyRelation, updateContentStatus, updateVocabularyMetadata } from "@/modules/admin/actions";
import { vocabularyPublishReadiness } from "@/modules/admin/content-schemas";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";

const levels = ["PRE_A1", "A1", "A2", "B1", "B2", "C1", "C2"];
export default async function VocabularyEditorPage({params}:{params:Promise<{id:string}>}) {
  await requireSystemAdmin(); const english=(await cookies()).get("ui_locale")?.value==="en"; const {id}=await params;
  const word=await db.vocabulary.findUnique({where:{id},include:{meanings:{orderBy:{senseOrder:"asc"}},examples:true,relationsFrom:{include:{target:true}}}}); if(!word)notFound();
  const zh=word.meanings.find(item=>item.locale==="zh-CN")?.definition??""; const missing=vocabularyPublishReadiness({meanings:word.meanings.length,examples:word.examples.length});
  const t=english?{back:"Back to content",editor:"Vocabulary entry editor",preview:"Pronunciation preview",status:"Status",update:"Update status",readiness:"Publication readiness",ready:"Ready to publish",missing:"Still required",info:"Complete word entry",phonetic:"Phonetic",part:"Part of speech",definitionEn:"English definition",definitionZh:"Chinese definition",topic:"Topic",audio:"Audio URL (optional)",image:"Image or icon URL (optional)",save:"Save entry",examples:"Context examples and collocations",sentence:"Example sentence",translation:"Translation (optional)",collocations:"Collocations, comma separated",addExample:"Add example",relations:"Synonyms and antonyms",target:"Existing vocabulary word",addRelation:"Add relation",remove:"Remove"}:{back:"返回内容管理",editor:"完整词条编辑器",preview:"发音试听",status:"状态",update:"更新状态",readiness:"发布完整度",ready:"已经达到发布标准",missing:"仍需补齐",info:"完整词条信息",phonetic:"音标",part:"词性",definitionEn:"英文解释",definitionZh:"中文解释",topic:"主题分类",audio:"发音音频 URL（可选）",image:"图片或图标 URL（可选）",save:"保存词条",examples:"情境例句与常见搭配",sentence:"英文例句",translation:"中文翻译（可选）",collocations:"常见搭配（逗号分隔）",addExample:"新增例句",relations:"近义词与反义词",target:"词库中已经存在的目标单词",addRelation:"新增关系",remove:"删除"};
  return <div className="mx-auto max-w-6xl"><Link className="text-sm font-bold text-brand" href="/admin/content">← {t.back}</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-brand">{word.level} · {word.topic}</p><h1 className="mt-1 text-4xl font-black">{t.editor}</h1><p className="mt-2 text-2xl font-bold">{word.word} {word.phonetic}</p></div><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value="vocabulary"/><input type="hidden" name="id" value={word.id}/><label><span className="label">{t.status}</span><select className="input" name="status" defaultValue={word.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><button className="button-primary">{t.update}</button></form></div>
  <section className={missing.length?"mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-100":"mt-6 rounded-2xl border border-emerald-300 bg-emerald-50 p-5 text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"}><h2 className="font-black">{t.readiness}</h2><p className="mt-2">{missing.length?`${t.missing}: ${missing.join(english?", ":"、")}`:`✓ ${t.ready}`}</p></section>
  <section className="card mt-6"><h2 className="text-2xl font-black">{t.preview}</h2><div className="mt-4"><SpeechPlayer text={word.word}/></div>{word.audioUrl&&<audio className="mt-4 w-full" controls src={word.audioUrl}/>}</section>
  <section className="card mt-6"><h2 className="text-2xl font-black">{t.info}</h2><form action={updateVocabularyMetadata} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="vocabularyId" value={word.id}/><Field name="word" label="Word" value={word.word}/><Field name="phonetic" label={t.phonetic} value={word.phonetic??""} optional/><Field name="partOfSpeech" label={t.part} value={word.partOfSpeech??"word"}/><label><span className="label">CEFR</span><select className="input" name="level" defaultValue={word.level}>{levels.map(x=><option key={x}>{x}</option>)}</select></label><Area name="definitionEn" label={t.definitionEn} value={word.definitionEn}/><Area name="definitionZh" label={t.definitionZh} value={zh}/><Field name="topic" label={t.topic} value={word.topic}/><Field name="audioUrl" label={t.audio} value={word.audioUrl??""} optional/><Field name="imageUrl" label={t.image} value={word.imageUrl??""} optional/><button className="button-primary md:col-span-2">{t.save}</button></form></section>
  <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card"><h2 className="text-2xl font-black">{t.examples} ({word.examples.length})</h2><div className="mt-4 space-y-3">{word.examples.map(item=><Row key={item.id} title={item.sentence} subtitle={[item.translation,item.collocations.join(" · ")].filter(Boolean).join(" | ")} action={deleteVocabularyExample} hidden={{vocabularyId:word.id,id:item.id}} remove={t.remove}/>)}</div><form action={addVocabularyExample} className="mt-5 grid gap-3 border-t pt-5"><input type="hidden" name="vocabularyId" value={word.id}/><Field name="sentence" label={t.sentence}/><Field name="translation" label={t.translation} optional/><Field name="collocations" label={t.collocations} optional/><label><span className="label">CEFR</span><select className="input" name="difficulty" defaultValue={word.level}>{levels.map(x=><option key={x}>{x}</option>)}</select></label><button className="button-primary">{t.addExample}</button></form></div>
  <div className="card"><h2 className="text-2xl font-black">{t.relations} ({word.relationsFrom.length})</h2><div className="mt-4 space-y-3">{word.relationsFrom.map(item=><Row key={item.id} title={`${item.type}: ${item.target.word}`} subtitle={item.target.definitionEn} action={deleteVocabularyRelation} hidden={{vocabularyId:word.id,id:item.id}} remove={t.remove}/>)}</div><form action={addVocabularyRelation} className="mt-5 grid gap-3 border-t pt-5"><input type="hidden" name="vocabularyId" value={word.id}/><Field name="targetWord" label={t.target}/><label><span className="label">Type</span><select className="input" name="type"><option>SYNONYM</option><option>ANTONYM</option></select></label><button className="button-primary">{t.addRelation}</button></form></div></section></div>;
}
function Field({name,label,value="",optional=false}:{name:string;label:string;value?:string;optional?:boolean}){return <label><span className="label">{label}</span><input className="input" name={name} defaultValue={value} required={!optional}/></label>}
function Area({name,label,value=""}:{name:string;label:string;value?:string}){return <label><span className="label">{label}</span><textarea className="input min-h-28" name={name} defaultValue={value} required/></label>}
function Row({title,subtitle,action,hidden,remove}:{title:string;subtitle:string;action:(formData:FormData)=>Promise<void>;hidden:Record<string,string>;remove:string}){return <div className="flex items-start justify-between gap-3 rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><div><strong>{title}</strong>{subtitle&&<p className="mt-1 text-sm text-muted">{subtitle}</p>}</div><form action={action}>{Object.entries(hidden).map(([name,value])=><input key={name} type="hidden" name={name} value={value}/>)}<button className="text-xs font-bold text-red-700">{remove}</button></form></div>}
