import { z } from "zod";
const level = z.enum(["PRE_A1", "A1", "A2", "B1", "B2", "C1", "C2"]);
export const vocabularyCourseSchema = z.object({ word: z.string().min(1), phonetic: z.string(), partOfSpeech: z.string(), definitionEn: z.string(), definitionZh: z.string(), level, topic: z.string(), collocations: z.array(z.string()), synonyms: z.array(z.string()), antonyms: z.array(z.string()), examples: z.array(z.object({ sentence: z.string(), translation: z.string() })).min(1) });
const questionTypes=["MULTIPLE_CHOICE", "TRUE_FALSE", "SHORT_ANSWER", "VOCABULARY", "FILL_BLANK", "ERROR_CORRECTION", "REORDER", "TRANSLATION", "SENTENCE_CREATION", "AI_DIALOGUE"] as const;
function record(value:unknown):Record<string,unknown>{return value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{}}
function first(source:Record<string,unknown>,...keys:string[]){for(const key of keys)if(source[key]!==undefined)return source[key]}
function normalizeQuestionType(value:unknown){return typeof value==="string"?value.trim().toUpperCase().replaceAll("-","_").replaceAll(" ","_"):value}
const readingQuestionObject=z.object({ type: z.enum(questionTypes), prompt: z.string().min(1), options: z.array(z.string()).optional(), answerKey: z.string().min(1), explanation: z.string() });
export type ReadingQuestionOutput=z.infer<typeof readingQuestionObject>;
export const readingQuestionSchema = z.preprocess(value=>{const row=record(value);return{...row,type:normalizeQuestionType(row.type),prompt:first(row,"prompt","question","text"),answerKey:first(row,"answerKey","correctAnswer","correct_answer","answer"),explanation:first(row,"explanation","rationale")??""}},readingQuestionObject) as z.ZodType<ReadingQuestionOutput>;
const readingArticleObject=z.object({ title: z.string(), body: z.string().min(100), translation: z.string().optional(), level, audience: z.string(), topic: z.string(), targetVocabulary: z.array(z.string()), targetGrammar: z.array(z.string()), summary: z.string(), questions: z.array(readingQuestionSchema).min(3), oralRetellingPrompt: z.string(), writingExtensionPrompt: z.string() });
export type ReadingArticleOutput=z.infer<typeof readingArticleObject>;
export const readingArticleSchema = z.preprocess(value=>{const root=record(value);const wrapped=record(first(root,"article","lesson","reading"));const row={...root,...wrapped};return{...row,body:first(row,"body","content","text","passage"),audience:first(row,"audience","targetAudience","target_audience"),topic:first(row,"topic","theme","subject"),targetVocabulary:first(row,"targetVocabulary","target_vocabulary","vocabulary")??[],targetGrammar:first(row,"targetGrammar","target_grammar","grammar")??[],summary:first(row,"summary","abstract"),questions:first(root,"questions","comprehensionQuestions","comprehension_questions")??first(row,"questions","comprehensionQuestions","comprehension_questions"),oralRetellingPrompt:first(row,"oralRetellingPrompt","oral_retelling_prompt","retellingPrompt")??"Retell the article in your own words.",writingExtensionPrompt:first(row,"writingExtensionPrompt","writing_extension_prompt","writingPrompt")??"Write a short response related to the article."}},readingArticleObject) as z.ZodType<ReadingArticleOutput>;
export const grammarCourseSchema = z.object({ slug: z.string(), title: z.string(), ruleEn: z.string(), ruleZh: z.string(), level, commonErrors: z.array(z.string()), useCases: z.array(z.string()), contrastExamples: z.array(z.object({ correct: z.string(), incorrect: z.string(), note: z.string() })), examples: z.array(z.object({ sentence: z.string(), translation: z.string(), isError: z.boolean(), explanation: z.string().optional() })), exercises: z.array(readingQuestionSchema) });
export const scenarioCourseSchema = z.object({ category: z.string(), title: z.string(), intro: z.string().min(80), level, cultureTips: z.array(z.string()).min(3), misunderstandings: z.array(z.string()).min(2), naturalExpressions: z.array(z.string()).min(4), dialogues: z.array(z.object({ speaker: z.string(), roleName: z.string(), textEn: z.string().min(8), textZh: z.string().min(4), cameraCue: z.string().optional() })).min(16), exercises: z.array(readingQuestionSchema).min(6) });
export const dailyTaskOutputSchema = z.object({ taskType: z.enum(["VOCABULARY", "READING", "LISTENING", "SPEAKING", "AI_TUTOR", "GRAMMAR", "WRITING", "QUIZ"]), title: z.string(), description: z.string(), estimatedMinutes: z.number().int().positive(), xpReward: z.number().int().nonnegative(), reason: z.string() });
export const weeklyPlanOutputSchema = z.object({ goals: z.array(z.string()).min(1), focusAreas: z.array(z.string()), recommendedCourses: z.array(z.string()), reviewContent: z.array(z.string()), stageGoals: z.array(z.string()), monthlyEvaluation: z.string(), adjustmentSuggestions: z.array(z.string()), items: z.array(z.object({ dayOffset: z.number().int().min(0).max(6), module: z.string(), title: z.string(), target: z.string(), durationMinutes: z.number().int().positive(), reason: z.string() })).min(1) });
export const speakingFeedbackSchema = z.object({ transcript: z.string(), accuracyScore: z.number().min(0).max(100), fluencyScore: z.number().min(0).max(100), grammarScore: z.number().min(0).max(100), completenessScore: z.number().min(0).max(100), naturalnessScore: z.number().min(0).max(100), speechRateWpm: z.number().nonnegative(), pauseCount: z.number().int().nonnegative(), pronunciationIssues: z.array(z.object({ word: z.string(), issue: z.string(), suggestion: z.string() })), summary: z.string() });
export const writingFeedbackOutputSchema = z.object({ grammarScore: z.number().min(0).max(100), spellingScore: z.number().min(0).max(100), vocabularyScore: z.number().min(0).max(100), structureScore: z.number().min(0).max(100), naturalnessScore: z.number().min(0).max(100), annotations: z.array(z.object({ excerpt: z.string(), issue: z.string(), suggestion: z.string() })), suggestions: z.string(), rewrittenVersion: z.string() });
export const placementReportSchema = z.object({ assessedLevel: level, sectionScores: z.record(z.number().min(0).max(100)), strengths: z.array(z.string()), weakAreas: z.array(z.string()), recommendations: z.array(z.string()) });
export const learningReportSchema = z.object({ metrics: z.object({ durationMinutes: z.number().nonnegative(), completionRate: z.number().min(0).max(100), averageScore: z.number().min(0).max(100).nullable() }), strengths: z.array(z.string()), weakAreas: z.array(z.string()), recommendations: z.array(z.string()) });
export const weeklyReportSchema = learningReportSchema.extend({ period: z.literal("WEEKLY") });
export const monthlyReportSchema = learningReportSchema.extend({ period: z.literal("MONTHLY") });
