import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { auth } from "@/auth"; import { db } from "@/lib/db"; import { ReadingViewer } from "@/components/reading-viewer"; import { getAccessibleProfiles } from "@/modules/learner/access"; import { getActiveProfile } from "@/modules/learner/selection"; import { submitReading } from "@/modules/reading/actions";

export default async function ArticlePage({ params }: { params: Promise<{ id: string }> }) {
  const session = await auth(); const english = (await cookies()).get("ui_locale")?.value === "en"; const { id } = await params; const selected = await getActiveProfile(await getAccessibleProfiles(session!.user.id)); if (!selected) notFound(); const profileId = selected.id;
  const article = await db.readingArticle.findFirst({ where: { id, status: "PUBLISHED" }, include: { questions: { orderBy: { order: "asc" } }, progress: { where: { learnerProfileId: profileId }, include: { answers: true } } } }); if (!article) notFound(); const progress = article.progress[0];
  const vocabulary = await db.vocabulary.findMany({ where: { status: "PUBLISHED", word: { in: article.targetVocabulary, mode: "insensitive" } }, include: { meanings: { where: { locale: "zh-CN" }, orderBy: { senseOrder: "asc" }, take: 1 } } });
  const t = english ? { vocabulary: "Target vocabulary", grammar: "Target grammar", general: "General", noZh: "No Chinese explanation", summary: "Article summary", summaryFallback: "Summarize the article in your own words after reading.", retell: "Oral retelling", retellFallback: "Retell the main ideas in English.", writing: "Writing extension", writingFallback: "Write an English paragraph about the article topic.", exercises: "Comprehension and extension", submit: "Submit answers and complete reading", score: "Latest score" } : { vocabulary: "目标词汇", grammar: "目标语法", general: "综合", noZh: "暂无中文解释", summary: "文章总结", summaryFallback: "完成阅读后，用自己的话概括文章。", retell: "口头复述", retellFallback: "用英语复述文章主要内容。", writing: "写作延伸", writingFallback: "根据文章主题写一段英文。", exercises: "理解与延伸练习", submit: "提交答案并完成阅读", score: "最近成绩" };
  return <div className="mx-auto max-w-4xl"><p className="text-sm font-bold text-brand">{article.level} · {article.topic}</p><h1 className="mt-2 text-4xl font-black">{article.title}</h1><p className="mt-2 text-muted">{t.vocabulary}: {article.targetVocabulary.join(english ? ", " : "、") || t.general} · {t.grammar}: {article.targetGrammar.join(english ? ", " : "、") || t.general}</p><ReadingViewer profileId={profileId} articleId={article.id} body={article.body} translation={article.translation} targetVocabulary={article.targetVocabulary} targetGrammar={article.targetGrammar} dictionary={vocabulary.map((item) => ({ word: item.word, phonetic: item.phonetic, definitionEn: item.definitionEn, definition: item.meanings[0]?.definition ?? t.noZh }))} initialPercent={progress?.progressPercent} initialPosition={progress?.currentPosition} immersion={english}/><section className="card mt-5 grid gap-4 md:grid-cols-3"><div><h2 className="font-black">{t.summary}</h2><p className="mt-2 text-sm text-muted">{article.summary || t.summaryFallback}</p></div><div><h2 className="font-black">{t.retell}</h2><p className="mt-2 text-sm text-muted">{article.oralRetellingPrompt || t.retellFallback}</p></div><div><h2 className="font-black">{t.writing}</h2><p className="mt-2 text-sm text-muted">{article.writingExtensionPrompt || t.writingFallback}</p></div></section><form action={submitReading} className="card mt-5"><input type="hidden" name="profileId" value={profileId}/><input type="hidden" name="articleId" value={article.id}/><input type="hidden" name="readingSeconds" value="0"/><h2 className="text-2xl font-black">{t.exercises}</h2><div className="mt-5 space-y-6">{article.questions.map((question, index) => { const previous = progress?.answers.find((answer) => answer.questionId === question.id); const options = Array.isArray(question.options) ? question.options as string[] : []; return <fieldset key={question.id}><legend className="font-bold">{index + 1}. [{question.type}] {question.prompt}</legend>{options.length ? <div className="mt-2 grid gap-2">{options.map((option) => <label className="rounded-xl border border-slate-200 p-3 dark:border-slate-700" key={option}><input className="mr-2" type="radio" name={`question_${question.id}`} value={option} defaultChecked={previous?.answer === option}/>{option}</label>)}</div> : <textarea className="input min-h-24" name={`question_${question.id}`} defaultValue={previous?.answer}/>} {previous && <p className={previous.isCorrect ? "mt-2 text-green-700" : "mt-2 text-red-700"}>{previous.feedback}</p>}</fieldset>; })}</div><button className="button-primary mt-6">{t.submit}</button>{progress?.completedAt && <p className="mt-4 font-bold">{t.score}: {Math.round((progress.score ?? 0) * 100)}</p>}</form></div>;
}
