import { notFound } from "next/navigation";
import { auth } from "@/auth";
import { db } from "@/lib/db";
import { requireProfileAccess } from "@/modules/learner/access";
import { submitReading } from "@/modules/reading/actions";

export default async function ArticlePage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ profile?: string }> }) {
  const session = await auth(); const { id } = await params; const query = await searchParams; if (!query.profile) notFound(); await requireProfileAccess(session!.user.id, query.profile);
  const article = await db.readingArticle.findFirst({ where: { id, status: "PUBLISHED" }, include: { questions: { orderBy: { order: "asc" } }, progress: { where: { learnerProfileId: query.profile }, include: { answers: true } } } }); if (!article) notFound(); const progress = article.progress[0];
  return <div className="mx-auto max-w-4xl"><p className="text-sm font-bold text-brand">{article.level} · {article.topic}</p><h1 className="mt-2 text-4xl font-black">{article.title}</h1><article className="card prose mt-7 max-w-none whitespace-pre-wrap text-lg leading-8 dark:prose-invert">{article.body}</article>{article.translation && <details className="card mt-4"><summary className="cursor-pointer font-bold text-brand">查看中文辅助</summary><p className="mt-4 whitespace-pre-wrap leading-7">{article.translation}</p></details>}<form action={submitReading} className="card mt-5"><input type="hidden" name="profileId" value={query.profile}/><input type="hidden" name="articleId" value={article.id}/><input type="hidden" name="readingSeconds" value="0"/><h2 className="text-2xl font-black">理解测试</h2><div className="mt-5 space-y-6">{article.questions.map((question, index) => { const previous = progress?.answers.find((a) => a.questionId === question.id); const options = Array.isArray(question.options) ? question.options as string[] : []; return <fieldset key={question.id}><legend className="font-bold">{index + 1}. {question.prompt}</legend>{options.length ? <div className="mt-2 grid gap-2">{options.map((option) => <label className="rounded-xl border border-slate-200 p-3 dark:border-slate-700" key={option}><input className="mr-2" type="radio" name={`question_${question.id}`} value={option} defaultChecked={previous?.answer === option}/>{option}</label>)}</div> : <input className="input" name={`question_${question.id}`} defaultValue={previous?.answer}/>} {previous && <p className={previous.isCorrect ? "mt-2 text-green-700" : "mt-2 text-red-700"}>{previous.feedback}</p>}</fieldset>; })}</div><button className="button-primary mt-6">提交答案并完成阅读</button>{progress?.completedAt && <p className="mt-4 font-bold">最近成绩：{Math.round((progress.score ?? 0) * 100)} 分</p>}</form></div>;
}
