import Link from "next/link";
import { cookies } from "next/headers";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { requireSystemAdmin } from "@/modules/authorization/require-admin";
import { addGrammarExample, addGrammarExercise, deleteGrammarItem, updateContentStatus, updateGrammarMetadata } from "@/modules/admin/actions";
import { grammarPublishReadiness } from "@/modules/admin/content-schemas";

const levels = ["PRE_A1", "A1", "A2", "B1", "B2", "C1"];
const types = ["MULTIPLE_CHOICE", "FILL_BLANK", "ERROR_CORRECTION", "REORDER", "TRANSLATION", "SENTENCE_CREATION", "AI_DIALOGUE"];

export default async function GrammarEditorPage({ params }: { params: Promise<{ id: string }> }) {
  await requireSystemAdmin(); const english = (await cookies()).get("ui_locale")?.value === "en"; const { id } = await params;
  const topic = await db.grammarTopic.findUnique({ where: { id }, include: { examples: true, exercises: { orderBy: { order: "asc" } } } }); if (!topic) notFound();
  const contrasts = Array.isArray(topic.contrastExamples) ? topic.contrastExamples as Array<{ correct?: string; incorrect?: string; note?: string }> : [];
  const missing = grammarPublishReadiness({ examples: topic.examples.length, exercises: topic.exercises.length, useCases: topic.useCases.length, commonErrors: topic.commonErrors.length });
  const t = english ? { back:"Back to content", editor:"Grammar lesson editor", readiness:"Publication readiness", ready:"Ready to publish", missing:"Still required", info:"Lesson information", slug:"Slug", title:"Title", ruleEn:"Short English rule", ruleZh:"Chinese explanation", uses:"Use cases, one per line", errors:"Common errors, one per line", contrasts:"Contrasts: correct | incorrect | note, one per line", save:"Save lesson information", examples:"Correct and incorrect examples", addExample:"Add example", sentence:"Sentence", translation:"Translation", explanation:"Explanation", wrong:"This is an incorrect example", exercises:"Practice exercises", addExercise:"Add exercise", prompt:"Prompt", options:"Options, one per line; only needed for multiple choice", answer:"Answer key", remove:"Remove", status:"Status", update:"Update status" } : { back:"返回内容管理", editor:"语法课程编辑器", readiness:"发布完整度", ready:"已经达到发布标准", missing:"仍需补齐", info:"课程信息", slug:"Slug", title:"标题", ruleEn:"简短英文规则", ruleZh:"中文解释", uses:"适用场景（每行一条）", errors:"常见错误（每行一条）", contrasts:"对比示例：正确句 | 错误句 | 说明（每行一组）", save:"保存课程信息", examples:"正确与错误例句", addExample:"新增例句", sentence:"例句", translation:"翻译", explanation:"说明", wrong:"这是错误例句", exercises:"多类型练习", addExercise:"新增练习", prompt:"题目", options:"选项，每行一项；仅选择题需要", answer:"标准答案", remove:"删除", status:"状态", update:"更新状态" };
  return <div className="mx-auto max-w-6xl"><Link className="text-sm font-bold text-brand" href="/admin/content">← {t.back}</Link><div className="mt-4 flex flex-wrap items-start justify-between gap-4"><div><p className="font-bold text-brand">{topic.level} · {topic.slug}</p><h1 className="mt-1 text-4xl font-black">{t.editor}</h1><p className="mt-2 text-muted">{topic.title}</p></div><form action={updateContentStatus} className="flex items-end gap-2"><input type="hidden" name="type" value="grammar"/><input type="hidden" name="id" value={topic.id}/><label><span className="label">{t.status}</span><select className="input" name="status" defaultValue={topic.status}><option>DRAFT</option><option>PUBLISHED</option><option>ARCHIVED</option></select></label><button className="button-primary">{t.update}</button></form></div>
  <section className={missing.length ? "mt-6 rounded-2xl border border-amber-300 bg-amber-50 p-5 text-amber-900 dark:bg-amber-950/30 dark:text-amber-100" : "mt-6 rounded-2xl border border-emerald-300 bg-emerald-50 p-5 text-emerald-900 dark:bg-emerald-950/30 dark:text-emerald-100"}><h2 className="font-black">{t.readiness}</h2><p className="mt-2">{missing.length ? `${t.missing}: ${missing.join(english ? ", " : "、")}` : `✓ ${t.ready}`}</p></section>
  <section className="card mt-6"><h2 className="text-2xl font-black">{t.info}</h2><form action={updateGrammarMetadata} className="mt-5 grid gap-4 md:grid-cols-2"><input type="hidden" name="topicId" value={topic.id}/><Field name="slug" label={t.slug} value={topic.slug}/><Field name="title" label={t.title} value={topic.title}/><Area name="ruleEn" label={t.ruleEn} value={topic.ruleEn}/><Area name="ruleZh" label={t.ruleZh} value={topic.ruleZh}/><label><span className="label">CEFR</span><select className="input" name="level" defaultValue={topic.level}>{levels.map(level=><option key={level}>{level}</option>)}</select></label><Area name="useCases" label={t.uses} value={topic.useCases.join("\n")}/><Area name="commonErrors" label={t.errors} value={topic.commonErrors.join("\n")}/><Area name="contrastExamples" label={t.contrasts} value={contrasts.map(item=>`${item.correct ?? ""} | ${item.incorrect ?? ""} | ${item.note ?? ""}`).join("\n")}/><button className="button-primary md:col-span-2">{t.save}</button></form></section>
  <section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="card"><h2 className="text-2xl font-black">{t.examples} ({topic.examples.length})</h2><div className="mt-4 space-y-2">{topic.examples.map(item=><Row key={item.id} title={`${item.isError ? "✕" : "✓"} ${item.sentence}`} subtitle={[item.translation,item.explanation].filter(Boolean).join(" · ")} topicId={topic.id} id={item.id} type="example" remove={t.remove}/>)}</div><form action={addGrammarExample} className="mt-5 grid gap-3 border-t pt-5"><input type="hidden" name="topicId" value={topic.id}/><Field name="sentence" label={t.sentence}/><Field name="translation" label={t.translation} optional/><Field name="explanation" label={t.explanation} optional/><label className="flex items-center gap-2"><input type="checkbox" name="isError"/>{t.wrong}</label><button className="button-primary">{t.addExample}</button></form></div>
  <div className="card"><h2 className="text-2xl font-black">{t.exercises} ({topic.exercises.length})</h2><div className="mt-4 space-y-2">{topic.exercises.map(item=><Row key={item.id} title={`${item.order}. [${item.type}] ${item.prompt}`} subtitle={`${t.answer}: ${item.answerKey}`} topicId={topic.id} id={item.id} type="exercise" remove={t.remove}/>)}</div><form action={addGrammarExercise} className="mt-5 grid gap-3 border-t pt-5"><input type="hidden" name="topicId" value={topic.id}/><label><span className="label">Type</span><select className="input" name="type">{types.map(type=><option key={type}>{type}</option>)}</select></label><Field name="prompt" label={t.prompt}/><Area name="options" label={t.options}/><Field name="answerKey" label={t.answer}/><Field name="explanation" label={t.explanation} optional/><button className="button-primary">{t.addExercise}</button></form></div></section></div>;
}
function Field({name,label,value="",optional=false}:{name:string;label:string;value?:string;optional?:boolean}){return <label><span className="label">{label}</span><input className="input" name={name} defaultValue={value} required={!optional}/></label>}
function Area({name,label,value=""}:{name:string;label:string;value?:string}){return <label><span className="label">{label}</span><textarea className="input min-h-28" name={name} defaultValue={value}/></label>}
function Row({title,subtitle,topicId,id,type,remove}:{title:string;subtitle:string;topicId:string;id:string;type:"example"|"exercise";remove:string}){return <div className="flex items-start justify-between gap-3 rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><div><strong>{title}</strong>{subtitle&&<p className="mt-1 text-sm text-muted">{subtitle}</p>}</div><form action={deleteGrammarItem}><input type="hidden" name="topicId" value={topicId}/><input type="hidden" name="id" value={id}/><input type="hidden" name="type" value={type}/><button className="text-xs font-bold text-red-700">{remove}</button></form></div>}
